/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCryptoTransferRequest,
  CreateWhitelistedAddressRequest,
  CryptoTransfer,
  CryptoWallet,
  WalletFeeEstimateResponse,
  WhitelistedAddress,
} from '../models/index';
import {
    CreateCryptoTransferRequestFromJSON,
    CreateCryptoTransferRequestToJSON,
    CreateWhitelistedAddressRequestFromJSON,
    CreateWhitelistedAddressRequestToJSON,
    CryptoTransferFromJSON,
    CryptoTransferToJSON,
    CryptoWalletFromJSON,
    CryptoWalletToJSON,
    WalletFeeEstimateResponseFromJSON,
    WalletFeeEstimateResponseToJSON,
    WhitelistedAddressFromJSON,
    WhitelistedAddressToJSON,
} from '../models/index';

export interface CreateCryptoTransferForAccountRequest {
    createCryptoTransferRequest: CreateCryptoTransferRequest;
}

export interface CreateWhitelistedAddressOperationRequest {
    createWhitelistedAddressRequest: CreateWhitelistedAddressRequest;
}

export interface DeleteWhitelistedAddressRequest {
    whitelistedAddressId: string;
}

export interface GetCryptoFundingTransferRequest {
    transferId: string;
}

export interface GetCryptoTransferEstimateRequest {
    asset?: string;
    fromAddress?: string;
    toAddress?: string;
    amount?: string;
}

export interface ListCryptoFundingWalletsRequest {
    asset?: string;
    chain?: ListCryptoFundingWalletsChainEnum;
    network?: ListCryptoFundingWalletsNetworkEnum;
}

/**
 * 
 */
export class CryptoFundingApi extends runtime.BaseAPI {

    /**
     * Creates a withdrawal request. Note that outgoing withdrawals must be sent to a whitelisted address and you must whitelist addresses at least 24 hours in advance. If you attempt to withdraw funds to a non-whitelisted address then the transfer will be rejected.
     * Request a New Withdrawal
     */
    async createCryptoTransferForAccountRaw(requestParameters: CreateCryptoTransferForAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoTransfer>> {
        if (requestParameters['createCryptoTransferRequest'] == null) {
            throw new runtime.RequiredError(
                'createCryptoTransferRequest',
                'Required parameter "createCryptoTransferRequest" was null or undefined when calling createCryptoTransferForAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/transfers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCryptoTransferRequestToJSON(requestParameters['createCryptoTransferRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoTransferFromJSON(jsonValue));
    }

    /**
     * Creates a withdrawal request. Note that outgoing withdrawals must be sent to a whitelisted address and you must whitelist addresses at least 24 hours in advance. If you attempt to withdraw funds to a non-whitelisted address then the transfer will be rejected.
     * Request a New Withdrawal
     */
    async createCryptoTransferForAccount(requestParameters: CreateCryptoTransferForAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoTransfer> {
        const response = await this.createCryptoTransferForAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits a new whitelisted withdrawal address for your account. The chain is derived from the supplied asset symbol and address, and the same address cannot be whitelisted twice on the same chain.  Where travel rule reporting applies to your account, address details are validated against the travel rule provider before being persisted.  Note that whitelisted addresses must wait at least 24 hours before they can be used as a withdrawal destination.
     * Request a new whitelisted address
     */
    async createWhitelistedAddressRaw(requestParameters: CreateWhitelistedAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WhitelistedAddress>> {
        if (requestParameters['createWhitelistedAddressRequest'] == null) {
            throw new runtime.RequiredError(
                'createWhitelistedAddressRequest',
                'Required parameter "createWhitelistedAddressRequest" was null or undefined when calling createWhitelistedAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/whitelists`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWhitelistedAddressRequestToJSON(requestParameters['createWhitelistedAddressRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WhitelistedAddressFromJSON(jsonValue));
    }

    /**
     * Submits a new whitelisted withdrawal address for your account. The chain is derived from the supplied asset symbol and address, and the same address cannot be whitelisted twice on the same chain.  Where travel rule reporting applies to your account, address details are validated against the travel rule provider before being persisted.  Note that whitelisted addresses must wait at least 24 hours before they can be used as a withdrawal destination.
     * Request a new whitelisted address
     */
    async createWhitelistedAddress(requestParameters: CreateWhitelistedAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WhitelistedAddress> {
        const response = await this.createWhitelistedAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a whitelisted withdrawal address by ID. Subsequent withdrawals targeting the deleted address will be rejected.
     * Delete a whitelisted address
     */
    async deleteWhitelistedAddressRaw(requestParameters: DeleteWhitelistedAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['whitelistedAddressId'] == null) {
            throw new runtime.RequiredError(
                'whitelistedAddressId',
                'Required parameter "whitelistedAddressId" was null or undefined when calling deleteWhitelistedAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/whitelists/{whitelisted_address_id}`;
        urlPath = urlPath.replace(`{${"whitelisted_address_id"}}`, encodeURIComponent(String(requestParameters['whitelistedAddressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a whitelisted withdrawal address by ID. Subsequent withdrawals targeting the deleted address will be rejected.
     * Delete a whitelisted address
     */
    async deleteWhitelistedAddress(requestParameters: DeleteWhitelistedAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWhitelistedAddressRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a specific wallet transfer by passing into the query the transfer_id.
     * Retrieve a Crypto Funding Transfer
     */
    async getCryptoFundingTransferRaw(requestParameters: GetCryptoFundingTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoTransfer>> {
        if (requestParameters['transferId'] == null) {
            throw new runtime.RequiredError(
                'transferId',
                'Required parameter "transferId" was null or undefined when calling getCryptoFundingTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/transfers/{transfer_id}`;
        urlPath = urlPath.replace(`{${"transfer_id"}}`, encodeURIComponent(String(requestParameters['transferId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoTransferFromJSON(jsonValue));
    }

    /**
     * Returns a specific wallet transfer by passing into the query the transfer_id.
     * Retrieve a Crypto Funding Transfer
     */
    async getCryptoFundingTransfer(requestParameters: GetCryptoFundingTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoTransfer> {
        const response = await this.getCryptoFundingTransferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the estimated on-chain network (gas) fee for a proposed crypto withdrawal at current chain conditions. Pass the `asset`, `from_address`, `to_address`, and `amount` you intend to send; the response reports the network fee that would be charged for the corresponding transaction.
     * Returns the estimated gas fee for a proposed transaction.
     */
    async getCryptoTransferEstimateRaw(requestParameters: GetCryptoTransferEstimateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletFeeEstimateResponse>> {
        const queryParameters: any = {};

        if (requestParameters['asset'] != null) {
            queryParameters['asset'] = requestParameters['asset'];
        }

        if (requestParameters['fromAddress'] != null) {
            queryParameters['from_address'] = requestParameters['fromAddress'];
        }

        if (requestParameters['toAddress'] != null) {
            queryParameters['to_address'] = requestParameters['toAddress'];
        }

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/fees/estimate`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletFeeEstimateResponseFromJSON(jsonValue));
    }

    /**
     * Returns the estimated on-chain network (gas) fee for a proposed crypto withdrawal at current chain conditions. Pass the `asset`, `from_address`, `to_address`, and `amount` you intend to send; the response reports the network fee that would be charged for the corresponding transaction.
     * Returns the estimated gas fee for a proposed transaction.
     */
    async getCryptoTransferEstimate(requestParameters: GetCryptoTransferEstimateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletFeeEstimateResponse> {
        const response = await this.getCryptoTransferEstimateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns an array of all transfers associated with the given account across all wallets.
     * Retrieve Crypto Funding Transfers
     */
    async listCryptoFundingTransfersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoTransfer>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/transfers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoTransferFromJSON(jsonValue));
    }

    /**
     * Returns an array of all transfers associated with the given account across all wallets.
     * Retrieve Crypto Funding Transfers
     */
    async listCryptoFundingTransfers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoTransfer> {
        const response = await this.listCryptoFundingTransfersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lists wallets for the account given in the path parameter. If an asset is specified and no wallet for the account and asset pair exists one will be created. If no asset is specified only existing wallets will be listed for the account. An account may have at most one wallet per asset.
     * Retrieve Crypto Funding Wallets
     */
    async listCryptoFundingWalletsRaw(requestParameters: ListCryptoFundingWalletsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CryptoWallet>> {
        const queryParameters: any = {};

        if (requestParameters['asset'] != null) {
            queryParameters['asset'] = requestParameters['asset'];
        }

        if (requestParameters['chain'] != null) {
            queryParameters['chain'] = requestParameters['chain'];
        }

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CryptoWalletFromJSON(jsonValue));
    }

    /**
     * Lists wallets for the account given in the path parameter. If an asset is specified and no wallet for the account and asset pair exists one will be created. If no asset is specified only existing wallets will be listed for the account. An account may have at most one wallet per asset.
     * Retrieve Crypto Funding Wallets
     */
    async listCryptoFundingWallets(requestParameters: ListCryptoFundingWalletsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CryptoWallet> {
        const response = await this.listCryptoFundingWalletsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the list of whitelisted withdrawal addresses for your account.
     * An array of whitelisted addresses
     */
    async listWhitelistedAddressRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WhitelistedAddress>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/wallets/whitelists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WhitelistedAddressFromJSON(jsonValue));
    }

    /**
     * Returns the list of whitelisted withdrawal addresses for your account.
     * An array of whitelisted addresses
     */
    async listWhitelistedAddress(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WhitelistedAddress> {
        const response = await this.listWhitelistedAddressRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListCryptoFundingWalletsChainEnum = {
    Sol: 'SOL',
    Eth: 'ETH',
    Btc: 'BTC',
    Xrp: 'XRP',
    Arb: 'ARB'
} as const;
export type ListCryptoFundingWalletsChainEnum = typeof ListCryptoFundingWalletsChainEnum[keyof typeof ListCryptoFundingWalletsChainEnum];
/**
 * @export
 */
export const ListCryptoFundingWalletsNetworkEnum = {
    Ethereum: 'ethereum',
    Solana: 'solana'
} as const;
export type ListCryptoFundingWalletsNetworkEnum = typeof ListCryptoFundingWalletsNetworkEnum[keyof typeof ListCryptoFundingWalletsNetworkEnum];
