/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCryptoPerpAccountLeverage200Response,
} from '../models/index';
import {
    GetCryptoPerpAccountLeverage200ResponseFromJSON,
    GetCryptoPerpAccountLeverage200ResponseToJSON,
} from '../models/index';

export interface GetCryptoPerpAccountLeverageRequest {
    symbol?: string;
}

export interface SetCryptoPerpAccountLeverageRequest {
    symbol?: string;
    leverage?: number;
}

/**
 * 
 */
export class CryptoPerpetualsLeverageBetaApi extends runtime.BaseAPI {

    /**
     * Retrieves the current leverage setting for the crypto perpetuals account, specific to a given underlying asset. To use this endpoint, provide the \'symbol\' of the asset as a query parameter. The system will return the asset\'s symbol and the integer value representing the current leverage applied to it within the account
     * Get Account Leverage for an Asset
     */
    async getCryptoPerpAccountLeverageRaw(requestParameters: GetCryptoPerpAccountLeverageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCryptoPerpAccountLeverage200Response>> {
        const queryParameters: any = {};

        if (requestParameters['symbol'] != null) {
            queryParameters['symbol'] = requestParameters['symbol'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/perpetuals/leverage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCryptoPerpAccountLeverage200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the current leverage setting for the crypto perpetuals account, specific to a given underlying asset. To use this endpoint, provide the \'symbol\' of the asset as a query parameter. The system will return the asset\'s symbol and the integer value representing the current leverage applied to it within the account
     * Get Account Leverage for an Asset
     */
    async getCryptoPerpAccountLeverage(requestParameters: GetCryptoPerpAccountLeverageRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCryptoPerpAccountLeverage200Response> {
        const response = await this.getCryptoPerpAccountLeverageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the leverage for the crypto perpetuals account for a specific underlying asset. Provide the \'symbol\' of the asset and the desired \'leverage\' (as an integer) using query parameters. The system will return the asset\'s symbol and the newly set leverage value upon successful update
     * Set Account Leverage for an Asset
     */
    async setCryptoPerpAccountLeverageRaw(requestParameters: SetCryptoPerpAccountLeverageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCryptoPerpAccountLeverage200Response>> {
        const queryParameters: any = {};

        if (requestParameters['symbol'] != null) {
            queryParameters['symbol'] = requestParameters['symbol'];
        }

        if (requestParameters['leverage'] != null) {
            queryParameters['leverage'] = requestParameters['leverage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/perpetuals/leverage`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCryptoPerpAccountLeverage200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates the leverage for the crypto perpetuals account for a specific underlying asset. Provide the \'symbol\' of the asset and the desired \'leverage\' (as an integer) using query parameters. The system will return the asset\'s symbol and the newly set leverage value upon successful update
     * Set Account Leverage for an Asset
     */
    async setCryptoPerpAccountLeverage(requestParameters: SetCryptoPerpAccountLeverageRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCryptoPerpAccountLeverage200Response> {
        const response = await this.setCryptoPerpAccountLeverageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
