/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PortfolioHistory,
} from '../models/index';
import {
    PortfolioHistoryFromJSON,
    PortfolioHistoryToJSON,
} from '../models/index';

export interface GetAccountPortfolioHistoryRequest {
    period?: string;
    timeframe?: string;
    intradayReporting?: GetAccountPortfolioHistoryIntradayReportingEnum;
    start?: Date;
    pnlReset?: GetAccountPortfolioHistoryPnlResetEnum;
    end?: Date;
    extendedHours?: string;
    cashflowTypes?: string;
}

/**
 * 
 */
export class PortfolioHistoryApi extends runtime.BaseAPI {

    /**
     * Returns timeseries data about equity and profit/loss (P/L) of the account in requested timespan.
     * Get Account Portfolio History
     */
    async getAccountPortfolioHistoryRaw(requestParameters: GetAccountPortfolioHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioHistory>> {
        const queryParameters: any = {};

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['intradayReporting'] != null) {
            queryParameters['intraday_reporting'] = requestParameters['intradayReporting'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['pnlReset'] != null) {
            queryParameters['pnl_reset'] = requestParameters['pnlReset'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['extendedHours'] != null) {
            queryParameters['extended_hours'] = requestParameters['extendedHours'];
        }

        if (requestParameters['cashflowTypes'] != null) {
            queryParameters['cashflow_types'] = requestParameters['cashflowTypes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/account/portfolio/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioHistoryFromJSON(jsonValue));
    }

    /**
     * Returns timeseries data about equity and profit/loss (P/L) of the account in requested timespan.
     * Get Account Portfolio History
     */
    async getAccountPortfolioHistory(requestParameters: GetAccountPortfolioHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioHistory> {
        const response = await this.getAccountPortfolioHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAccountPortfolioHistoryIntradayReportingEnum = {
    MarketHours: 'market_hours',
    ExtendedHours: 'extended_hours',
    Continuous: 'continuous'
} as const;
export type GetAccountPortfolioHistoryIntradayReportingEnum = typeof GetAccountPortfolioHistoryIntradayReportingEnum[keyof typeof GetAccountPortfolioHistoryIntradayReportingEnum];
/**
 * @export
 */
export const GetAccountPortfolioHistoryPnlResetEnum = {
    NoReset: 'no_reset',
    PerDay: 'per_day'
} as const;
export type GetAccountPortfolioHistoryPnlResetEnum = typeof GetAccountPortfolioHistoryPnlResetEnum[keyof typeof GetAccountPortfolioHistoryPnlResetEnum];
