/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddAssetToWatchlistRequest,
  UpdateWatchlistRequest,
  Watchlist,
  WatchlistWithoutAsset,
} from '../models/index';
import {
    AddAssetToWatchlistRequestFromJSON,
    AddAssetToWatchlistRequestToJSON,
    UpdateWatchlistRequestFromJSON,
    UpdateWatchlistRequestToJSON,
    WatchlistFromJSON,
    WatchlistToJSON,
    WatchlistWithoutAssetFromJSON,
    WatchlistWithoutAssetToJSON,
} from '../models/index';

export interface AddAssetToWatchlistOperationRequest {
    watchlistId: string;
    addAssetToWatchlistRequest?: AddAssetToWatchlistRequest;
}

export interface AddAssetToWatchlistByNameRequest {
    name: string;
    addAssetToWatchlistRequest?: AddAssetToWatchlistRequest;
}

export interface DeleteWatchlistByIdRequest {
    watchlistId: string;
}

export interface DeleteWatchlistByNameRequest {
    name: string;
}

export interface GetWatchlistByIdRequest {
    watchlistId: string;
}

export interface GetWatchlistByNameRequest {
    name: string;
}

export interface PostWatchlistRequest {
    updateWatchlistRequest: UpdateWatchlistRequest;
}

export interface RemoveAssetFromWatchlistRequest {
    watchlistId: string;
    symbol: string;
}

export interface UpdateWatchlistByIdRequest {
    watchlistId: string;
    updateWatchlistRequest?: UpdateWatchlistRequest;
}

export interface UpdateWatchlistByNameRequest {
    name: string;
    updateWatchlistRequest?: UpdateWatchlistRequest;
}

/**
 * 
 */
export class WatchlistsApi extends runtime.BaseAPI {

    /**
     * Append an asset for the symbol to the end of watchlist asset list
     * Add Asset to Watchlist
     */
    async addAssetToWatchlistRaw(requestParameters: AddAssetToWatchlistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['watchlistId'] == null) {
            throw new runtime.RequiredError(
                'watchlistId',
                'Required parameter "watchlistId" was null or undefined when calling addAssetToWatchlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists/{watchlist_id}`;
        urlPath = urlPath.replace(`{${"watchlist_id"}}`, encodeURIComponent(String(requestParameters['watchlistId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddAssetToWatchlistRequestToJSON(requestParameters['addAssetToWatchlistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Append an asset for the symbol to the end of watchlist asset list
     * Add Asset to Watchlist
     */
    async addAssetToWatchlist(requestParameters: AddAssetToWatchlistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.addAssetToWatchlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Append an asset for the symbol to the end of watchlist asset list
     * Add Asset to Watchlist By Name
     */
    async addAssetToWatchlistByNameRaw(requestParameters: AddAssetToWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling addAssetToWatchlistByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists:by_name`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddAssetToWatchlistRequestToJSON(requestParameters['addAssetToWatchlistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Append an asset for the symbol to the end of watchlist asset list
     * Add Asset to Watchlist By Name
     */
    async addAssetToWatchlistByName(requestParameters: AddAssetToWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.addAssetToWatchlistByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a watchlist. This is a permanent deletion.
     * Delete Watchlist By Id
     */
    async deleteWatchlistByIdRaw(requestParameters: DeleteWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['watchlistId'] == null) {
            throw new runtime.RequiredError(
                'watchlistId',
                'Required parameter "watchlistId" was null or undefined when calling deleteWatchlistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists/{watchlist_id}`;
        urlPath = urlPath.replace(`{${"watchlist_id"}}`, encodeURIComponent(String(requestParameters['watchlistId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a watchlist. This is a permanent deletion.
     * Delete Watchlist By Id
     */
    async deleteWatchlistById(requestParameters: DeleteWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWatchlistByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a watchlist. This is a permanent deletion.
     * Delete Watchlist By Name
     */
    async deleteWatchlistByNameRaw(requestParameters: DeleteWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteWatchlistByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists:by_name`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a watchlist. This is a permanent deletion.
     * Delete Watchlist By Name
     */
    async deleteWatchlistByName(requestParameters: DeleteWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWatchlistByNameRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a watchlist identified by the ID.
     * Get Watchlist by ID
     */
    async getWatchlistByIdRaw(requestParameters: GetWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['watchlistId'] == null) {
            throw new runtime.RequiredError(
                'watchlistId',
                'Required parameter "watchlistId" was null or undefined when calling getWatchlistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists/{watchlist_id}`;
        urlPath = urlPath.replace(`{${"watchlist_id"}}`, encodeURIComponent(String(requestParameters['watchlistId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Returns a watchlist identified by the ID.
     * Get Watchlist by ID
     */
    async getWatchlistById(requestParameters: GetWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.getWatchlistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * You can also call GET, PUT, POST and DELETE with watchlist name with another endpoint /v2/watchlists:by_name and query parameter name=<watchlist_name>, instead of /v2/watchlists/{watchlist_id} endpoints  Returns a watchlist by name
     * Get Watchlist by Name
     */
    async getWatchlistByNameRaw(requestParameters: GetWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getWatchlistByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists:by_name`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * You can also call GET, PUT, POST and DELETE with watchlist name with another endpoint /v2/watchlists:by_name and query parameter name=<watchlist_name>, instead of /v2/watchlists/{watchlist_id} endpoints  Returns a watchlist by name
     * Get Watchlist by Name
     */
    async getWatchlistByName(requestParameters: GetWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.getWatchlistByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the list of watchlists registered under the account.
     * Get All Watchlists
     */
    async getWatchlistsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WatchlistWithoutAsset>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WatchlistWithoutAssetFromJSON));
    }

    /**
     * Returns the list of watchlists registered under the account.
     * Get All Watchlists
     */
    async getWatchlists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WatchlistWithoutAsset>> {
        const response = await this.getWatchlistsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new watchlist with initial set of assets.
     * Create Watchlist
     */
    async postWatchlistRaw(requestParameters: PostWatchlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['updateWatchlistRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWatchlistRequest',
                'Required parameter "updateWatchlistRequest" was null or undefined when calling postWatchlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWatchlistRequestToJSON(requestParameters['updateWatchlistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Create a new watchlist with initial set of assets.
     * Create Watchlist
     */
    async postWatchlist(requestParameters: PostWatchlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.postWatchlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete one entry for an asset by symbol name
     * Delete Symbol from Watchlist
     */
    async removeAssetFromWatchlistRaw(requestParameters: RemoveAssetFromWatchlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['watchlistId'] == null) {
            throw new runtime.RequiredError(
                'watchlistId',
                'Required parameter "watchlistId" was null or undefined when calling removeAssetFromWatchlist().'
            );
        }

        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling removeAssetFromWatchlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists/{watchlist_id}/{symbol}`;
        urlPath = urlPath.replace(`{${"watchlist_id"}}`, encodeURIComponent(String(requestParameters['watchlistId'])));
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Delete one entry for an asset by symbol name
     * Delete Symbol from Watchlist
     */
    async removeAssetFromWatchlist(requestParameters: RemoveAssetFromWatchlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.removeAssetFromWatchlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the name and/or content of watchlist
     * Update Watchlist By Id
     */
    async updateWatchlistByIdRaw(requestParameters: UpdateWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['watchlistId'] == null) {
            throw new runtime.RequiredError(
                'watchlistId',
                'Required parameter "watchlistId" was null or undefined when calling updateWatchlistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists/{watchlist_id}`;
        urlPath = urlPath.replace(`{${"watchlist_id"}}`, encodeURIComponent(String(requestParameters['watchlistId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWatchlistRequestToJSON(requestParameters['updateWatchlistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Update the name and/or content of watchlist
     * Update Watchlist By Id
     */
    async updateWatchlistById(requestParameters: UpdateWatchlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.updateWatchlistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the name and/or content of watchlist
     * Update Watchlist By Name
     */
    async updateWatchlistByNameRaw(requestParameters: UpdateWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Watchlist>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling updateWatchlistByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/watchlists:by_name`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWatchlistRequestToJSON(requestParameters['updateWatchlistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WatchlistFromJSON(jsonValue));
    }

    /**
     * Update the name and/or content of watchlist
     * Update Watchlist By Name
     */
    async updateWatchlistByName(requestParameters: UpdateWatchlistByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Watchlist> {
        const response = await this.updateWatchlistByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
