/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityEventV2AllOfDetails } from './ActivityEventV2AllOfDetails';
import {
    ActivityEventV2AllOfDetailsFromJSON,
    ActivityEventV2AllOfDetailsFromJSONTyped,
    ActivityEventV2AllOfDetailsToJSON,
    ActivityEventV2AllOfDetailsToJSONTyped,
} from './ActivityEventV2AllOfDetails';

/**
 * Represents an account activity, sent over the Event Streaming API.
 * @export
 * @interface ActivityEventV2
 */
export interface ActivityEventV2 {
    /**
     * Sub category for activity type, if any
     * @type {string}
     * @memberof ActivityEventV2
     */
    activitySubtype?: string;
    /**
     * The type of the activity, which can be trade or any of the non trade activities
     * @type {string}
     * @memberof ActivityEventV2
     */
    activityType: string;
    /**
     * Timestamp of event
     * @type {Date}
     * @memberof ActivityEventV2
     */
    at: Date;
    /**
     * Currency code in ISO format
     * @type {string}
     * @memberof ActivityEventV2
     */
    currency: string;
    /**
     * Lexically sortable, monotonically increasing character string
     * @type {string}
     * @memberof ActivityEventV2
     */
    eventId: string;
    /**
     * Execution time for the activity event
     * @type {Date}
     * @memberof ActivityEventV2
     */
    executedAt: Date;
    /**
     * The net amount of money (positive or negative) associated with the activity
     * @type {string}
     * @memberof ActivityEventV2
     */
    netAmount?: string;
    /**
     * Previous ID is presented if this activity corrects or cancels a previous trade or non trade activity. It contains execution_id or trns_id respectively
     * @type {string}
     * @memberof ActivityEventV2
     */
    previousId?: string;
    /**
     * The price of the security involved with the activity
     * @type {string}
     * @memberof ActivityEventV2
     */
    price?: string;
    /**
     * The quantity of the security involved with the activity
     * @type {string}
     * @memberof ActivityEventV2
     */
    qty?: string;
    /**
     * The unique identifier for the activity. For trades, the execution_id is used, for other activities the trns_id is used.
     * @type {string}
     * @memberof ActivityEventV2
     */
    refId: string;
    /**
     * Date when the activity settled
     * @type {Date}
     * @memberof ActivityEventV2
     */
    settleDate: Date;
    /**
     * Status of the activity
     * @type {string}
     * @memberof ActivityEventV2
     */
    status: string;
    /**
     * Currency conversion fee rate base-point in case of local currency activity
     * @type {string}
     * @memberof ActivityEventV2
     */
    swapFeeBps?: string;
    /**
     * Conversion rate for local currency activities
     * @type {string}
     * @memberof ActivityEventV2
     */
    swapRate?: string;
    /**
     * 
     * @type {ActivityEventV2AllOfDetails}
     * @memberof ActivityEventV2
     */
    details: ActivityEventV2AllOfDetails;
}

/**
 * Check if a given object implements the ActivityEventV2 interface.
 */
export function instanceOfActivityEventV2(value: object): value is ActivityEventV2 {
    if (!('activityType' in value) || value['activityType'] === undefined) return false;
    if (!('at' in value) || value['at'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('executedAt' in value) || value['executedAt'] === undefined) return false;
    if (!('refId' in value) || value['refId'] === undefined) return false;
    if (!('settleDate' in value) || value['settleDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function ActivityEventV2FromJSON(json: any): ActivityEventV2 {
    return ActivityEventV2FromJSONTyped(json, false);
}

export function ActivityEventV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityEventV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'activitySubtype': json['activity_subtype'] == null ? undefined : json['activity_subtype'],
        'activityType': json['activity_type'],
        'at': (new Date(json['at'])),
        'currency': json['currency'],
        'eventId': json['event_id'],
        'executedAt': (new Date(json['executed_at'])),
        'netAmount': json['net_amount'] == null ? undefined : json['net_amount'],
        'previousId': json['previous_id'] == null ? undefined : json['previous_id'],
        'price': json['price'] == null ? undefined : json['price'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'refId': json['ref_id'],
        'settleDate': (new Date(json['settle_date'])),
        'status': json['status'],
        'swapFeeBps': json['swap_fee_bps'] == null ? undefined : json['swap_fee_bps'],
        'swapRate': json['swap_rate'] == null ? undefined : json['swap_rate'],
        'details': ActivityEventV2AllOfDetailsFromJSON(json['details']),
    };
}

export function ActivityEventV2ToJSON(json: any): ActivityEventV2 {
    return ActivityEventV2ToJSONTyped(json, false);
}

export function ActivityEventV2ToJSONTyped(value?: ActivityEventV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_subtype': value['activitySubtype'],
        'activity_type': value['activityType'],
        'at': ((value['at']).toISOString()),
        'currency': value['currency'],
        'event_id': value['eventId'],
        'executed_at': ((value['executedAt']).toISOString()),
        'net_amount': value['netAmount'],
        'previous_id': value['previousId'],
        'price': value['price'],
        'qty': value['qty'],
        'ref_id': value['refId'],
        'settle_date': ((value['settleDate']).toISOString().substring(0,10)),
        'status': value['status'],
        'swap_fee_bps': value['swapFeeBps'],
        'swap_rate': value['swapRate'],
        'details': ActivityEventV2AllOfDetailsToJSON(value['details']),
    };
}

