/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - FILL
 *   Order fills (both partial and full fills)
 * 
 * - TRANS
 *   Cash transactions (both CSD and CSW)
 * 
 * - MISC
 *   Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)
 * 
 * - ACATC
 *   ACATS IN/OUT (Cash)
 * 
 * - ACATS
 *   ACATS IN/OUT (Securities)
 * 
 * - CFEE
 *   Crypto fee
 * 
 * - CGD
 *   Capital gain distribution
 * 
 * - CSD
 *   Cash deposit(+)
 * 
 * - CSW
 *   Cash withdrawal(-)
 * 
 * - DIV
 *   Dividends
 * 
 * - DIVCGL
 *   Dividend (capital gain long term)
 * 
 * - DIVCGS
 *   Dividend (capital gain short term)
 * 
 * - DIVFEE
 *   Dividend fee
 * 
 * - DIVFT
 *   Dividend adjusted (Foreign Tax Withheld)
 * 
 * - DIVNRA
 *   Dividend adjusted (NRA Withheld)
 * 
 * - DIVROC
 *   Dividend return of capital
 * 
 * - DIVTW
 *   Dividend adjusted (Tefra Withheld)
 * 
 * - DIVTXEX
 *   Dividend (tax exempt)
 * 
 * - FEE
 *   Fee denominated in USD
 * 
 * - INT
 *   Interest (credit/margin)
 * 
 * - INTNRA
 *   Interest adjusted (NRA Withheld)
 * 
 * - INTTW
 *   Interest adjusted (Tefra Withheld)
 * 
 * - JNL
 *   Journal entry
 * 
 * - JNLC
 *   Journal entry (cash)
 * 
 * - JNLS
 *   Journal entry (stock)
 * 
 * - MA
 *   Merger/Acquisition
 * 
 * - NC
 *   Name change
 * 
 * - OPASN
 *   Option assignment
 * 
 * - OPCA
 *   Option corporate action
 * 
 * - OPCSH
 *   Option cash deliverable for non-standard contracts
 * 
 * - OPEXC
 *   Option exercise
 * 
 * - OPEXP
 *   Option expiration
 * 
 * - OPTRD
 *   Option trade
 * 
 * - PTC
 *   Pass Thru Charge
 * 
 * - PTR
 *   Pass Thru Rebate
 * 
 * - REORG
 *   Reorg CA
 * 
 * - SPIN
 *   Stock spinoff
 * 
 * - SPLIT
 *   Stock split
 * 
 * - FOPT
 *   Free of Payment Transfers
 * @export
 */
export const ActivityType = {
    Fill: 'FILL',
    Trans: 'TRANS',
    Misc: 'MISC',
    Acatc: 'ACATC',
    Acats: 'ACATS',
    Cfee: 'CFEE',
    Cgd: 'CGD',
    Csd: 'CSD',
    Csw: 'CSW',
    Div: 'DIV',
    Divcgl: 'DIVCGL',
    Divcgs: 'DIVCGS',
    Divfee: 'DIVFEE',
    Divft: 'DIVFT',
    Divnra: 'DIVNRA',
    Divroc: 'DIVROC',
    Divtw: 'DIVTW',
    Divtxex: 'DIVTXEX',
    Fee: 'FEE',
    Int: 'INT',
    Intnra: 'INTNRA',
    Inttw: 'INTTW',
    Jnl: 'JNL',
    Jnlc: 'JNLC',
    Jnls: 'JNLS',
    Ma: 'MA',
    Nc: 'NC',
    Opasn: 'OPASN',
    Opca: 'OPCA',
    Opcsh: 'OPCSH',
    Opexc: 'OPEXC',
    Opexp: 'OPEXP',
    Optrd: 'OPTRD',
    Ptc: 'PTC',
    Ptr: 'PTR',
    Reorg: 'REORG',
    Spin: 'SPIN',
    Split: 'SPLIT',
    Fopt: 'FOPT'
} as const;
export type ActivityType = typeof ActivityType[keyof typeof ActivityType];


export function instanceOfActivityType(value: any): boolean {
    for (const key in ActivityType) {
        if (Object.prototype.hasOwnProperty.call(ActivityType, key)) {
            if (ActivityType[key as keyof typeof ActivityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityTypeFromJSON(json: any): ActivityType {
    return ActivityTypeFromJSONTyped(json, false);
}

export function ActivityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityType {
    return json as ActivityType;
}

export function ActivityTypeToJSON(value?: ActivityType | null): any {
    return value as any;
}

export function ActivityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityType {
    return value as ActivityType;
}

