/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Exchange } from './Exchange';
import {
    ExchangeFromJSON,
    ExchangeFromJSONTyped,
    ExchangeToJSON,
    ExchangeToJSONTyped,
} from './Exchange';
import type { AssetAttribute } from './AssetAttribute';
import {
    AssetAttributeFromJSON,
    AssetAttributeFromJSONTyped,
    AssetAttributeToJSON,
    AssetAttributeToJSONTyped,
} from './AssetAttribute';
import type { AssetClass } from './AssetClass';
import {
    AssetClassFromJSON,
    AssetClassFromJSONTyped,
    AssetClassToJSON,
    AssetClassToJSONTyped,
} from './AssetClass';

/**
 * The assets API serves as the master list of assets available for trade and data consumption from Alpaca. Assets are sorted by asset class, exchange and symbol. Some assets are only available for data consumption via Polygon, and are not tradable with Alpaca. These assets will be marked with the flag tradable=false.
 * 
 * @export
 * @interface Assets
 */
export interface Assets {
    /**
     * 
     * @type {Array<AssetAttribute>}
     * @memberof Assets
     */
    attributes?: Array<AssetAttribute>;
    /**
     * Borrow status for US equity assets. This field is omitted for non-US-equity assets.
     * @type {string}
     * @memberof Assets
     */
    borrowStatus?: AssetsBorrowStatusEnum;
    /**
     * 
     * @type {AssetClass}
     * @memberof Assets
     */
    _class: AssetClass;
    /**
     * The CUSIP identifier for the asset (US Equities only).
     * To request a specific CUSIP, please reach out to Alpaca support.
     * 
     * @type {string}
     * @memberof Assets
     */
    cusip?: string | null;
    /**
     * **deprecated**: Please use borrow_status instead.
     * Asset is easy-to-borrow or not (filtering for easy_to_borrow = True is the best way to check whether the name is currently available to short at Alpaca).
     * 
     * @type {boolean}
     * @memberof Assets
     * @deprecated
     */
    easyToBorrow?: boolean;
    /**
     * 
     * @type {Exchange}
     * @memberof Assets
     */
    exchange: Exchange;
    /**
     * Asset is fractionable or not
     * @type {boolean}
     * @memberof Assets
     */
    fractionable: boolean;
    /**
     * Asset ID
     * @type {string}
     * @memberof Assets
     */
    id: string;
    /**
     * **deprecated**: Please use margin_requirement_long or margin_requirement_short instead. Note that these fields are of type string.
     * Shows the margin requirement percentage for the asset (equities only).
     * 
     * @type {number}
     * @memberof Assets
     * @deprecated
     */
    maintenanceMarginRequirement?: number;
    /**
     * The margin requirement percentage for the asset's long positions (equities only).
     * @type {string}
     * @memberof Assets
     */
    marginRequirementLong?: string;
    /**
     * The margin requirement percentage for the asset's short positions (equities only).
     * @type {string}
     * @memberof Assets
     */
    marginRequirementShort?: string;
    /**
     * Asset is marginable or not
     * @type {boolean}
     * @memberof Assets
     */
    marginable: boolean;
    /**
     * Minimum order size. Field available for crypto only.
     * @type {string}
     * @memberof Assets
     */
    minOrderSize?: string;
    /**
     * Amount a trade quantity can be incremented by. Field available for crypto only.
     * @type {string}
     * @memberof Assets
     */
    minTradeIncrement?: string;
    /**
     * The official name of the asset
     * @type {string}
     * @memberof Assets
     */
    name: string;
    /**
     * Amount the price can be incremented by. Field available for crypto only.
     * @type {string}
     * @memberof Assets
     */
    priceIncrement?: string;
    /**
     * Asset is shortable or not
     * @type {boolean}
     * @memberof Assets
     */
    shortable: boolean;
    /**
     * active or inactive
     * @type {string}
     * @memberof Assets
     */
    status: AssetsStatusEnum;
    /**
     * The symbol of the asset
     * @type {string}
     * @memberof Assets
     */
    symbol: string;
    /**
     * Asset is tradable on Alpaca or not
     * @type {boolean}
     * @memberof Assets
     */
    tradable: boolean;
}


/**
 * @export
 */
export const AssetsBorrowStatusEnum = {
    EasyToBorrow: 'easy_to_borrow',
    HardToBorrow: 'hard_to_borrow'
} as const;
export type AssetsBorrowStatusEnum = typeof AssetsBorrowStatusEnum[keyof typeof AssetsBorrowStatusEnum];

/**
 * @export
 */
export const AssetsStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type AssetsStatusEnum = typeof AssetsStatusEnum[keyof typeof AssetsStatusEnum];


/**
 * Check if a given object implements the Assets interface.
 */
export function instanceOfAssets(value: object): value is Assets {
    if (!('_class' in value) || value['_class'] === undefined) return false;
    if (!('exchange' in value) || value['exchange'] === undefined) return false;
    if (!('fractionable' in value) || value['fractionable'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('marginable' in value) || value['marginable'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shortable' in value) || value['shortable'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('tradable' in value) || value['tradable'] === undefined) return false;
    return true;
}

export function AssetsFromJSON(json: any): Assets {
    return AssetsFromJSONTyped(json, false);
}

export function AssetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assets {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AssetAttributeFromJSON)),
        'borrowStatus': json['borrow_status'] == null ? undefined : json['borrow_status'],
        '_class': AssetClassFromJSON(json['class']),
        'cusip': json['cusip'] == null ? undefined : json['cusip'],
        'easyToBorrow': json['easy_to_borrow'] == null ? undefined : json['easy_to_borrow'],
        'exchange': ExchangeFromJSON(json['exchange']),
        'fractionable': json['fractionable'],
        'id': json['id'],
        'maintenanceMarginRequirement': json['maintenance_margin_requirement'] == null ? undefined : json['maintenance_margin_requirement'],
        'marginRequirementLong': json['margin_requirement_long'] == null ? undefined : json['margin_requirement_long'],
        'marginRequirementShort': json['margin_requirement_short'] == null ? undefined : json['margin_requirement_short'],
        'marginable': json['marginable'],
        'minOrderSize': json['min_order_size'] == null ? undefined : json['min_order_size'],
        'minTradeIncrement': json['min_trade_increment'] == null ? undefined : json['min_trade_increment'],
        'name': json['name'],
        'priceIncrement': json['price_increment'] == null ? undefined : json['price_increment'],
        'shortable': json['shortable'],
        'status': json['status'],
        'symbol': json['symbol'],
        'tradable': json['tradable'],
    };
}

export function AssetsToJSON(json: any): Assets {
    return AssetsToJSONTyped(json, false);
}

export function AssetsToJSONTyped(value?: Assets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AssetAttributeToJSON)),
        'borrow_status': value['borrowStatus'],
        'class': AssetClassToJSON(value['_class']),
        'cusip': value['cusip'],
        'easy_to_borrow': value['easyToBorrow'],
        'exchange': ExchangeToJSON(value['exchange']),
        'fractionable': value['fractionable'],
        'id': value['id'],
        'maintenance_margin_requirement': value['maintenanceMarginRequirement'],
        'margin_requirement_long': value['marginRequirementLong'],
        'margin_requirement_short': value['marginRequirementShort'],
        'marginable': value['marginable'],
        'min_order_size': value['minOrderSize'],
        'min_trade_increment': value['minTradeIncrement'],
        'name': value['name'],
        'price_increment': value['priceIncrement'],
        'shortable': value['shortable'],
        'status': value['status'],
        'symbol': value['symbol'],
        'tradable': value['tradable'],
    };
}

