/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reorganization (REO) activity sub-types:
 * - **REOS**: Stock only (1 or more stock legs)
 * - **REOC**: Cash only (one cash leg)
 * - **REOSC**: Stock and cash
 * @export
 * @interface CommonREOActivityV2
 */
export interface CommonREOActivityV2 {
    /**
     * Cash payout amount
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    cashPayout?: string;
    /**
     * Cash rate per share
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    cashRate?: string;
    /**
     * CUSIP received on this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    cusip?: string;
    /**
     * Effective date of the reorganization
     * @type {Date}
     * @memberof CommonREOActivityV2
     */
    effectiveDate?: Date;
    /**
     * ISIN received on this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    isin?: string;
    /**
     * New ratio for this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    newRate?: string;
    /**
     * Payable date of the reorganization
     * @type {Date}
     * @memberof CommonREOActivityV2
     */
    payableDate: Date;
    /**
     * Quantity received on this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    qty?: string;
    /**
     * Positive quantity removed from the source position
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    removedQty?: string;
    /**
     * CUSIP of the source security
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    sourceCusip: string;
    /**
     * ISIN of the source security
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    sourceIsin?: string;
    /**
     * Source position quantity
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    sourceQty?: string;
    /**
     * Source ratio for this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    sourceRate?: string;
    /**
     * Symbol of the source security
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    sourceSymbol: string;
    /**
     * Symbol received on this stock leg
     * @type {string}
     * @memberof CommonREOActivityV2
     */
    symbol?: string;
}

/**
 * Check if a given object implements the CommonREOActivityV2 interface.
 */
export function instanceOfCommonREOActivityV2(value: object): value is CommonREOActivityV2 {
    if (!('payableDate' in value) || value['payableDate'] === undefined) return false;
    if (!('sourceCusip' in value) || value['sourceCusip'] === undefined) return false;
    if (!('sourceSymbol' in value) || value['sourceSymbol'] === undefined) return false;
    return true;
}

export function CommonREOActivityV2FromJSON(json: any): CommonREOActivityV2 {
    return CommonREOActivityV2FromJSONTyped(json, false);
}

export function CommonREOActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonREOActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'cashPayout': json['cash_payout'] == null ? undefined : json['cash_payout'],
        'cashRate': json['cash_rate'] == null ? undefined : json['cash_rate'],
        'cusip': json['cusip'] == null ? undefined : json['cusip'],
        'effectiveDate': json['effective_date'] == null ? undefined : (new Date(json['effective_date'])),
        'isin': json['isin'] == null ? undefined : json['isin'],
        'newRate': json['new_rate'] == null ? undefined : json['new_rate'],
        'payableDate': (new Date(json['payable_date'])),
        'qty': json['qty'] == null ? undefined : json['qty'],
        'removedQty': json['removed_qty'] == null ? undefined : json['removed_qty'],
        'sourceCusip': json['source_cusip'],
        'sourceIsin': json['source_isin'] == null ? undefined : json['source_isin'],
        'sourceQty': json['source_qty'] == null ? undefined : json['source_qty'],
        'sourceRate': json['source_rate'] == null ? undefined : json['source_rate'],
        'sourceSymbol': json['source_symbol'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
    };
}

export function CommonREOActivityV2ToJSON(json: any): CommonREOActivityV2 {
    return CommonREOActivityV2ToJSONTyped(json, false);
}

export function CommonREOActivityV2ToJSONTyped(value?: CommonREOActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cash_payout': value['cashPayout'],
        'cash_rate': value['cashRate'],
        'cusip': value['cusip'],
        'effective_date': value['effectiveDate'] == null ? undefined : ((value['effectiveDate']).toISOString().substring(0,10)),
        'isin': value['isin'],
        'new_rate': value['newRate'],
        'payable_date': ((value['payableDate']).toISOString().substring(0,10)),
        'qty': value['qty'],
        'removed_qty': value['removedQty'],
        'source_cusip': value['sourceCusip'],
        'source_isin': value['sourceIsin'],
        'source_qty': value['sourceQty'],
        'source_rate': value['sourceRate'],
        'source_symbol': value['sourceSymbol'],
        'symbol': value['symbol'],
    };
}

