/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonOPCAActivityV2
 */
export interface CommonOPCAActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof CommonOPCAActivityV2
     */
    systemDate: Date;
    /**
     * The unique identifier for this corporate action
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    caId?: string;
    /**
     * The position_date for this corporate action
     * @type {Date}
     * @memberof CommonOPCAActivityV2
     */
    positionDate: Date;
    /**
     * The reorg identifier, if present in the source corporate action definition
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    reorgId?: string;
    /**
     * The new contract symbol
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    newContractSymbol: string;
    /**
     * used when the old contract's quantity is not equal to the new contract's quantity. Mutually exclusive with 'qty'.
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    newQty?: string;
    /**
     * The old contract symbol
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    oldContractSymbol: string;
    /**
     * used when the old contract's quantity is not equal to the new contract's quantity. Mutually exclusive with 'qty'.
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    oldQty?: string;
    /**
     * used when the old contract's quantity is equal to the new contract's quantity. Mutually exclusive with 'old_qty' and 'new_qty'
     * @type {string}
     * @memberof CommonOPCAActivityV2
     */
    qty?: string;
}

/**
 * Check if a given object implements the CommonOPCAActivityV2 interface.
 */
export function instanceOfCommonOPCAActivityV2(value: object): value is CommonOPCAActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('positionDate' in value) || value['positionDate'] === undefined) return false;
    if (!('newContractSymbol' in value) || value['newContractSymbol'] === undefined) return false;
    if (!('oldContractSymbol' in value) || value['oldContractSymbol'] === undefined) return false;
    return true;
}

export function CommonOPCAActivityV2FromJSON(json: any): CommonOPCAActivityV2 {
    return CommonOPCAActivityV2FromJSONTyped(json, false);
}

export function CommonOPCAActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonOPCAActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'caId': json['ca_id'] == null ? undefined : json['ca_id'],
        'positionDate': (new Date(json['position_date'])),
        'reorgId': json['reorg_id'] == null ? undefined : json['reorg_id'],
        'newContractSymbol': json['new_contract_symbol'],
        'newQty': json['new_qty'] == null ? undefined : json['new_qty'],
        'oldContractSymbol': json['old_contract_symbol'],
        'oldQty': json['old_qty'] == null ? undefined : json['old_qty'],
        'qty': json['qty'] == null ? undefined : json['qty'],
    };
}

export function CommonOPCAActivityV2ToJSON(json: any): CommonOPCAActivityV2 {
    return CommonOPCAActivityV2ToJSONTyped(json, false);
}

export function CommonOPCAActivityV2ToJSONTyped(value?: CommonOPCAActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'ca_id': value['caId'],
        'position_date': ((value['positionDate']).toISOString().substring(0,10)),
        'reorg_id': value['reorgId'],
        'new_contract_symbol': value['newContractSymbol'],
        'new_qty': value['newQty'],
        'old_contract_symbol': value['oldContractSymbol'],
        'old_qty': value['oldQty'],
        'qty': value['qty'],
    };
}

