/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonOptionsActivityV2
 */
export interface CommonOptionsActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof CommonOptionsActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof CommonOptionsActivityV2
     */
    systemDate: Date;
    /**
     * The contract symbol of the security involved with the activity
     * @type {string}
     * @memberof CommonOptionsActivityV2
     */
    contractSymbol?: string;
    /**
     * The CUSIP of the security involved with the activity
     * @type {string}
     * @memberof CommonOptionsActivityV2
     */
    cusip?: string;
    /**
     * The symbol of the security involved with the activity
     * @type {string}
     * @memberof CommonOptionsActivityV2
     */
    symbol?: string;
}

/**
 * Check if a given object implements the CommonOptionsActivityV2 interface.
 */
export function instanceOfCommonOptionsActivityV2(value: object): value is CommonOptionsActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    return true;
}

export function CommonOptionsActivityV2FromJSON(json: any): CommonOptionsActivityV2 {
    return CommonOptionsActivityV2FromJSONTyped(json, false);
}

export function CommonOptionsActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonOptionsActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'contractSymbol': json['contract_symbol'] == null ? undefined : json['contract_symbol'],
        'cusip': json['cusip'] == null ? undefined : json['cusip'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
    };
}

export function CommonOptionsActivityV2ToJSON(json: any): CommonOptionsActivityV2 {
    return CommonOptionsActivityV2ToJSONTyped(json, false);
}

export function CommonOptionsActivityV2ToJSONTyped(value?: CommonOptionsActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'contract_symbol': value['contractSymbol'],
        'cusip': value['cusip'],
        'symbol': value['symbol'],
    };
}

