/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Takes in string/number values for stop_price and limit_price
 * @export
 * @interface CreateOrderRequestStopLoss
 */
export interface CreateOrderRequestStopLoss {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestStopLoss
     */
    limitPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestStopLoss
     */
    stopPrice?: string;
}

/**
 * Check if a given object implements the CreateOrderRequestStopLoss interface.
 */
export function instanceOfCreateOrderRequestStopLoss(value: object): value is CreateOrderRequestStopLoss {
    return true;
}

export function CreateOrderRequestStopLossFromJSON(json: any): CreateOrderRequestStopLoss {
    return CreateOrderRequestStopLossFromJSONTyped(json, false);
}

export function CreateOrderRequestStopLossFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequestStopLoss {
    if (json == null) {
        return json;
    }
    return {
        
        'limitPrice': json['limit_price'] == null ? undefined : json['limit_price'],
        'stopPrice': json['stop_price'] == null ? undefined : json['stop_price'],
    };
}

export function CreateOrderRequestStopLossToJSON(json: any): CreateOrderRequestStopLoss {
    return CreateOrderRequestStopLossToJSONTyped(json, false);
}

export function CreateOrderRequestStopLossToJSONTyped(value?: CreateOrderRequestStopLoss | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit_price': value['limitPrice'],
        'stop_price': value['stopPrice'],
    };
}

