/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCryptoTransferRequest
 */
export interface CreateCryptoTransferRequest {
    /**
     * The destination wallet address
     * @type {string}
     * @memberof CreateCryptoTransferRequest
     */
    address: string;
    /**
     * The amount, denoted in the specified asset, to be withdrawn from the user's wallet
     * @type {string}
     * @memberof CreateCryptoTransferRequest
     */
    amount: string;
    /**
     * The crypto asset symbol, e.g. BTC, ETH, USDT.
     * @type {string}
     * @memberof CreateCryptoTransferRequest
     */
    asset: string;
    /**
     * Optional chain identifier. The blockchain network used for the withdrawal.
     * @type {string}
     * @memberof CreateCryptoTransferRequest
     */
    chain?: CreateCryptoTransferRequestChainEnum;
}


/**
 * @export
 */
export const CreateCryptoTransferRequestChainEnum = {
    Sol: 'SOL',
    Eth: 'ETH',
    Btc: 'BTC',
    Xrp: 'XRP',
    Arb: 'ARB'
} as const;
export type CreateCryptoTransferRequestChainEnum = typeof CreateCryptoTransferRequestChainEnum[keyof typeof CreateCryptoTransferRequestChainEnum];


/**
 * Check if a given object implements the CreateCryptoTransferRequest interface.
 */
export function instanceOfCreateCryptoTransferRequest(value: object): value is CreateCryptoTransferRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('asset' in value) || value['asset'] === undefined) return false;
    return true;
}

export function CreateCryptoTransferRequestFromJSON(json: any): CreateCryptoTransferRequest {
    return CreateCryptoTransferRequestFromJSONTyped(json, false);
}

export function CreateCryptoTransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCryptoTransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'amount': json['amount'],
        'asset': json['asset'],
        'chain': json['chain'] == null ? undefined : json['chain'],
    };
}

export function CreateCryptoTransferRequestToJSON(json: any): CreateCryptoTransferRequest {
    return CreateCryptoTransferRequestToJSONTyped(json, false);
}

export function CreateCryptoTransferRequestToJSONTyped(value?: CreateCryptoTransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'amount': value['amount'],
        'asset': value['asset'],
        'chain': value['chain'],
    };
}

