/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedInstructions } from './AdvancedInstructions';
import {
    AdvancedInstructionsFromJSON,
    AdvancedInstructionsFromJSONTyped,
    AdvancedInstructionsToJSON,
    AdvancedInstructionsToJSONTyped,
} from './AdvancedInstructions';
import type { MLegOrderLeg } from './MLegOrderLeg';
import {
    MLegOrderLegFromJSON,
    MLegOrderLegFromJSONTyped,
    MLegOrderLegToJSON,
    MLegOrderLegToJSONTyped,
} from './MLegOrderLeg';
import type { OrderClass } from './OrderClass';
import {
    OrderClassFromJSON,
    OrderClassFromJSONTyped,
    OrderClassToJSON,
    OrderClassToJSONTyped,
} from './OrderClass';
import type { OrderType } from './OrderType';
import {
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
    OrderTypeToJSONTyped,
} from './OrderType';
import type { CreateOrderRequestTakeProfit } from './CreateOrderRequestTakeProfit';
import {
    CreateOrderRequestTakeProfitFromJSON,
    CreateOrderRequestTakeProfitFromJSONTyped,
    CreateOrderRequestTakeProfitToJSON,
    CreateOrderRequestTakeProfitToJSONTyped,
} from './CreateOrderRequestTakeProfit';
import type { TimeInForce } from './TimeInForce';
import {
    TimeInForceFromJSON,
    TimeInForceFromJSONTyped,
    TimeInForceToJSON,
    TimeInForceToJSONTyped,
} from './TimeInForce';
import type { CreateOrderRequestStopLoss } from './CreateOrderRequestStopLoss';
import {
    CreateOrderRequestStopLossFromJSON,
    CreateOrderRequestStopLossFromJSONTyped,
    CreateOrderRequestStopLossToJSON,
    CreateOrderRequestStopLossToJSONTyped,
} from './CreateOrderRequestStopLoss';
import type { PositionIntent } from './PositionIntent';
import {
    PositionIntentFromJSON,
    PositionIntentFromJSONTyped,
    PositionIntentToJSON,
    PositionIntentToJSONTyped,
} from './PositionIntent';
import type { OrderSide } from './OrderSide';
import {
    OrderSideFromJSON,
    OrderSideFromJSONTyped,
    OrderSideToJSON,
    OrderSideToJSONTyped,
} from './OrderSide';

/**
 * Represents a request to create an order.
 * @export
 * @interface CreateOrderRequest
 */
export interface CreateOrderRequest {
    /**
     * 
     * @type {AdvancedInstructions}
     * @memberof CreateOrderRequest
     */
    advancedInstructions?: AdvancedInstructions;
    /**
     * A unique identifier for the order. Automatically generated if not sent. (<= 128 characters)
     * @type {string}
     * @memberof CreateOrderRequest
     */
    clientOrderId?: string;
    /**
     * (default) false. If true, order will be eligible for execution in the pre-market, after-hours, and overnight sessions. Only works with type `limit` and time_in_force set to either `day` or `gtc`
     * @type {boolean}
     * @memberof CreateOrderRequest
     */
    extendedHours?: boolean;
    /**
     * list of order legs (<= 4)
     * @type {Array<MLegOrderLeg>}
     * @memberof CreateOrderRequest
     */
    legs?: Array<MLegOrderLeg>;
    /**
     * Required if type is `limit` or `stop_limit`.
     * In case of `mleg`, the limit_price parameter is expressed with the following notation:
     * - A positive value indicates a debit, representing a cost or payment to be made.
     * - A negative value signifies a credit, reflecting an amount to be received.
     * @type {string}
     * @memberof CreateOrderRequest
     */
    limitPrice?: string;
    /**
     * dollar amount to trade. Cannot work with `qty`. Can only work for market order types and day for time in force.
     * @type {string}
     * @memberof CreateOrderRequest
     */
    notional?: string;
    /**
     * 
     * @type {OrderClass}
     * @memberof CreateOrderRequest
     */
    orderClass?: OrderClass;
    /**
     * 
     * @type {PositionIntent}
     * @memberof CreateOrderRequest
     */
    positionIntent?: PositionIntent;
    /**
     * number of shares to trade. Can be fractionable for only market and day order types. Required for `mleg` order class, represents the number of units to trade of this strategy.
     * @type {string}
     * @memberof CreateOrderRequest
     */
    qty?: string;
    /**
     * 
     * @type {OrderSide}
     * @memberof CreateOrderRequest
     */
    side?: OrderSide;
    /**
     * 
     * @type {CreateOrderRequestStopLoss}
     * @memberof CreateOrderRequest
     */
    stopLoss?: CreateOrderRequestStopLoss;
    /**
     * required if type is `stop` or `stop_limit`
     * @type {string}
     * @memberof CreateOrderRequest
     */
    stopPrice?: string;
    /**
     * symbol, asset ID, or currency pair to identify the asset to trade, required for all order classes except for `mleg`.
     * @type {string}
     * @memberof CreateOrderRequest
     */
    symbol?: string;
    /**
     * 
     * @type {CreateOrderRequestTakeProfit}
     * @memberof CreateOrderRequest
     */
    takeProfit?: CreateOrderRequestTakeProfit;
    /**
     * 
     * @type {TimeInForce}
     * @memberof CreateOrderRequest
     */
    timeInForce: TimeInForce;
    /**
     * this or `trail_price` is required if type is `trailing_stop`
     * @type {string}
     * @memberof CreateOrderRequest
     */
    trailPercent?: string;
    /**
     * this or `trail_percent` is required if type is `trailing_stop`
     * @type {string}
     * @memberof CreateOrderRequest
     */
    trailPrice?: string;
    /**
     * 
     * @type {OrderType}
     * @memberof CreateOrderRequest
     */
    type: OrderType;
}



/**
 * Check if a given object implements the CreateOrderRequest interface.
 */
export function instanceOfCreateOrderRequest(value: object): value is CreateOrderRequest {
    if (!('timeInForce' in value) || value['timeInForce'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateOrderRequestFromJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestFromJSONTyped(json, false);
}

export function CreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advancedInstructions': json['advanced_instructions'] == null ? undefined : AdvancedInstructionsFromJSON(json['advanced_instructions']),
        'clientOrderId': json['client_order_id'] == null ? undefined : json['client_order_id'],
        'extendedHours': json['extended_hours'] == null ? undefined : json['extended_hours'],
        'legs': json['legs'] == null ? undefined : ((json['legs'] as Array<any>).map(MLegOrderLegFromJSON)),
        'limitPrice': json['limit_price'] == null ? undefined : json['limit_price'],
        'notional': json['notional'] == null ? undefined : json['notional'],
        'orderClass': json['order_class'] == null ? undefined : OrderClassFromJSON(json['order_class']),
        'positionIntent': json['position_intent'] == null ? undefined : PositionIntentFromJSON(json['position_intent']),
        'qty': json['qty'] == null ? undefined : json['qty'],
        'side': json['side'] == null ? undefined : OrderSideFromJSON(json['side']),
        'stopLoss': json['stop_loss'] == null ? undefined : CreateOrderRequestStopLossFromJSON(json['stop_loss']),
        'stopPrice': json['stop_price'] == null ? undefined : json['stop_price'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'takeProfit': json['take_profit'] == null ? undefined : CreateOrderRequestTakeProfitFromJSON(json['take_profit']),
        'timeInForce': TimeInForceFromJSON(json['time_in_force']),
        'trailPercent': json['trail_percent'] == null ? undefined : json['trail_percent'],
        'trailPrice': json['trail_price'] == null ? undefined : json['trail_price'],
        'type': OrderTypeFromJSON(json['type']),
    };
}

export function CreateOrderRequestToJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestToJSONTyped(json, false);
}

export function CreateOrderRequestToJSONTyped(value?: CreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advanced_instructions': AdvancedInstructionsToJSON(value['advancedInstructions']),
        'client_order_id': value['clientOrderId'],
        'extended_hours': value['extendedHours'],
        'legs': value['legs'] == null ? undefined : ((value['legs'] as Array<any>).map(MLegOrderLegToJSON)),
        'limit_price': value['limitPrice'],
        'notional': value['notional'],
        'order_class': OrderClassToJSON(value['orderClass']),
        'position_intent': PositionIntentToJSON(value['positionIntent']),
        'qty': value['qty'],
        'side': OrderSideToJSON(value['side']),
        'stop_loss': CreateOrderRequestStopLossToJSON(value['stopLoss']),
        'stop_price': value['stopPrice'],
        'symbol': value['symbol'],
        'take_profit': CreateOrderRequestTakeProfitToJSON(value['takeProfit']),
        'time_in_force': TimeInForceToJSON(value['timeInForce']),
        'trail_percent': value['trailPercent'],
        'trail_price': value['trailPrice'],
        'type': OrderTypeToJSON(value['type']),
    };
}

