/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoWallet
 */
export interface CryptoWallet {
    /**
     * 
     * @type {string}
     * @memberof CryptoWallet
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoWallet
     */
    chain?: string;
    /**
     * Timestamp (RFC3339) of account creation.
     * @type {Date}
     * @memberof CryptoWallet
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CryptoWallet interface.
 */
export function instanceOfCryptoWallet(value: object): value is CryptoWallet {
    return true;
}

export function CryptoWalletFromJSON(json: any): CryptoWallet {
    return CryptoWalletFromJSONTyped(json, false);
}

export function CryptoWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoWallet {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'chain': json['chain'] == null ? undefined : json['chain'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function CryptoWalletToJSON(json: any): CryptoWallet {
    return CryptoWalletToJSONTyped(json, false);
}

export function CryptoWalletToJSONTyped(value?: CryptoWallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

