/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The day count convention used to calculate accrued interest.
 * 
 * - `A/360`: calculates the daily interest using a 360-day year and then multiplies that by the actual number of days in each time period.
 * - `A/365`: calculates the daily interest using a 365-day year and then multiplies that by the actual number of days in each time period.
 * - `30/360`: calculates the daily interest using a 360-day year and then multiplies that by 30 (standardized month).
 * - `30/365`: calculates the daily interest using a 365-day year and then multiplies that by 30 (standardized month).
 * - `A/A`: calculates the daily interest using the actual number of days in the year and then multiplies that by the actual number of days in each time period.
 * - `30E/360`: number of days equals to the actual number of days (for February). If the start date or the end date of the period is the 31st of a month, that date is set to the 30th. The number of days in a year is 360.
 * - `B/252`: calculates the daily interest using a 252-business-day year and then multiplies that by the actual number of days in each time period.
 * - `A/364`: calculates the daily interest using a 364-day year and then multiplies that by the actual number of days in each time period.
 * 
 * @export
 */
export const DayCount = {
    A360: 'A/360',
    A365: 'A/365',
    _30360: '30/360',
    _30365: '30/365',
    AA: 'A/A',
    _30E360: '30E/360',
    B252: 'B/252',
    A364: 'A/364'
} as const;
export type DayCount = typeof DayCount[keyof typeof DayCount];


export function instanceOfDayCount(value: any): boolean {
    for (const key in DayCount) {
        if (Object.prototype.hasOwnProperty.call(DayCount, key)) {
            if (DayCount[key as keyof typeof DayCount] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DayCountFromJSON(json: any): DayCount {
    return DayCountFromJSONTyped(json, false);
}

export function DayCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayCount {
    return json as DayCount;
}

export function DayCountToJSON(value?: DayCount | null): any {
    return value as any;
}

export function DayCountToJSONTyped(value: any, ignoreDiscriminator: boolean): DayCount {
    return value as DayCount;
}

