/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Substitute payment in lieu of dividend
 * @export
 * @interface DIVSPDActivityV2
 */
export interface DIVSPDActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    systemDate: Date;
    /**
     * The unique identifier for this corporate action
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    caId?: string;
    /**
     * The position_date for this corporate action
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    positionDate: Date;
    /**
     * The reorg identifier, if present in the source corporate action definition
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    reorgId?: string;
    /**
     * Total cash amount paid
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    cashPayout: string;
    /**
     * The CUSIP of the security involved with the activity
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    cusip: string;
    /**
     * When due bills stop applying for this event
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    dueBillOffDate?: Date;
    /**
     * When due bills begin to apply for this event
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    dueBillOnDate?: Date;
    /**
     * Quantity of shares entitled to receive cash in lieu
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    entitledQty: string;
    /**
     * The ex_date for this corporate action
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    exDate?: Date;
    /**
     * Indicates if related to a non-US security
     * @type {boolean}
     * @memberof DIVSPDActivityV2
     */
    foreign: boolean;
    /**
     * The payable_date for this corporate action
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    payableDate?: Date;
    /**
     * Cash payout per share
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    rate: string;
    /**
     * The record_date for this corporate action
     * @type {Date}
     * @memberof DIVSPDActivityV2
     */
    recordDate?: Date;
    /**
     * Indicates if this is a special dividend
     * @type {boolean}
     * @memberof DIVSPDActivityV2
     */
    special: boolean;
    /**
     * The symbol of the security involved with the activity
     * @type {string}
     * @memberof DIVSPDActivityV2
     */
    symbol: string;
}

/**
 * Check if a given object implements the DIVSPDActivityV2 interface.
 */
export function instanceOfDIVSPDActivityV2(value: object): value is DIVSPDActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('positionDate' in value) || value['positionDate'] === undefined) return false;
    if (!('cashPayout' in value) || value['cashPayout'] === undefined) return false;
    if (!('cusip' in value) || value['cusip'] === undefined) return false;
    if (!('entitledQty' in value) || value['entitledQty'] === undefined) return false;
    if (!('foreign' in value) || value['foreign'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('special' in value) || value['special'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function DIVSPDActivityV2FromJSON(json: any): DIVSPDActivityV2 {
    return DIVSPDActivityV2FromJSONTyped(json, false);
}

export function DIVSPDActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): DIVSPDActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'caId': json['ca_id'] == null ? undefined : json['ca_id'],
        'positionDate': (new Date(json['position_date'])),
        'reorgId': json['reorg_id'] == null ? undefined : json['reorg_id'],
        'cashPayout': json['cash_payout'],
        'cusip': json['cusip'],
        'dueBillOffDate': json['due_bill_off_date'] == null ? undefined : (new Date(json['due_bill_off_date'])),
        'dueBillOnDate': json['due_bill_on_date'] == null ? undefined : (new Date(json['due_bill_on_date'])),
        'entitledQty': json['entitled_qty'],
        'exDate': json['ex_date'] == null ? undefined : (new Date(json['ex_date'])),
        'foreign': json['foreign'],
        'payableDate': json['payable_date'] == null ? undefined : (new Date(json['payable_date'])),
        'rate': json['rate'],
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'special': json['special'],
        'symbol': json['symbol'],
    };
}

export function DIVSPDActivityV2ToJSON(json: any): DIVSPDActivityV2 {
    return DIVSPDActivityV2ToJSONTyped(json, false);
}

export function DIVSPDActivityV2ToJSONTyped(value?: DIVSPDActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'ca_id': value['caId'],
        'position_date': ((value['positionDate']).toISOString().substring(0,10)),
        'reorg_id': value['reorgId'],
        'cash_payout': value['cashPayout'],
        'cusip': value['cusip'],
        'due_bill_off_date': value['dueBillOffDate'] == null ? undefined : ((value['dueBillOffDate']).toISOString().substring(0,10)),
        'due_bill_on_date': value['dueBillOnDate'] == null ? undefined : ((value['dueBillOnDate']).toISOString().substring(0,10)),
        'entitled_qty': value['entitledQty'],
        'ex_date': value['exDate'] == null ? undefined : ((value['exDate']).toISOString().substring(0,10)),
        'foreign': value['foreign'],
        'payable_date': value['payableDate'] == null ? undefined : ((value['payableDate']).toISOString().substring(0,10)),
        'rate': value['rate'],
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'special': value['special'],
        'symbol': value['symbol'],
    };
}

