/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeOfferActivityV2
 */
export interface ExchangeOfferActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof ExchangeOfferActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof ExchangeOfferActivityV2
     */
    systemDate: Date;
    /**
     * CUSIP of the new security
     * @type {string}
     * @memberof ExchangeOfferActivityV2
     */
    newCusip?: string;
    /**
     * Symbol of the new security
     * @type {string}
     * @memberof ExchangeOfferActivityV2
     */
    newSymbol?: string;
    /**
     * CUSIP of the parent security
     * @type {string}
     * @memberof ExchangeOfferActivityV2
     */
    sourceCusip: string;
    /**
     * Symbol of the parent security
     * @type {string}
     * @memberof ExchangeOfferActivityV2
     */
    sourceSymbol: string;
}

/**
 * Check if a given object implements the ExchangeOfferActivityV2 interface.
 */
export function instanceOfExchangeOfferActivityV2(value: object): value is ExchangeOfferActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('sourceCusip' in value) || value['sourceCusip'] === undefined) return false;
    if (!('sourceSymbol' in value) || value['sourceSymbol'] === undefined) return false;
    return true;
}

export function ExchangeOfferActivityV2FromJSON(json: any): ExchangeOfferActivityV2 {
    return ExchangeOfferActivityV2FromJSONTyped(json, false);
}

export function ExchangeOfferActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeOfferActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'newCusip': json['new_cusip'] == null ? undefined : json['new_cusip'],
        'newSymbol': json['new_symbol'] == null ? undefined : json['new_symbol'],
        'sourceCusip': json['source_cusip'],
        'sourceSymbol': json['source_symbol'],
    };
}

export function ExchangeOfferActivityV2ToJSON(json: any): ExchangeOfferActivityV2 {
    return ExchangeOfferActivityV2ToJSONTyped(json, false);
}

export function ExchangeOfferActivityV2ToJSONTyped(value?: ExchangeOfferActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'new_cusip': value['newCusip'],
        'new_symbol': value['newSymbol'],
        'source_cusip': value['sourceCusip'],
        'source_symbol': value['sourceSymbol'],
    };
}

