/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the current exchanges Alpaca supports. List is currently:
 * 
 * - AMEX
 * - ARCA
 * - BATS
 * - NYSE
 * - NASDAQ
 * - NYSEARCA
 * - OTC
 * 
 * Can be empty if not applicable (e.g., for options contracts)
 * @export
 */
export const ExchangeForPosition = {
    Amex: 'AMEX',
    Arca: 'ARCA',
    Bats: 'BATS',
    Nyse: 'NYSE',
    Nasdaq: 'NASDAQ',
    Nysearca: 'NYSEARCA',
    Otc: 'OTC',
    Empty: ''
} as const;
export type ExchangeForPosition = typeof ExchangeForPosition[keyof typeof ExchangeForPosition];


export function instanceOfExchangeForPosition(value: any): boolean {
    for (const key in ExchangeForPosition) {
        if (Object.prototype.hasOwnProperty.call(ExchangeForPosition, key)) {
            if (ExchangeForPosition[key as keyof typeof ExchangeForPosition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExchangeForPositionFromJSON(json: any): ExchangeForPosition {
    return ExchangeForPositionFromJSONTyped(json, false);
}

export function ExchangeForPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeForPosition {
    return json as ExchangeForPosition;
}

export function ExchangeForPositionToJSON(value?: ExchangeForPosition | null): any {
    return value as any;
}

export function ExchangeForPositionToJSONTyped(value: any, ignoreDiscriminator: boolean): ExchangeForPosition {
    return value as ExchangeForPosition;
}

