/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Fee
 * @export
 * @interface FEEActivityV2
 */
export interface FEEActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof FEEActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof FEEActivityV2
     */
    systemDate: Date;
    /**
     * The parent transaction's ID
     * @type {string}
     * @memberof FEEActivityV2
     */
    parentId: string;
}

/**
 * Check if a given object implements the FEEActivityV2 interface.
 */
export function instanceOfFEEActivityV2(value: object): value is FEEActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    return true;
}

export function FEEActivityV2FromJSON(json: any): FEEActivityV2 {
    return FEEActivityV2FromJSONTyped(json, false);
}

export function FEEActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): FEEActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'parentId': json['parent_id'],
    };
}

export function FEEActivityV2ToJSON(json: any): FEEActivityV2 {
    return FEEActivityV2ToJSONTyped(json, false);
}

export function FEEActivityV2ToJSONTyped(value?: FEEActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'parent_id': value['parentId'],
    };
}

