/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';
import type { TradingActivities } from './TradingActivities';
import {
    TradingActivitiesFromJSON,
    TradingActivitiesFromJSONTyped,
    TradingActivitiesToJSON,
    TradingActivitiesToJSONTyped,
} from './TradingActivities';
import type { ActivityType } from './ActivityType';
import {
    ActivityTypeFromJSON,
    ActivityTypeFromJSONTyped,
    ActivityTypeToJSON,
    ActivityTypeToJSONTyped,
} from './ActivityType';
import type { NonTradeActivities } from './NonTradeActivities';
import {
    NonTradeActivitiesFromJSON,
    NonTradeActivitiesFromJSONTyped,
    NonTradeActivitiesToJSON,
    NonTradeActivitiesToJSONTyped,
} from './NonTradeActivities';

/**
 * Will be a mix of TradingActivity or NonTradeActivity objects based on what is passed in the activity_types parameter
 * @export
 * @interface GetAccountActivities200ResponseInner
 */
export interface GetAccountActivities200ResponseInner extends Record<string, unknown> {
    /**
     * 
     * @type {ActivityType}
     * @memberof GetAccountActivities200ResponseInner
     */
    activityType?: ActivityType;
    /**
     * The cumulative quantity of shares involved in the execution.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    cumQty?: string;
    /**
     * An ID for the activity, always in "::" format. Can be sent as page_token in requests to facilitate the paging of results.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    id?: string;
    /**
     * For partially_filled orders, the quantity of shares that are left to be filled.
     * 
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    leavesQty?: string;
    /**
     * The id for the order that filled.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    orderId?: string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof GetAccountActivities200ResponseInner
     */
    orderStatus?: OrderStatus;
    /**
     * The per-share price that the trade was executed at.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    price?: string;
    /**
     * For dividend activities, the number of shares that contributed to the payment. Not present for other activity types.
     * 
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    qty?: string;
    /**
     * buy or sell
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    side?: string;
    /**
     * The symbol of the security involved with the activity. Not present for all activity types.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    symbol?: string;
    /**
     * The time at which the execution occurred.
     * @type {Date}
     * @memberof GetAccountActivities200ResponseInner
     */
    transactionTime?: Date;
    /**
     * fill or partial_fill
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    type?: GetAccountActivities200ResponseInnerTypeEnum;
    /**
     * Represents a more specific classification to the `activity_type`.
     * This field is optional and may not always be populated, depending on the activity type and the available data.
     * Each `activity_type` has a set of valid `activity_sub_type` values.
     * 
     * Full mapping of `activity_type` to `activity_sub_type`:
     * 
     * - **DIV**: Dividend activity sub-types:
     *   - **CDIV**: Cash Dividend
     *   - **SDIV**: Stock Dividend
     *   - **SPD**: Substitute Payment In Lieu Of Dividend
     * 
     * - **FEE**: Fee-related activity sub-types:
     *   - **REG**: Regulatory Fee
     *   - **TAF**: Trading Activity Fee
     *   - **LCT**: Local Currency Trading Fee
     *   - **ORF**: Options Regulatory Fee
     *   - **OCC**: Options Clearing Corporation Fee
     *   - **NRC**: Non-Retail Commission Fee
     *   - **NRV**: Non-Retail Venue Fee
     *   - **COM**: Commission
     *   - **CAT**: Consolidated Audit Trail Fee
     * 
     * - **INT**: Interest-related activity sub-types:
     *   - **MGN**: Margin Interest
     *   - **CDT**: Credit Interest
     *   - **SWP**: Sweep Interest
     *   - **QII**: Qualified Interest
     * 
     * - **MA**: Merger and Acquisition activity sub-types:
     *   - **CMA**: Cash Merger
     *   - **SMA**: Stock Merger
     *   - **SCMA**: Stock & Cash Merger
     * 
     * - **NC**: Name Change activity sub types
     *   - **SNC**: Symbol Name Change
     *   - **CNC**: CUSIP Name Change
     *   - **SCNC**: Symbol & CUSIP Name Change
     * 
     * - **OPCA**: Option Corporate Action activity sub-types:
     *   - **DIV.CDIV**: Cash Dividend
     *   - **DIV.SDIV**: Stock Dividend
     *   - **MA.CMA**: Cash Merger
     *   - **MA.SMA**: Stock Merger
     *   - **MA.SCMA**: Stock & Cash Merger
     *   - **NC.CNC**: CUSIP Name Change
     *   - **NC.SNC**: Symbol Name Change
     *   - **NC.SCNC**: Symbol & CUSIP Name Change
     *   - **SPIN**: Spin-off
     *   - **SPLIT.FSPLIT**: Forward Stock Split
     *   - **SPLIT.RSPLIT**: Reverse Stock Split
     *   - **SPLIT.USPLIT**: Unit Split
     * 
     * - **REORG**: Reorganization activity sub-types:
     *   - **WRM**: Worthless Removal
     * 
     * - **SPLIT**: Stock Split activity sub-types:
     *   - **FSPLIT**: Forward Stock Split
     *   - **RSPLIT**: Reverse Stock Split
     *   - **USPLIT**: Unit Split
     * 
     * - **VOF**: Voluntary Offering activity sub-types:
     *   - **VTND**: Tender Offer
     *   - **VWRT**: Warrant Exercise
     *   - **VRGT**: Rights Offer
     *   - **VEXH**: Exchange Offer
     * 
     * - **WH**: Withholding activity sub-types:
     *   - **SWH**: State Withholding
     *   - **FWH**: Federal Withholding
     *   - **SLWH**: Sales Withholding
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    activitySubType?: string;
    /**
     * Valid only for non-trading activity types. Null for trading activites.
     * @type {Date}
     * @memberof GetAccountActivities200ResponseInner
     */
    createdAt?: Date;
    /**
     * Currency denomination of the activity (e.g. USD). Included in NTA stream events and activity responses.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    currency?: string;
    /**
     * The CUSIP of the security involved with the activity. Not present for all activity types.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    cusip?: string;
    /**
     * The date on which the activity occurred or on which the transaction associated with the activity settled.
     * @type {Date}
     * @memberof GetAccountActivities200ResponseInner
     */
    date?: Date;
    /**
     * ID used to link activities who share a sibling relationship.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    groupId?: string;
    /**
     * The net amount of money (positive or negative) associated with the activity.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    netAmount?: string;
    /**
     * For dividend activities, the average amount paid per share. Not present for other activity types.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    perShareAmount?: string;
    /**
     * The activity status.
     * @type {string}
     * @memberof GetAccountActivities200ResponseInner
     */
    status?: GetAccountActivities200ResponseInnerStatusEnum;
}


/**
 * @export
 */
export const GetAccountActivities200ResponseInnerTypeEnum = {
    Fill: 'fill',
    PartialFill: 'partial_fill'
} as const;
export type GetAccountActivities200ResponseInnerTypeEnum = typeof GetAccountActivities200ResponseInnerTypeEnum[keyof typeof GetAccountActivities200ResponseInnerTypeEnum];

/**
 * @export
 */
export const GetAccountActivities200ResponseInnerStatusEnum = {
    Executed: 'executed',
    Correct: 'correct',
    Canceled: 'canceled'
} as const;
export type GetAccountActivities200ResponseInnerStatusEnum = typeof GetAccountActivities200ResponseInnerStatusEnum[keyof typeof GetAccountActivities200ResponseInnerStatusEnum];


/**
 * Check if a given object implements the GetAccountActivities200ResponseInner interface.
 */
export function instanceOfGetAccountActivities200ResponseInner(value: object): value is GetAccountActivities200ResponseInner {
    return true;
}

export function GetAccountActivities200ResponseInnerFromJSON(json: any): GetAccountActivities200ResponseInner {
    return GetAccountActivities200ResponseInnerFromJSONTyped(json, false);
}

export function GetAccountActivities200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountActivities200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        ...json,
        
        'activityType': json['activity_type'] == null ? undefined : ActivityTypeFromJSON(json['activity_type']),
        'cumQty': json['cum_qty'] == null ? undefined : json['cum_qty'],
        'id': json['id'] == null ? undefined : json['id'],
        'leavesQty': json['leaves_qty'] == null ? undefined : json['leaves_qty'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'orderStatus': json['order_status'] == null ? undefined : OrderStatusFromJSON(json['order_status']),
        'price': json['price'] == null ? undefined : json['price'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'side': json['side'] == null ? undefined : json['side'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'transactionTime': json['transaction_time'] == null ? undefined : (new Date(json['transaction_time'])),
        'type': json['type'] == null ? undefined : json['type'],
        'activitySubType': json['activity_sub_type'] == null ? undefined : json['activity_sub_type'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'cusip': json['cusip'] == null ? undefined : json['cusip'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'netAmount': json['net_amount'] == null ? undefined : json['net_amount'],
        'perShareAmount': json['per_share_amount'] == null ? undefined : json['per_share_amount'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function GetAccountActivities200ResponseInnerToJSON(json: any): GetAccountActivities200ResponseInner {
    return GetAccountActivities200ResponseInnerToJSONTyped(json, false);
}

export function GetAccountActivities200ResponseInnerToJSONTyped(value?: GetAccountActivities200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_type': ActivityTypeToJSON(value['activityType']),
        'cum_qty': value['cumQty'],
        'id': value['id'],
        'leaves_qty': value['leavesQty'],
        'order_id': value['orderId'],
        'order_status': OrderStatusToJSON(value['orderStatus']),
        'price': value['price'],
        'qty': value['qty'],
        'side': value['side'],
        'symbol': value['symbol'],
        'transaction_time': value['transactionTime'] == null ? undefined : ((value['transactionTime']).toISOString()),
        'type': value['type'],
        'activity_sub_type': value['activitySubType'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'currency': value['currency'],
        'cusip': value['cusip'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'group_id': value['groupId'],
        'net_amount': value['netAmount'],
        'per_share_amount': value['perShareAmount'],
        'status': value['status'],
    };
}

