/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCryptoPerpTransferEstimate200Response
 */
export interface GetCryptoPerpTransferEstimate200Response {
    /**
     * 
     * @type {string}
     * @memberof GetCryptoPerpTransferEstimate200Response
     */
    fee?: string;
}

/**
 * Check if a given object implements the GetCryptoPerpTransferEstimate200Response interface.
 */
export function instanceOfGetCryptoPerpTransferEstimate200Response(value: object): value is GetCryptoPerpTransferEstimate200Response {
    return true;
}

export function GetCryptoPerpTransferEstimate200ResponseFromJSON(json: any): GetCryptoPerpTransferEstimate200Response {
    return GetCryptoPerpTransferEstimate200ResponseFromJSONTyped(json, false);
}

export function GetCryptoPerpTransferEstimate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCryptoPerpTransferEstimate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'fee': json['fee'] == null ? undefined : json['fee'],
    };
}

export function GetCryptoPerpTransferEstimate200ResponseToJSON(json: any): GetCryptoPerpTransferEstimate200Response {
    return GetCryptoPerpTransferEstimate200ResponseToJSONTyped(json, false);
}

export function GetCryptoPerpTransferEstimate200ResponseToJSONTyped(value?: GetCryptoPerpTransferEstimate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee': value['fee'],
    };
}

