/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Locates API error response. Locate-specific 400 and create locate 422 errors include a machine-readable `code`.
 * @export
 * @interface LocateError
 */
export interface LocateError {
    /**
     * Machine-readable error code. Present on locate-specific 400 and create locate 422 errors.
     * @type {string}
     * @memberof LocateError
     */
    code?: LocateErrorCodeEnum;
    /**
     * Error message.
     * @type {string}
     * @memberof LocateError
     */
    message: string;
}


/**
 * @export
 */
export const LocateErrorCodeEnum = {
    InvalidInput: 'invalid_input',
    InvalidRequestBody: 'invalid_request_body',
    InvalidLimitPrice: 'invalid_limit_price',
    InvalidSymbols: 'invalid_symbols',
    SymbolNotFound: 'symbol_not_found',
    SecurityNotFound: 'security_not_found',
    InsufficientBuyingPower: 'insufficient_buying_power',
    EasyToBorrow: 'easy_to_borrow',
    ThresholdSecurity: 'threshold_security'
} as const;
export type LocateErrorCodeEnum = typeof LocateErrorCodeEnum[keyof typeof LocateErrorCodeEnum];


/**
 * Check if a given object implements the LocateError interface.
 */
export function instanceOfLocateError(value: object): value is LocateError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LocateErrorFromJSON(json: any): LocateError {
    return LocateErrorFromJSONTyped(json, false);
}

export function LocateErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocateError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'],
    };
}

export function LocateErrorToJSON(json: any): LocateError {
    return LocateErrorToJSONTyped(json, false);
}

export function LocateErrorToJSONTyped(value?: LocateError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

