/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The market identifier (MIC, BIC, or acronym).
 * @export
 */
export const Market = {
    Bmo: 'BMO',
    Bnym: 'BNYM',
    Boats: 'BOATS',
    Ceux: 'CEUX',
    Chix: 'CHIX',
    Hkex: 'HKEX',
    Iex: 'IEX',
    Iexg: 'IEXG',
    Ise: 'ISE',
    Lse: 'LSE',
    Mta: 'MTA',
    Mtaa: 'MTAA',
    Nasdaq: 'NASDAQ',
    Nyse: 'NYSE',
    Ocea: 'OCEA',
    Opra: 'OPRA',
    Otc: 'OTC',
    Otcm: 'OTCM',
    Sifma: 'SIFMA',
    Tadawul: 'TADAWUL',
    Xams: 'XAMS',
    Xbru: 'XBRU',
    Xdub: 'XDUB',
    Xetr: 'XETR',
    Xetra: 'XETRA',
    Xhkg: 'XHKG',
    Xlis: 'XLIS',
    Xlon: 'XLON',
    Xnas: 'XNAS',
    Xnys: 'XNYS',
    Xpar: 'XPAR',
    Xsau: 'XSAU'
} as const;
export type Market = typeof Market[keyof typeof Market];


export function instanceOfMarket(value: any): boolean {
    for (const key in Market) {
        if (Object.prototype.hasOwnProperty.call(Market, key)) {
            if (Market[key as keyof typeof Market] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MarketFromJSON(json: any): Market {
    return MarketFromJSONTyped(json, false);
}

export function MarketFromJSONTyped(json: any, ignoreDiscriminator: boolean): Market {
    return json as Market;
}

export function MarketToJSON(value?: Market | null): any {
    return value as any;
}

export function MarketToJSONTyped(value: any, ignoreDiscriminator: boolean): Market {
    return value as Market;
}

