/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Options corporate action of forward-splits
 * @export
 * @interface OpcaFSPLITActivityV2
 */
export interface OpcaFSPLITActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    systemDate: Date;
    /**
     * The unique identifier for this corporate action
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    caId?: string;
    /**
     * The position_date for this corporate action
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    positionDate: Date;
    /**
     * The reorg identifier, if present in the source corporate action definition
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    reorgId?: string;
    /**
     * The new contract symbol
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    newContractSymbol: string;
    /**
     * used when the old contract's quantity is not equal to the new contract's quantity. Mutually exclusive with 'qty'.
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    newQty?: string;
    /**
     * The old contract symbol
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    oldContractSymbol: string;
    /**
     * used when the old contract's quantity is not equal to the new contract's quantity. Mutually exclusive with 'qty'.
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    oldQty?: string;
    /**
     * used when the old contract's quantity is equal to the new contract's quantity. Mutually exclusive with 'old_qty' and 'new_qty'
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    qty?: string;
    /**
     * CUSIP of the new security after the split
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    newCusip: string;
    /**
     * Ratio of new shares received
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    newRate: string;
    /**
     * CUSIP of the old security before the split
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    oldCusip: string;
    /**
     * Ratio of old shares exchanged
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    oldRate: string;
    /**
     * The payable_date for this corporate action
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    payableDate?: Date;
    /**
     * When due bills related to the split are redeemed
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    dueBillRedemptionDate?: Date;
    /**
     * The ex_date for this corporate action
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    exDate?: Date;
    /**
     * The record_date for this corporate action
     * @type {Date}
     * @memberof OpcaFSPLITActivityV2
     */
    recordDate?: Date;
    /**
     * The symbol of the security involved with the activity
     * @type {string}
     * @memberof OpcaFSPLITActivityV2
     */
    symbol: string;
}

/**
 * Check if a given object implements the OpcaFSPLITActivityV2 interface.
 */
export function instanceOfOpcaFSPLITActivityV2(value: object): value is OpcaFSPLITActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('positionDate' in value) || value['positionDate'] === undefined) return false;
    if (!('newContractSymbol' in value) || value['newContractSymbol'] === undefined) return false;
    if (!('oldContractSymbol' in value) || value['oldContractSymbol'] === undefined) return false;
    if (!('newCusip' in value) || value['newCusip'] === undefined) return false;
    if (!('newRate' in value) || value['newRate'] === undefined) return false;
    if (!('oldCusip' in value) || value['oldCusip'] === undefined) return false;
    if (!('oldRate' in value) || value['oldRate'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function OpcaFSPLITActivityV2FromJSON(json: any): OpcaFSPLITActivityV2 {
    return OpcaFSPLITActivityV2FromJSONTyped(json, false);
}

export function OpcaFSPLITActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): OpcaFSPLITActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'caId': json['ca_id'] == null ? undefined : json['ca_id'],
        'positionDate': (new Date(json['position_date'])),
        'reorgId': json['reorg_id'] == null ? undefined : json['reorg_id'],
        'newContractSymbol': json['new_contract_symbol'],
        'newQty': json['new_qty'] == null ? undefined : json['new_qty'],
        'oldContractSymbol': json['old_contract_symbol'],
        'oldQty': json['old_qty'] == null ? undefined : json['old_qty'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'newCusip': json['new_cusip'],
        'newRate': json['new_rate'],
        'oldCusip': json['old_cusip'],
        'oldRate': json['old_rate'],
        'payableDate': json['payable_date'] == null ? undefined : (new Date(json['payable_date'])),
        'dueBillRedemptionDate': json['due_bill_redemption_date'] == null ? undefined : (new Date(json['due_bill_redemption_date'])),
        'exDate': json['ex_date'] == null ? undefined : (new Date(json['ex_date'])),
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'symbol': json['symbol'],
    };
}

export function OpcaFSPLITActivityV2ToJSON(json: any): OpcaFSPLITActivityV2 {
    return OpcaFSPLITActivityV2ToJSONTyped(json, false);
}

export function OpcaFSPLITActivityV2ToJSONTyped(value?: OpcaFSPLITActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'ca_id': value['caId'],
        'position_date': ((value['positionDate']).toISOString().substring(0,10)),
        'reorg_id': value['reorgId'],
        'new_contract_symbol': value['newContractSymbol'],
        'new_qty': value['newQty'],
        'old_contract_symbol': value['oldContractSymbol'],
        'old_qty': value['oldQty'],
        'qty': value['qty'],
        'new_cusip': value['newCusip'],
        'new_rate': value['newRate'],
        'old_cusip': value['oldCusip'],
        'old_rate': value['oldRate'],
        'payable_date': value['payableDate'] == null ? undefined : ((value['payableDate']).toISOString().substring(0,10)),
        'due_bill_redemption_date': value['dueBillRedemptionDate'] == null ? undefined : ((value['dueBillRedemptionDate']).toISOString().substring(0,10)),
        'ex_date': value['exDate'] == null ? undefined : ((value['exDate']).toISOString().substring(0,10)),
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'symbol': value['symbol'],
    };
}

