/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The order types supported by Alpaca vary based on the order's security type. The following provides a comprehensive breakdown of the supported order types for each category:
 *  - Equity trading: market, limit, stop, stop_limit, trailing_stop.
 *  - Options trading: market, limit.
 *  - Multileg Options trading: market, limit.
 *  - Crypto trading: market, limit, stop_limit.
 * @export
 */
export const OrderType = {
    Market: 'market',
    Limit: 'limit',
    Stop: 'stop',
    StopLimit: 'stop_limit',
    TrailingStop: 'trailing_stop'
} as const;
export type OrderType = typeof OrderType[keyof typeof OrderType];


export function instanceOfOrderType(value: any): boolean {
    for (const key in OrderType) {
        if (Object.prototype.hasOwnProperty.call(OrderType, key)) {
            if (OrderType[key as keyof typeof OrderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrderTypeFromJSON(json: any): OrderType {
    return OrderTypeFromJSONTyped(json, false);
}

export function OrderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderType {
    return json as OrderType;
}

export function OrderTypeToJSON(value?: OrderType | null): any {
    return value as any;
}

export function OrderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OrderType {
    return value as OrderType;
}

