/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedInstructions } from './AdvancedInstructions';
import {
    AdvancedInstructionsFromJSON,
    AdvancedInstructionsFromJSONTyped,
    AdvancedInstructionsToJSON,
    AdvancedInstructionsToJSONTyped,
} from './AdvancedInstructions';
import type { TimeInForce } from './TimeInForce';
import {
    TimeInForceFromJSON,
    TimeInForceFromJSONTyped,
    TimeInForceToJSON,
    TimeInForceToJSONTyped,
} from './TimeInForce';

/**
 * Represents a request to patch an order.
 * 
 * Note: `qty` and `notional` are mutually exclusive on a single replace request. `notional` is only valid for IPO indications of interest (`asset_class: "ipo"`); non-IPO notional orders cannot be replaced at all.
 * @export
 * @interface PatchOrderRequest
 */
export interface PatchOrderRequest {
    /**
     * 
     * @type {AdvancedInstructions}
     * @memberof PatchOrderRequest
     */
    advancedInstructions?: AdvancedInstructions;
    /**
     * A unique identifier for the new order. Automatically generated if not sent. (<= 128 characters)
     * @type {string}
     * @memberof PatchOrderRequest
     */
    clientOrderId?: string;
    /**
     * Required if original order's `type` field was `limit` or `stop_limit`.
     * In case of `mleg`, the limit_price parameter is expressed with the following notation:
     * - A positive value indicates a debit, representing a cost or payment to be made.
     * - A negative value signifies a credit, reflecting an amount to be received.
     * @type {string}
     * @memberof PatchOrderRequest
     */
    limitPrice?: string;
    /**
     * New notional (dollar amount) for the order. Only valid for IPO indications of interest (`asset_class: "ipo"`); will be rejected for any other asset class.
     * Mutually exclusive with `qty` on the same replace request.
     * @type {string}
     * @memberof PatchOrderRequest
     */
    notional?: string;
    /**
     * number of shares to trade.
     * 
     * You can only patch full shares for now.
     * 
     * Qty of equity fractional orders are not allowed to change. Non-IPO notional orders cannot be replaced at all - no fields (qty, limit_price, stop_price, etc.) can be modified; cancel and resubmit instead.
     * @type {string}
     * @memberof PatchOrderRequest
     */
    qty?: string;
    /**
     * required if original order type is limit or stop_limit
     * @type {string}
     * @memberof PatchOrderRequest
     */
    stopPrice?: string;
    /**
     * 
     * @type {TimeInForce}
     * @memberof PatchOrderRequest
     */
    timeInForce?: TimeInForce;
    /**
     * the new value of the trail_price or trail_percent value (works only for type="trailing_stop")
     * @type {string}
     * @memberof PatchOrderRequest
     */
    trail?: string;
}



/**
 * Check if a given object implements the PatchOrderRequest interface.
 */
export function instanceOfPatchOrderRequest(value: object): value is PatchOrderRequest {
    return true;
}

export function PatchOrderRequestFromJSON(json: any): PatchOrderRequest {
    return PatchOrderRequestFromJSONTyped(json, false);
}

export function PatchOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advancedInstructions': json['advanced_instructions'] == null ? undefined : AdvancedInstructionsFromJSON(json['advanced_instructions']),
        'clientOrderId': json['client_order_id'] == null ? undefined : json['client_order_id'],
        'limitPrice': json['limit_price'] == null ? undefined : json['limit_price'],
        'notional': json['notional'] == null ? undefined : json['notional'],
        'qty': json['qty'] == null ? undefined : json['qty'],
        'stopPrice': json['stop_price'] == null ? undefined : json['stop_price'],
        'timeInForce': json['time_in_force'] == null ? undefined : TimeInForceFromJSON(json['time_in_force']),
        'trail': json['trail'] == null ? undefined : json['trail'],
    };
}

export function PatchOrderRequestToJSON(json: any): PatchOrderRequest {
    return PatchOrderRequestToJSONTyped(json, false);
}

export function PatchOrderRequestToJSONTyped(value?: PatchOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advanced_instructions': AdvancedInstructionsToJSON(value['advancedInstructions']),
        'client_order_id': value['clientOrderId'],
        'limit_price': value['limitPrice'],
        'notional': value['notional'],
        'qty': value['qty'],
        'stop_price': value['stopPrice'],
        'time_in_force': TimeInForceToJSON(value['timeInForce']),
        'trail': value['trail'],
    };
}

