/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarDay } from './CalendarDay';
import {
    CalendarDayFromJSON,
    CalendarDayFromJSONTyped,
    CalendarDayToJSON,
    CalendarDayToJSONTyped,
} from './CalendarDay';
import type { PublicMarket } from './PublicMarket';
import {
    PublicMarketFromJSON,
    PublicMarketFromJSONTyped,
    PublicMarketToJSON,
    PublicMarketToJSONTyped,
} from './PublicMarket';

/**
 * Calendar response.
 * @export
 * @interface PublicCalendarResp
 */
export interface PublicCalendarResp {
    /**
     * The market calendar.
     * @type {Array<CalendarDay>}
     * @memberof PublicCalendarResp
     */
    calendar: Array<CalendarDay>;
    /**
     * 
     * @type {PublicMarket}
     * @memberof PublicCalendarResp
     */
    market: PublicMarket;
}

/**
 * Check if a given object implements the PublicCalendarResp interface.
 */
export function instanceOfPublicCalendarResp(value: object): value is PublicCalendarResp {
    if (!('calendar' in value) || value['calendar'] === undefined) return false;
    if (!('market' in value) || value['market'] === undefined) return false;
    return true;
}

export function PublicCalendarRespFromJSON(json: any): PublicCalendarResp {
    return PublicCalendarRespFromJSONTyped(json, false);
}

export function PublicCalendarRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCalendarResp {
    if (json == null) {
        return json;
    }
    return {
        
        'calendar': (json['calendar'] == null ? [] : (json['calendar'] as Array<any>).map(CalendarDayFromJSON)),
        'market': PublicMarketFromJSON(json['market']),
    };
}

export function PublicCalendarRespToJSON(json: any): PublicCalendarResp {
    return PublicCalendarRespToJSONTyped(json, false);
}

export function PublicCalendarRespToJSONTyped(value?: PublicCalendarResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar': ((value['calendar'] as Array<any>).map(CalendarDayToJSON)),
        'market': PublicMarketToJSON(value['market']),
    };
}

