/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VASP } from './VASP';
import {
    VASPFromJSON,
    VASPFromJSONTyped,
    VASPToJSON,
    VASPToJSONTyped,
} from './VASP';

/**
 * Paginated VASP directory search results.
 * @export
 * @interface SearchVASPsResponse
 */
export interface SearchVASPsResponse {
    /**
     * 
     * @type {number}
     * @memberof SearchVASPsResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchVASPsResponse
     */
    pages?: number;
    /**
     * Total count of matching records.
     * @type {number}
     * @memberof SearchVASPsResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<VASP>}
     * @memberof SearchVASPsResponse
     */
    vasps?: Array<VASP>;
}

/**
 * Check if a given object implements the SearchVASPsResponse interface.
 */
export function instanceOfSearchVASPsResponse(value: object): value is SearchVASPsResponse {
    return true;
}

export function SearchVASPsResponseFromJSON(json: any): SearchVASPsResponse {
    return SearchVASPsResponseFromJSONTyped(json, false);
}

export function SearchVASPsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchVASPsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'total': json['total'] == null ? undefined : json['total'],
        'vasps': json['vasps'] == null ? undefined : ((json['vasps'] as Array<any>).map(VASPFromJSON)),
    };
}

export function SearchVASPsResponseToJSON(json: any): SearchVASPsResponse {
    return SearchVASPsResponseToJSONTyped(json, false);
}

export function SearchVASPsResponseToJSONTyped(value?: SearchVASPsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'total': value['total'],
        'vasps': value['vasps'] == null ? undefined : ((value['vasps'] as Array<any>).map(VASPToJSON)),
    };
}

