/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Spinoff
 * @export
 * @interface SpinoffActivityV2
 */
export interface SpinoffActivityV2 {
    /**
     * Optional group ID which can help grouping together related activities
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    groupId?: string;
    /**
     * The date when the activity was booked
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    systemDate: Date;
    /**
     * The unique identifier for this corporate action
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    caId?: string;
    /**
     * The position_date for this corporate action
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    positionDate: Date;
    /**
     * The reorg identifier, if present in the source corporate action definition
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    reorgId?: string;
    /**
     * When due bills related to the spinoff are redeemed
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    dueBillRedemptionDate?: Date;
    /**
     * The ex_date for this corporate action
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    exDate?: Date;
    /**
     * CUSIP of the new security
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    newCusip: string;
    /**
     * Market price of new shares after the spinoff
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    newPrice: string;
    /**
     * Ratio of new shares received
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    newRate: string;
    /**
     * Symbol of the new security
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    newSymbol: string;
    /**
     * The payable_date for this corporate action
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    payableDate?: Date;
    /**
     * The record_date for this corporate action
     * @type {Date}
     * @memberof SpinoffActivityV2
     */
    recordDate?: Date;
    /**
     * CUSIP of the parent security
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    sourceCusip: string;
    /**
     * Market price of parent shares before the spinoff
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    sourcePrice: string;
    /**
     * Ratio of parent shares
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    sourceRate: string;
    /**
     * Symbol of the parent security
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    sourceSymbol: string;
    /**
     * The new quantity
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    newQty: string;
    /**
     * The source quantity
     * @type {string}
     * @memberof SpinoffActivityV2
     */
    sourceQty: string;
}

/**
 * Check if a given object implements the SpinoffActivityV2 interface.
 */
export function instanceOfSpinoffActivityV2(value: object): value is SpinoffActivityV2 {
    if (!('systemDate' in value) || value['systemDate'] === undefined) return false;
    if (!('positionDate' in value) || value['positionDate'] === undefined) return false;
    if (!('newCusip' in value) || value['newCusip'] === undefined) return false;
    if (!('newPrice' in value) || value['newPrice'] === undefined) return false;
    if (!('newRate' in value) || value['newRate'] === undefined) return false;
    if (!('newSymbol' in value) || value['newSymbol'] === undefined) return false;
    if (!('sourceCusip' in value) || value['sourceCusip'] === undefined) return false;
    if (!('sourcePrice' in value) || value['sourcePrice'] === undefined) return false;
    if (!('sourceRate' in value) || value['sourceRate'] === undefined) return false;
    if (!('sourceSymbol' in value) || value['sourceSymbol'] === undefined) return false;
    if (!('newQty' in value) || value['newQty'] === undefined) return false;
    if (!('sourceQty' in value) || value['sourceQty'] === undefined) return false;
    return true;
}

export function SpinoffActivityV2FromJSON(json: any): SpinoffActivityV2 {
    return SpinoffActivityV2FromJSONTyped(json, false);
}

export function SpinoffActivityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SpinoffActivityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'systemDate': (new Date(json['system_date'])),
        'caId': json['ca_id'] == null ? undefined : json['ca_id'],
        'positionDate': (new Date(json['position_date'])),
        'reorgId': json['reorg_id'] == null ? undefined : json['reorg_id'],
        'dueBillRedemptionDate': json['due_bill_redemption_date'] == null ? undefined : (new Date(json['due_bill_redemption_date'])),
        'exDate': json['ex_date'] == null ? undefined : (new Date(json['ex_date'])),
        'newCusip': json['new_cusip'],
        'newPrice': json['new_price'],
        'newRate': json['new_rate'],
        'newSymbol': json['new_symbol'],
        'payableDate': json['payable_date'] == null ? undefined : (new Date(json['payable_date'])),
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'sourceCusip': json['source_cusip'],
        'sourcePrice': json['source_price'],
        'sourceRate': json['source_rate'],
        'sourceSymbol': json['source_symbol'],
        'newQty': json['new_qty'],
        'sourceQty': json['source_qty'],
    };
}

export function SpinoffActivityV2ToJSON(json: any): SpinoffActivityV2 {
    return SpinoffActivityV2ToJSONTyped(json, false);
}

export function SpinoffActivityV2ToJSONTyped(value?: SpinoffActivityV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
        'system_date': ((value['systemDate']).toISOString().substring(0,10)),
        'ca_id': value['caId'],
        'position_date': ((value['positionDate']).toISOString().substring(0,10)),
        'reorg_id': value['reorgId'],
        'due_bill_redemption_date': value['dueBillRedemptionDate'] == null ? undefined : ((value['dueBillRedemptionDate']).toISOString().substring(0,10)),
        'ex_date': value['exDate'] == null ? undefined : ((value['exDate']).toISOString().substring(0,10)),
        'new_cusip': value['newCusip'],
        'new_price': value['newPrice'],
        'new_rate': value['newRate'],
        'new_symbol': value['newSymbol'],
        'payable_date': value['payableDate'] == null ? undefined : ((value['payableDate']).toISOString().substring(0,10)),
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'source_cusip': value['sourceCusip'],
        'source_price': value['sourcePrice'],
        'source_rate': value['sourceRate'],
        'source_symbol': value['sourceSymbol'],
        'new_qty': value['newQty'],
        'source_qty': value['sourceQty'],
    };
}

