/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tokenization request type
 * @export
 */
export const TokenizationRequestType = {
    Mint: 'mint',
    Redeem: 'redeem'
} as const;
export type TokenizationRequestType = typeof TokenizationRequestType[keyof typeof TokenizationRequestType];


export function instanceOfTokenizationRequestType(value: any): boolean {
    for (const key in TokenizationRequestType) {
        if (Object.prototype.hasOwnProperty.call(TokenizationRequestType, key)) {
            if (TokenizationRequestType[key as keyof typeof TokenizationRequestType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenizationRequestTypeFromJSON(json: any): TokenizationRequestType {
    return TokenizationRequestTypeFromJSONTyped(json, false);
}

export function TokenizationRequestTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenizationRequestType {
    return json as TokenizationRequestType;
}

export function TokenizationRequestTypeToJSON(value?: TokenizationRequestType | null): any {
    return value as any;
}

export function TokenizationRequestTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TokenizationRequestType {
    return value as TokenizationRequestType;
}

