/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransferDirection = {
    Incoming: 'INCOMING',
    Outgoing: 'OUTGOING'
} as const;
export type TransferDirection = typeof TransferDirection[keyof typeof TransferDirection];


export function instanceOfTransferDirection(value: any): boolean {
    for (const key in TransferDirection) {
        if (Object.prototype.hasOwnProperty.call(TransferDirection, key)) {
            if (TransferDirection[key as keyof typeof TransferDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransferDirectionFromJSON(json: any): TransferDirection {
    return TransferDirectionFromJSONTyped(json, false);
}

export function TransferDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferDirection {
    return json as TransferDirection;
}

export function TransferDirectionToJSON(value?: TransferDirection | null): any {
    return value as any;
}

export function TransferDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): TransferDirection {
    return value as TransferDirection;
}

