/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TravelRuleManualEntry } from './TravelRuleManualEntry';
import {
    TravelRuleManualEntryFromJSON,
    TravelRuleManualEntryFromJSONTyped,
    TravelRuleManualEntryToJSON,
    TravelRuleManualEntryToJSONTyped,
} from './TravelRuleManualEntry';

/**
 * Travel rule information pertaining to the wallet being whitelisted. Identify the destination by providing beneficiary_vasp_id, setting beneficiary_is_self_hosted to true, or providing beneficiary_manual_entry. Either beneficiary_entity_name (for legal entities) or beneficiary_given_name and beneficiary_family_name (for natural persons) must be provided.
 * @export
 * @interface TravelRuleInfo
 */
export interface TravelRuleInfoFields {
    /**
     * ISO 3166-1 country code for the beneficiary's country of residence.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryCountryOfResidence?: string;
    /**
     * The beneficiary's legal entity name (required for legal entities)
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryEntityName?: string;
    /**
     * The beneficiary's last name (required for natural persons)
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryFamilyName?: string;
    /**
     * Building number in the beneficiary's geographic address.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGeographicAddressBuildingNumber?: string;
    /**
     * ISO 3166-1 alpha-2 or alpha-3 country code in the beneficiary's geographic address.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGeographicAddressCountry?: string;
    /**
     * Postal code in the beneficiary's geographic address.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGeographicAddressPostCode?: string;
    /**
     * Street name in the beneficiary's geographic address.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGeographicAddressStreetName?: string;
    /**
     * Town or city in the beneficiary's geographic address.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGeographicAddressTownName?: string;
    /**
     * The beneficiary's first name (required for natural persons)
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryGivenName?: string;
    /**
     * Beneficiary is receiving funds to a self-hosted / non-custodial wallet
     * @type {boolean}
     * @memberof TravelRuleInfo
     */
    beneficiaryIsSelfHosted?: boolean;
    /**
     * 
     * @type {TravelRuleManualEntry}
     * @memberof TravelRuleInfo
     */
    beneficiaryManualEntry?: TravelRuleManualEntry;
    /**
     * The W3C Decentralized Identifier (DID) representing the beneficiary's VASP.
     * @type {string}
     * @memberof TravelRuleInfo
     */
    beneficiaryVaspId?: string;
}

export type TravelRuleInfo = TravelRuleInfoFields & (
    | { beneficiaryVaspId: string }
    | { beneficiaryIsSelfHosted: true }
    | { beneficiaryManualEntry: TravelRuleManualEntry }
) & (
    | { beneficiaryEntityName: string }
    | { beneficiaryGivenName: string; beneficiaryFamilyName: string }
);


function isNonEmptyString(value: unknown): value is string {
    return typeof value === 'string' && value.length > 0;
}

function isValidTravelRuleInfo(value: Record<string, unknown>): boolean {
    const manualEntry = value['beneficiaryManualEntry'] as
        | Record<string, unknown>
        | null
        | undefined;
    const hasDestination =
        isNonEmptyString(value['beneficiaryVaspId']) ||
        value['beneficiaryIsSelfHosted'] === true ||
        (
            manualEntry !== null &&
            typeof manualEntry === 'object' &&
            isNonEmptyString(manualEntry['vaspName']) &&
            isNonEmptyString(manualEntry['vaspWebsite'])
        );
    const hasIdentity =
        isNonEmptyString(value['beneficiaryEntityName']) ||
        (
            isNonEmptyString(value['beneficiaryGivenName']) &&
            isNonEmptyString(value['beneficiaryFamilyName'])
        );
    return hasDestination && hasIdentity;
}

/**
 * Check if a given object implements the TravelRuleInfo interface.
 */
export function instanceOfTravelRuleInfo(value: object): value is TravelRuleInfo {
    return isValidTravelRuleInfo(value as Record<string, unknown>);
}

export function TravelRuleInfoFromJSON(json: any): TravelRuleInfo {
    return TravelRuleInfoFromJSONTyped(json, false);
}

export function TravelRuleInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelRuleInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'beneficiaryCountryOfResidence': json['beneficiary_country_of_residence'] == null ? undefined : json['beneficiary_country_of_residence'],
        'beneficiaryEntityName': json['beneficiary_entity_name'] == null ? undefined : json['beneficiary_entity_name'],
        'beneficiaryFamilyName': json['beneficiary_family_name'] == null ? undefined : json['beneficiary_family_name'],
        'beneficiaryGeographicAddressBuildingNumber': json['beneficiary_geographic_address_building_number'] == null ? undefined : json['beneficiary_geographic_address_building_number'],
        'beneficiaryGeographicAddressCountry': json['beneficiary_geographic_address_country'] == null ? undefined : json['beneficiary_geographic_address_country'],
        'beneficiaryGeographicAddressPostCode': json['beneficiary_geographic_address_post_code'] == null ? undefined : json['beneficiary_geographic_address_post_code'],
        'beneficiaryGeographicAddressStreetName': json['beneficiary_geographic_address_street_name'] == null ? undefined : json['beneficiary_geographic_address_street_name'],
        'beneficiaryGeographicAddressTownName': json['beneficiary_geographic_address_town_name'] == null ? undefined : json['beneficiary_geographic_address_town_name'],
        'beneficiaryGivenName': json['beneficiary_given_name'] == null ? undefined : json['beneficiary_given_name'],
        'beneficiaryIsSelfHosted': json['beneficiary_is_self_hosted'] == null ? undefined : json['beneficiary_is_self_hosted'],
        'beneficiaryManualEntry': json['beneficiary_manual_entry'] == null ? undefined : TravelRuleManualEntryFromJSON(json['beneficiary_manual_entry']),
        'beneficiaryVaspId': json['beneficiary_vasp_id'] == null ? undefined : json['beneficiary_vasp_id'],
    };
}

export function TravelRuleInfoToJSON(json: any): TravelRuleInfo {
    return TravelRuleInfoToJSONTyped(json, false);
}

export function TravelRuleInfoToJSONTyped(value?: TravelRuleInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (!instanceOfTravelRuleInfo(value)) {
        throw new TypeError(
            'TravelRuleInfo requires a destination and either an entity name or both beneficiary names',
        );
    }

    return {
        
        'beneficiary_country_of_residence': value['beneficiaryCountryOfResidence'],
        'beneficiary_entity_name': value['beneficiaryEntityName'],
        'beneficiary_family_name': value['beneficiaryFamilyName'],
        'beneficiary_geographic_address_building_number': value['beneficiaryGeographicAddressBuildingNumber'],
        'beneficiary_geographic_address_country': value['beneficiaryGeographicAddressCountry'],
        'beneficiary_geographic_address_post_code': value['beneficiaryGeographicAddressPostCode'],
        'beneficiary_geographic_address_street_name': value['beneficiaryGeographicAddressStreetName'],
        'beneficiary_geographic_address_town_name': value['beneficiaryGeographicAddressTownName'],
        'beneficiary_given_name': value['beneficiaryGivenName'],
        'beneficiary_is_self_hosted': value['beneficiaryIsSelfHosted'],
        'beneficiary_manual_entry': TravelRuleManualEntryToJSON(value['beneficiaryManualEntry']),
        'beneficiary_vasp_id': value['beneficiaryVaspId'],
    };
}

