/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TravelRuleNextAction } from './TravelRuleNextAction';
import {
    TravelRuleNextActionFromJSON,
    TravelRuleNextActionFromJSONTyped,
    TravelRuleNextActionToJSON,
    TravelRuleNextActionToJSONTyped,
} from './TravelRuleNextAction';
import type { TravelRuleValidationErrorCode } from './TravelRuleValidationErrorCode';
import {
    TravelRuleValidationErrorCodeFromJSON,
    TravelRuleValidationErrorCodeFromJSONTyped,
    TravelRuleValidationErrorCodeToJSON,
    TravelRuleValidationErrorCodeToJSONTyped,
} from './TravelRuleValidationErrorCode';

/**
 * Travel rule validation failure and the actions required to correct it.
 * @export
 * @interface TravelRuleValidationError
 */
export interface TravelRuleValidationError {
    /**
     * 
     * @type {TravelRuleValidationErrorCode}
     * @memberof TravelRuleValidationError
     */
    errorCode: TravelRuleValidationErrorCode;
    /**
     * 
     * @type {string}
     * @memberof TravelRuleValidationError
     */
    message: string;
    /**
     * A list of actions to be taken to fulfill information requirements.
     * @type {Array<TravelRuleNextAction>}
     * @memberof TravelRuleValidationError
     */
    nextActions: Array<TravelRuleNextAction>;
}



/**
 * Check if a given object implements the TravelRuleValidationError interface.
 */
export function instanceOfTravelRuleValidationError(value: object): value is TravelRuleValidationError {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('nextActions' in value) || value['nextActions'] === undefined) return false;
    return true;
}

export function TravelRuleValidationErrorFromJSON(json: any): TravelRuleValidationError {
    return TravelRuleValidationErrorFromJSONTyped(json, false);
}

export function TravelRuleValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelRuleValidationError {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': TravelRuleValidationErrorCodeFromJSON(json['error_code']),
        'message': json['message'],
        'nextActions': (json['next_actions'] == null ? [] : (json['next_actions'] as Array<any>).map(TravelRuleNextActionFromJSON)),
    };
}

export function TravelRuleValidationErrorToJSON(json: any): TravelRuleValidationError {
    return TravelRuleValidationErrorToJSONTyped(json, false);
}

export function TravelRuleValidationErrorToJSONTyped(value?: TravelRuleValidationError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': TravelRuleValidationErrorCodeToJSON(value['errorCode']),
        'message': value['message'],
        'next_actions': ((value['nextActions'] as Array<any>).map(TravelRuleNextActionToJSON)),
    };
}

