/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TravelRuleValidationError } from './TravelRuleValidationError';
import {
    instanceOfTravelRuleValidationError,
    TravelRuleValidationErrorFromJSON,
    TravelRuleValidationErrorFromJSONTyped,
    TravelRuleValidationErrorToJSON,
} from './TravelRuleValidationError';
import type { WalletError } from './WalletError';
import {
    instanceOfWalletError,
    WalletErrorFromJSON,
    WalletErrorFromJSONTyped,
    WalletErrorToJSON,
} from './WalletError';

/**
 * @type TravelRuleErrorResponse
 * A wallet or travel rule validation error.
 * @export
 */
export type TravelRuleErrorResponse = TravelRuleValidationError | WalletError;

function containsInvalidDate(value: unknown): boolean {
    if (value instanceof Date) {
        return Number.isNaN(value.getTime());
    }
    if (Array.isArray(value)) {
        return value.some(containsInvalidDate);
    }
    if (value !== null && typeof value === 'object') {
        return Object.values(value).some(containsInvalidDate);
    }
    return false;
}

function selectMostSpecific<T>(values: T[]): T | undefined {
    let selected: T | undefined;
    let selectedScore = -1;
    for (const value of values) {
        const score =
            value !== null && typeof value === 'object'
                ? Object.values(value).filter((item) => item !== undefined).length
                : 0;
        if (score > selectedScore) {
            selected = value;
            selectedScore = score;
        }
    }
    return selected;
}

/**
 * Check if a given object implements one of the TravelRuleErrorResponse variants.
 */
export function instanceOfTravelRuleErrorResponse(value: object): value is TravelRuleErrorResponse {
    return (
        instanceOfTravelRuleValidationError(value) ||
        instanceOfWalletError(value) ||
        false
    );
}

export function TravelRuleErrorResponseFromJSON(json: any): TravelRuleErrorResponse {
    return TravelRuleErrorResponseFromJSONTyped(json, false);
}

export function TravelRuleErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelRuleErrorResponse {
    if (json == null) {
        return json;
    }
    const candidates: any[] = [];
    if (typeof json !== 'object') {
        return json;
    }
    {
        const value = TravelRuleValidationErrorFromJSONTyped(json, true);
        if (instanceOfTravelRuleValidationError(value) && !containsInvalidDate(value)) {
            candidates.push(value);
        }
    }
    {
        const value = WalletErrorFromJSONTyped(json, true);
        if (instanceOfWalletError(value) && !containsInvalidDate(value)) {
            candidates.push(value);
        }
    }

    return selectMostSpecific(candidates) ?? json;
}

export function TravelRuleErrorResponseToJSON(json: any): any {
    return TravelRuleErrorResponseToJSONTyped(json, false);
}

export function TravelRuleErrorResponseToJSONTyped(value?: TravelRuleErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    const candidates: any[] = [];
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTravelRuleValidationError(value)) {
        candidates.push(TravelRuleValidationErrorToJSON(value as TravelRuleValidationError));
    }
    if (instanceOfWalletError(value)) {
        candidates.push(WalletErrorToJSON(value as WalletError));
    }

    return selectMostSpecific(candidates) ?? value;
}

