/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TravelRuleInfo } from './TravelRuleInfo';
import {
    TravelRuleInfoFromJSON,
    TravelRuleInfoFromJSONTyped,
    TravelRuleInfoToJSON,
    TravelRuleInfoToJSONTyped,
} from './TravelRuleInfo';

/**
 * Travel rule information to associate with a whitelisted address.
 * @export
 * @interface UpdateWhitelistedAddressTravelRuleInfoRequest
 */
export interface UpdateWhitelistedAddressTravelRuleInfoRequest {
    /**
     * 
     * @type {TravelRuleInfo}
     * @memberof UpdateWhitelistedAddressTravelRuleInfoRequest
     */
    travelRuleInfo: TravelRuleInfo;
}

/**
 * Check if a given object implements the UpdateWhitelistedAddressTravelRuleInfoRequest interface.
 */
export function instanceOfUpdateWhitelistedAddressTravelRuleInfoRequest(value: object): value is UpdateWhitelistedAddressTravelRuleInfoRequest {
    if (!('travelRuleInfo' in value) || value['travelRuleInfo'] === undefined) return false;
    return true;
}

export function UpdateWhitelistedAddressTravelRuleInfoRequestFromJSON(json: any): UpdateWhitelistedAddressTravelRuleInfoRequest {
    return UpdateWhitelistedAddressTravelRuleInfoRequestFromJSONTyped(json, false);
}

export function UpdateWhitelistedAddressTravelRuleInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWhitelistedAddressTravelRuleInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'travelRuleInfo': TravelRuleInfoFromJSON(json['travel_rule_info']),
    };
}

export function UpdateWhitelistedAddressTravelRuleInfoRequestToJSON(json: any): UpdateWhitelistedAddressTravelRuleInfoRequest {
    return UpdateWhitelistedAddressTravelRuleInfoRequestToJSONTyped(json, false);
}

export function UpdateWhitelistedAddressTravelRuleInfoRequestToJSONTyped(value?: UpdateWhitelistedAddressTravelRuleInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'travel_rule_info': TravelRuleInfoToJSON(value['travelRuleInfo']),
    };
}

