/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallType } from './CallType';
import {
    CallTypeFromJSON,
    CallTypeFromJSONTyped,
    CallTypeToJSON,
    CallTypeToJSONTyped,
} from './CallType';
import type { CouponType } from './CouponType';
import {
    CouponTypeFromJSON,
    CouponTypeFromJSONTyped,
    CouponTypeToJSON,
    CouponTypeToJSONTyped,
} from './CouponType';
import type { DayCount } from './DayCount';
import {
    DayCountFromJSON,
    DayCountFromJSONTyped,
    DayCountToJSON,
    DayCountToJSONTyped,
} from './DayCount';
import type { CouponFrequency } from './CouponFrequency';
import {
    CouponFrequencyFromJSON,
    CouponFrequencyFromJSONTyped,
    CouponFrequencyToJSON,
    CouponFrequencyToJSONTyped,
} from './CouponFrequency';
import type { BondStatus } from './BondStatus';
import {
    BondStatusFromJSON,
    BondStatusFromJSONTyped,
    BondStatusToJSON,
    BondStatusToJSONTyped,
} from './BondStatus';
import type { SpOutlook } from './SpOutlook';
import {
    SpOutlookFromJSON,
    SpOutlookFromJSONTyped,
    SpOutlookToJSON,
    SpOutlookToJSONTyped,
} from './SpOutlook';

/**
 * A US corporate
 * @export
 * @interface UsCorporate
 */
export interface UsCorporate {
    /**
     * The interest that has accumulated on a bond in dollars per bond between the last interest payment and the present date that has not yet been paid to the bondholder
     * @type {number}
     * @memberof UsCorporate
     */
    accruedInterest?: number;
    /**
     * 
     * @type {BondStatus}
     * @memberof UsCorporate
     */
    bondStatus: BondStatus;
    /**
     * 
     * @type {CallType}
     * @memberof UsCorporate
     */
    callType?: CallType;
    /**
     * Whether the bond is callable, meaning the issuer has the right, but not the obligation to redeem the bond - in other words, pay out the bondholder - before its maturity date at a set price (the call price)
     * @type {boolean}
     * @memberof UsCorporate
     */
    callable: boolean;
    /**
     * The price of the last transaction of a security before the market closes for normal trading, shown as a percentage of par value
     * @type {number}
     * @memberof UsCorporate
     */
    closePrice?: number;
    /**
     * The date of the close price
     * @type {Date}
     * @memberof UsCorporate
     */
    closePriceDate?: Date;
    /**
     * Yield to maturity of the treasury after the last close
     * @type {number}
     * @memberof UsCorporate
     */
    closeYieldToMaturity?: number;
    /**
     * Yield to worst of the treasury after the last close
     * @type {number}
     * @memberof UsCorporate
     */
    closeYieldToWorst?: number;
    /**
     * A flag indicating whether the bond is convertible
     * @type {boolean}
     * @memberof UsCorporate
     */
    convertible: boolean;
    /**
     * The country where the corporate is domiciled in the 2-alpha country code format (e.g., US, CA)
     * @type {string}
     * @memberof UsCorporate
     */
    countryDomicile: string;
    /**
     * The annual interest rate paid on the bond as a percentage of par value
     * @type {number}
     * @memberof UsCorporate
     */
    coupon: number;
    /**
     * 
     * @type {CouponFrequency}
     * @memberof UsCorporate
     */
    couponFrequency: CouponFrequency;
    /**
     * 
     * @type {CouponType}
     * @memberof UsCorporate
     */
    couponType: CouponType;
    /**
     * CUSIP is a nine-character alphanumeric code that uniquely identifies the security
     * @type {string}
     * @memberof UsCorporate
     */
    cusip: string;
    /**
     * The dated date marks the beginning of the period for which interest starts accruing on the bond
     * @type {Date}
     * @memberof UsCorporate
     */
    datedDate: Date;
    /**
     * 
     * @type {DayCount}
     * @memberof UsCorporate
     */
    dayCount: DayCount;
    /**
     * Description of the corporate bond
     * @type {string}
     * @memberof UsCorporate
     */
    description: string;
    /**
     * Short description of the corporate bond
     * @type {string}
     * @memberof UsCorporate
     */
    descriptionShort: string;
    /**
     * The date of the first coupon payment
     * @type {Date}
     * @memberof UsCorporate
     */
    firstCouponDate?: Date;
    /**
     * International Securities Identification Number
     * @type {string}
     * @memberof UsCorporate
     */
    isin: string;
    /**
     * The date on which the bond was issued
     * @type {Date}
     * @memberof UsCorporate
     */
    issueDate: Date;
    /**
     * The smallest unit of the bond that can be purchased at its initial offering
     * @type {number}
     * @memberof UsCorporate
     */
    issueMinimumDenomination: number;
    /**
     * The price at which the bond was originally issued as a percentage of par value
     * @type {number}
     * @memberof UsCorporate
     */
    issuePrice: number;
    /**
     * The total size amount of the bond issue in the issuing currency
     * @type {number}
     * @memberof UsCorporate
     */
    issueSize: number;
    /**
     * The name of the issuer of the corporate bond
     * @type {string}
     * @memberof UsCorporate
     */
    issuer: string;
    /**
     * The date of the last coupon payment
     * @type {Date}
     * @memberof UsCorporate
     */
    lastCouponDate?: Date;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to buy or sell (no minimum trading sizes)
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityInstitutionalAggregate?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to buy (no minimum trading sizes)
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityInstitutionalBuy?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to sell (no minimum trading sizes)
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityInstitutionalSell?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to buy or sell with minimum trading sizes less than or equal to $1,000.00
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityMicroAggregate?: number;
    /**
     * Score (from 1-5 if the bond is priced, or null if the bond is not tradable) reflecting the historical depth of executable liquidity to buy with minimum trading sizes less than or equal to $1,000.00
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityMicroBuy?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to sell with minimum trading sizes less than or equal to $1,000.00
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityMicroSell?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to buy or sell with minimum trading sizes less than or equal to 10,000
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityRetailAggregate?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to buy with minimum trading sizes less than or equal to $10,000.00
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityRetailBuy?: number;
    /**
     * Score (from 1-5 or null if the bond is not priced/tradable) reflecting the historical depth of executable liquidity to sell with minimum trading sizes less than or equal to 10,000
     * @type {number}
     * @memberof UsCorporate
     */
    liquidityRetailSell?: number;
    /**
     * Whether the corporate is marginable
     * @type {boolean}
     * @memberof UsCorporate
     */
    marginable: boolean;
    /**
     * The date on which the bond matures
     * @type {Date}
     * @memberof UsCorporate
     */
    maturityDate?: Date;
    /**
     * The date of the next possible call on the bond.
     * @type {Date}
     * @memberof UsCorporate
     */
    nextCallDate?: Date;
    /**
     * The price at which a callable bond can be redeemed by the issuer on the next call date, as a percentage of par.
     * @type {number}
     * @memberof UsCorporate
     */
    nextCallPrice?: number;
    /**
     * The date of the next coupon payment
     * @type {Date}
     * @memberof UsCorporate
     */
    nextCouponDate?: Date;
    /**
     * The amount that the issuer of the bond will pay back to the bondholder upon maturity
     * @type {number}
     * @memberof UsCorporate
     */
    parValue: number;
    /**
     * A flag representing whether a bond is perpetual
     * @type {boolean}
     * @memberof UsCorporate
     */
    perpetual: boolean;
    /**
     * Whether the bond is puttable, meaning the bondholder has the right, but not the obligation to sell the bond back to the issuer at a set price (the put price) on specified dates before maturity
     * @type {boolean}
     * @memberof UsCorporate
     */
    puttable: boolean;
    /**
     * Indicates whether the security falls under Regulation S, a rule that provides an exemption from the registration requirements for securities offerings made outside the United States
     * @type {boolean}
     * @memberof UsCorporate
     */
    regS: boolean;
    /**
     * The date on which the corporate was reissued
     * @type {Date}
     * @memberof UsCorporate
     */
    reissueDate?: Date;
    /**
     * The price at which the corporate was reissued as a percentage of par value
     * @type {number}
     * @memberof UsCorporate
     */
    reissuePrice?: number;
    /**
     * The total size amount of the corporate reissue in the issuing currency
     * @type {number}
     * @memberof UsCorporate
     */
    reissueSize?: number;
    /**
     * The sector of the corporate bond
     * @type {string}
     * @memberof UsCorporate
     */
    sector: string;
    /**
     * The seniority of the corporate bond
     * @type {string}
     * @memberof UsCorporate
     */
    seniority: string;
    /**
     * S&P's CreditWatch highlights S&P's opinion regarding the potential direction of a short-term or long-term rating
     * @type {string}
     * @memberof UsCorporate
     */
    spCreditwatch?: string;
    /**
     * The date of the most recent Standard & Poor's CreditWatch for the bond in YYYY-MM-DD format
     * @type {Date}
     * @memberof UsCorporate
     */
    spCreditwatchDate?: Date;
    /**
     * 
     * @type {SpOutlook}
     * @memberof UsCorporate
     */
    spOutlook?: SpOutlook;
    /**
     * The date of the most recent Standard & Poor's outlook for the bond in YYYY-MM-DD format
     * @type {Date}
     * @memberof UsCorporate
     */
    spOutlookDate?: Date;
    /**
     * Standard & Poor's rating for the bond in the standard AAA - D format
     * @type {string}
     * @memberof UsCorporate
     */
    spRating?: string;
    /**
     * The date in the timezone of the issuing country of the most recent Standard & Poor's rating for the bond in YYYY-MM-DD format
     * @type {Date}
     * @memberof UsCorporate
     */
    spRatingDate?: Date;
    /**
     * The ticker symbol of the corporate
     * @type {string}
     * @memberof UsCorporate
     */
    ticker: string;
    /**
     * Whether the treasury is tradable
     * @type {boolean}
     * @memberof UsCorporate
     */
    tradable: boolean;
}



/**
 * Check if a given object implements the UsCorporate interface.
 */
export function instanceOfUsCorporate(value: object): value is UsCorporate {
    if (!('bondStatus' in value) || value['bondStatus'] === undefined) return false;
    if (!('callable' in value) || value['callable'] === undefined) return false;
    if (!('convertible' in value) || value['convertible'] === undefined) return false;
    if (!('countryDomicile' in value) || value['countryDomicile'] === undefined) return false;
    if (!('coupon' in value) || value['coupon'] === undefined) return false;
    if (!('couponFrequency' in value) || value['couponFrequency'] === undefined) return false;
    if (!('couponType' in value) || value['couponType'] === undefined) return false;
    if (!('cusip' in value) || value['cusip'] === undefined) return false;
    if (!('datedDate' in value) || value['datedDate'] === undefined) return false;
    if (!('dayCount' in value) || value['dayCount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('descriptionShort' in value) || value['descriptionShort'] === undefined) return false;
    if (!('isin' in value) || value['isin'] === undefined) return false;
    if (!('issueDate' in value) || value['issueDate'] === undefined) return false;
    if (!('issueMinimumDenomination' in value) || value['issueMinimumDenomination'] === undefined) return false;
    if (!('issuePrice' in value) || value['issuePrice'] === undefined) return false;
    if (!('issueSize' in value) || value['issueSize'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    if (!('marginable' in value) || value['marginable'] === undefined) return false;
    if (!('parValue' in value) || value['parValue'] === undefined) return false;
    if (!('perpetual' in value) || value['perpetual'] === undefined) return false;
    if (!('puttable' in value) || value['puttable'] === undefined) return false;
    if (!('regS' in value) || value['regS'] === undefined) return false;
    if (!('sector' in value) || value['sector'] === undefined) return false;
    if (!('seniority' in value) || value['seniority'] === undefined) return false;
    if (!('ticker' in value) || value['ticker'] === undefined) return false;
    if (!('tradable' in value) || value['tradable'] === undefined) return false;
    return true;
}

export function UsCorporateFromJSON(json: any): UsCorporate {
    return UsCorporateFromJSONTyped(json, false);
}

export function UsCorporateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsCorporate {
    if (json == null) {
        return json;
    }
    return {
        
        'accruedInterest': json['accrued_interest'] == null ? undefined : json['accrued_interest'],
        'bondStatus': BondStatusFromJSON(json['bond_status']),
        'callType': json['call_type'] == null ? undefined : CallTypeFromJSON(json['call_type']),
        'callable': json['callable'],
        'closePrice': json['close_price'] == null ? undefined : json['close_price'],
        'closePriceDate': json['close_price_date'] == null ? undefined : (new Date(json['close_price_date'])),
        'closeYieldToMaturity': json['close_yield_to_maturity'] == null ? undefined : json['close_yield_to_maturity'],
        'closeYieldToWorst': json['close_yield_to_worst'] == null ? undefined : json['close_yield_to_worst'],
        'convertible': json['convertible'],
        'countryDomicile': json['country_domicile'],
        'coupon': json['coupon'],
        'couponFrequency': CouponFrequencyFromJSON(json['coupon_frequency']),
        'couponType': CouponTypeFromJSON(json['coupon_type']),
        'cusip': json['cusip'],
        'datedDate': (new Date(json['dated_date'])),
        'dayCount': DayCountFromJSON(json['day_count']),
        'description': json['description'],
        'descriptionShort': json['description_short'],
        'firstCouponDate': json['first_coupon_date'] == null ? undefined : (new Date(json['first_coupon_date'])),
        'isin': json['isin'],
        'issueDate': (new Date(json['issue_date'])),
        'issueMinimumDenomination': json['issue_minimum_denomination'],
        'issuePrice': json['issue_price'],
        'issueSize': json['issue_size'],
        'issuer': json['issuer'],
        'lastCouponDate': json['last_coupon_date'] == null ? undefined : (new Date(json['last_coupon_date'])),
        'liquidityInstitutionalAggregate': json['liquidity_institutional_aggregate'] == null ? undefined : json['liquidity_institutional_aggregate'],
        'liquidityInstitutionalBuy': json['liquidity_institutional_buy'] == null ? undefined : json['liquidity_institutional_buy'],
        'liquidityInstitutionalSell': json['liquidity_institutional_sell'] == null ? undefined : json['liquidity_institutional_sell'],
        'liquidityMicroAggregate': json['liquidity_micro_aggregate'] == null ? undefined : json['liquidity_micro_aggregate'],
        'liquidityMicroBuy': json['liquidity_micro_buy'] == null ? undefined : json['liquidity_micro_buy'],
        'liquidityMicroSell': json['liquidity_micro_sell'] == null ? undefined : json['liquidity_micro_sell'],
        'liquidityRetailAggregate': json['liquidity_retail_aggregate'] == null ? undefined : json['liquidity_retail_aggregate'],
        'liquidityRetailBuy': json['liquidity_retail_buy'] == null ? undefined : json['liquidity_retail_buy'],
        'liquidityRetailSell': json['liquidity_retail_sell'] == null ? undefined : json['liquidity_retail_sell'],
        'marginable': json['marginable'],
        'maturityDate': json['maturity_date'] == null ? undefined : (new Date(json['maturity_date'])),
        'nextCallDate': json['next_call_date'] == null ? undefined : (new Date(json['next_call_date'])),
        'nextCallPrice': json['next_call_price'] == null ? undefined : json['next_call_price'],
        'nextCouponDate': json['next_coupon_date'] == null ? undefined : (new Date(json['next_coupon_date'])),
        'parValue': json['par_value'],
        'perpetual': json['perpetual'],
        'puttable': json['puttable'],
        'regS': json['reg_s'],
        'reissueDate': json['reissue_date'] == null ? undefined : (new Date(json['reissue_date'])),
        'reissuePrice': json['reissue_price'] == null ? undefined : json['reissue_price'],
        'reissueSize': json['reissue_size'] == null ? undefined : json['reissue_size'],
        'sector': json['sector'],
        'seniority': json['seniority'],
        'spCreditwatch': json['sp_creditwatch'] == null ? undefined : json['sp_creditwatch'],
        'spCreditwatchDate': json['sp_creditwatch_date'] == null ? undefined : (new Date(json['sp_creditwatch_date'])),
        'spOutlook': json['sp_outlook'] == null ? undefined : SpOutlookFromJSON(json['sp_outlook']),
        'spOutlookDate': json['sp_outlook_date'] == null ? undefined : (new Date(json['sp_outlook_date'])),
        'spRating': json['sp_rating'] == null ? undefined : json['sp_rating'],
        'spRatingDate': json['sp_rating_date'] == null ? undefined : (new Date(json['sp_rating_date'])),
        'ticker': json['ticker'],
        'tradable': json['tradable'],
    };
}

export function UsCorporateToJSON(json: any): UsCorporate {
    return UsCorporateToJSONTyped(json, false);
}

export function UsCorporateToJSONTyped(value?: UsCorporate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accrued_interest': value['accruedInterest'],
        'bond_status': BondStatusToJSON(value['bondStatus']),
        'call_type': CallTypeToJSON(value['callType']),
        'callable': value['callable'],
        'close_price': value['closePrice'],
        'close_price_date': value['closePriceDate'] == null ? undefined : ((value['closePriceDate']).toISOString().substring(0,10)),
        'close_yield_to_maturity': value['closeYieldToMaturity'],
        'close_yield_to_worst': value['closeYieldToWorst'],
        'convertible': value['convertible'],
        'country_domicile': value['countryDomicile'],
        'coupon': value['coupon'],
        'coupon_frequency': CouponFrequencyToJSON(value['couponFrequency']),
        'coupon_type': CouponTypeToJSON(value['couponType']),
        'cusip': value['cusip'],
        'dated_date': ((value['datedDate']).toISOString().substring(0,10)),
        'day_count': DayCountToJSON(value['dayCount']),
        'description': value['description'],
        'description_short': value['descriptionShort'],
        'first_coupon_date': value['firstCouponDate'] == null ? undefined : ((value['firstCouponDate']).toISOString().substring(0,10)),
        'isin': value['isin'],
        'issue_date': ((value['issueDate']).toISOString().substring(0,10)),
        'issue_minimum_denomination': value['issueMinimumDenomination'],
        'issue_price': value['issuePrice'],
        'issue_size': value['issueSize'],
        'issuer': value['issuer'],
        'last_coupon_date': value['lastCouponDate'] == null ? undefined : ((value['lastCouponDate']).toISOString().substring(0,10)),
        'liquidity_institutional_aggregate': value['liquidityInstitutionalAggregate'],
        'liquidity_institutional_buy': value['liquidityInstitutionalBuy'],
        'liquidity_institutional_sell': value['liquidityInstitutionalSell'],
        'liquidity_micro_aggregate': value['liquidityMicroAggregate'],
        'liquidity_micro_buy': value['liquidityMicroBuy'],
        'liquidity_micro_sell': value['liquidityMicroSell'],
        'liquidity_retail_aggregate': value['liquidityRetailAggregate'],
        'liquidity_retail_buy': value['liquidityRetailBuy'],
        'liquidity_retail_sell': value['liquidityRetailSell'],
        'marginable': value['marginable'],
        'maturity_date': value['maturityDate'] == null ? undefined : ((value['maturityDate']).toISOString().substring(0,10)),
        'next_call_date': value['nextCallDate'] == null ? undefined : ((value['nextCallDate']).toISOString().substring(0,10)),
        'next_call_price': value['nextCallPrice'],
        'next_coupon_date': value['nextCouponDate'] == null ? undefined : ((value['nextCouponDate']).toISOString().substring(0,10)),
        'par_value': value['parValue'],
        'perpetual': value['perpetual'],
        'puttable': value['puttable'],
        'reg_s': value['regS'],
        'reissue_date': value['reissueDate'] == null ? undefined : ((value['reissueDate']).toISOString().substring(0,10)),
        'reissue_price': value['reissuePrice'],
        'reissue_size': value['reissueSize'],
        'sector': value['sector'],
        'seniority': value['seniority'],
        'sp_creditwatch': value['spCreditwatch'],
        'sp_creditwatch_date': value['spCreditwatchDate'] == null ? undefined : ((value['spCreditwatchDate']).toISOString().substring(0,10)),
        'sp_outlook': SpOutlookToJSON(value['spOutlook']),
        'sp_outlook_date': value['spOutlookDate'] == null ? undefined : ((value['spOutlookDate']).toISOString().substring(0,10)),
        'sp_rating': value['spRating'],
        'sp_rating_date': value['spRatingDate'] == null ? undefined : ((value['spRatingDate']).toISOString().substring(0,10)),
        'ticker': value['ticker'],
        'tradable': value['tradable'],
    };
}

