/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Estimated on-chain fee breakdown for a proposed crypto withdrawal, including the total fee and the underlying network (gas) fee.
 * @export
 * @interface WalletFeeEstimateResponse
 */
export interface WalletFeeEstimateResponse {
    /**
     * 
     * @type {string}
     * @memberof WalletFeeEstimateResponse
     */
    fee?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletFeeEstimateResponse
     */
    networkFee?: string;
}

/**
 * Check if a given object implements the WalletFeeEstimateResponse interface.
 */
export function instanceOfWalletFeeEstimateResponse(value: object): value is WalletFeeEstimateResponse {
    return true;
}

export function WalletFeeEstimateResponseFromJSON(json: any): WalletFeeEstimateResponse {
    return WalletFeeEstimateResponseFromJSONTyped(json, false);
}

export function WalletFeeEstimateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletFeeEstimateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fee': json['fee'] == null ? undefined : json['fee'],
        'networkFee': json['network_fee'] == null ? undefined : json['network_fee'],
    };
}

export function WalletFeeEstimateResponseToJSON(json: any): WalletFeeEstimateResponse {
    return WalletFeeEstimateResponseToJSONTyped(json, false);
}

export function WalletFeeEstimateResponseToJSONTyped(value?: WalletFeeEstimateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee': value['fee'],
        'network_fee': value['networkFee'],
    };
}

