/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The watchlist API provides CRUD operation for the account's watchlist. An account can have multiple watchlists and each is uniquely identified by id but can also be addressed by user-defined name.
 * 
 * @export
 * @interface WatchlistWithoutAsset
 */
export interface WatchlistWithoutAsset {
    /**
     * account ID
     * @type {string}
     * @memberof WatchlistWithoutAsset
     */
    accountId: string;
    /**
     * 
     * @type {Date}
     * @memberof WatchlistWithoutAsset
     */
    createdAt: Date;
    /**
     * watchlist id
     * @type {string}
     * @memberof WatchlistWithoutAsset
     */
    id: string;
    /**
     * user-defined watchlist name (up to 64 characters)
     * @type {string}
     * @memberof WatchlistWithoutAsset
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof WatchlistWithoutAsset
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the WatchlistWithoutAsset interface.
 */
export function instanceOfWatchlistWithoutAsset(value: object): value is WatchlistWithoutAsset {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WatchlistWithoutAssetFromJSON(json: any): WatchlistWithoutAsset {
    return WatchlistWithoutAssetFromJSONTyped(json, false);
}

export function WatchlistWithoutAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistWithoutAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function WatchlistWithoutAssetToJSON(json: any): WatchlistWithoutAsset {
    return WatchlistWithoutAssetToJSONTyped(json, false);
}

export function WatchlistWithoutAssetToJSONTyped(value?: WatchlistWithoutAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

