import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { renderDocsExamples } from "../scripts/gen-docs-examples";
import { renderDocsMigration } from "../scripts/gen-docs-migration";

describe("docs migration generator", () => {
    it("adds generated frontmatter and rewrites only repository-relative links", () => {
        const source = [
            "# Migration guide",
            "",
            "[Codemod](codemods/alpaca-v3-to-v4.js)",
            "[Reference](codemods/README.md)",
            "[Section](#before-you-start)",
            "[External](https://example.com/guide)",
            "",
        ].join("\n");

        expect(renderDocsMigration(source)).toBe(
            [
                "---",
                "sidebar_position: 2",
                "title: Migrate from 3.x",
                "custom_edit_url: null",
                "---",
                "",
                "<!-- Generated by scripts/gen-docs-migration.ts from MIGRATION.md — do not edit by hand. -->",
                "",
                "# Migration guide",
                "",
                "[Codemod](https://github.com/alpacahq/alpaca-trade-api-js/blob/master/codemods/alpaca-v3-to-v4.js)",
                "[Reference](https://github.com/alpacahq/alpaca-trade-api-js/blob/master/codemods/README.md)",
                "[Section](#before-you-start)",
                "[External](https://example.com/guide)",
                "",
            ].join("\n"),
        );
    });

    it("keeps the generated migration page ignored beside other generated docs", () => {
        const gitignore = readFileSync(resolve(import.meta.dirname, "..", ".gitignore"), "utf8");
        const lines = gitignore.split(/\r?\n/);
        const examplesIndex = lines.indexOf("docs/docs/examples.md");
        expect(examplesIndex).toBeGreaterThan(-1);
        expect(lines[examplesIndex + 1]).toBe("docs/docs/migration.md");
    });

    it("preserves stable 4.x install guidance", () => {
        const source = readFileSync(resolve(import.meta.dirname, "..", "MIGRATION.md"), "utf8");
        const generated = renderDocsMigration(source);

        for (const guide of [source, generated]) {
            expect(guide).toContain("npm install @alpacahq/alpaca-trade-api@^4");
            expect(guide).toContain(
                "npm install alpaca-v4@npm:@alpacahq/alpaca-trade-api@^4",
            );
            expect(guide).not.toContain("@alpha");
            expect(guide).not.toContain("prerelease");
            expect(guide).not.toContain("After stable `4.0.0` publishes");
        }
    });

    it("keeps current-version examples aligned with the 4.x types and semantics", () => {
        const source = readFileSync(resolve(import.meta.dirname, "..", "MIGRATION.md"), "utf8");

        expect(source).toContain("Every generated REST call takes **a single options object**");
        expect(source).toContain('start: new Date("2024-01-01")');
        expect(source).toContain('end: new Date("2024-02-01")');
        expect(source).toContain('extendedHours: "true"');
        expect(source).toContain('market: "NYSE"');
        expect(source).toContain("createWatchlistRequest: { name: n, symbols: s }");
        expect(source).toContain(
            'getStockBarsFor("AAPL", {\n  start: new Date("2024-04-01"), end: new Date("2024-04-02"),',
        );
        expect(source).toContain(
            "for await (const { symbol, value } of alpaca.marketData.iterateStockBars",
        );
        expect(source).toContain(
            'marketData.getCryptoBars({ loc: "us", symbols: ss, ...o\' })',
        );
        expect(source).toContain("low-level `trading.Configuration`");
        expect(source).toContain("custom `fetchApi` or middleware");
        expect(source).toContain("const terminalOrder = await alpaca.trading.submitAndWait");
        expect(source).toContain('if (terminalOrder.status === "filled")');
        expect(source).toContain("Historical stock feeds are `iex`, `sip`, `otc`, and `boats`");
        expect(source).toContain("`delayed_sip` is supported only where explicitly");
        expect(source).toContain("typed, such as streaming and latest-data calls");
        expect(source).toContain(
            "alpaca.getOrderByClientId(cid)\n  → alpaca.trading.orders.getOrderByClientOrderId",
        );
        expect(source).toContain(
            "| `getOrderByClientId(c)` | `trading.orders.getOrderByClientOrderId",
        );

        expect(source).not.toContain(
            "override per-request via `initOverrides` or `headers`/middleware",
        );
        expect(source).not.toContain(
            'market: "us_equity", start: "2024-01-01", end: "2024-01-31"',
        );
        expect(source).not.toContain(
            'updateWatchlistRequest: { name: "My list", symbols: ["AAPL", "MSFT"] }',
        );
        expect(source).not.toContain(
            "for await (const page of alpaca.marketData.iterateStockBars",
        );
        expect(source).not.toContain(
            "const filled = await alpaca.trading.submitAndWait",
        );
        expect(source).not.toContain(
            'console.log("filled at", filled.filledAvgPrice)',
        );
        expect(source).not.toContain("alpaca.getOrderByClientOrderId(cid)");
        expect(source).not.toContain("| `getOrderByClientOrderId(c)` |");

        // The 3.x snippets remain intentionally unchanged as historical context.
        expect(source).toContain('date_start: "2024-01-01"');
        expect(source).toContain(
            'await alpaca.getCalendar({ start: "2024-01-01", end: "2024-01-31" });',
        );
    });

    it("subscribes to order/trade updates before connecting the 4.x trading stream", () => {
        const source = readFileSync(resolve(import.meta.dirname, "..", "MIGRATION.md"), "utf8");
        const start = source.indexOf("// 4.x\nconst tws = alpaca.trading.stream();");
        const end = source.indexOf("> Streaming requires", start);
        const example = source.slice(start, end);

        expect(source).toMatch(/order\/trade updates/i);
        expect(source).not.toContain("order/account updates");
        expect(start).toBeGreaterThan(-1);
        expect(example.indexOf("tws.subscribeTradeUpdates();")).toBeGreaterThan(-1);
        expect(example.indexOf("tws.connect();")).toBeGreaterThan(
            example.indexOf("tws.subscribeTradeUpdates();"),
        );
        expect(example).not.toMatch(/onConnect\([^)]*subscribeTradeUpdates/s);
    });

    it("documents field-agnostic lossless parsing for every unsafe integer token", () => {
        const source = readFileSync(resolve(import.meta.dirname, "..", "MIGRATION.md"), "utf8");

        expect(source).toMatch(
            /lossless parser.*any unsafe integer token.*Number\.MAX_SAFE_INTEGER.*string.*regardless of field/is,
        );
        expect(source).toMatch(/crypto trade\s+ids.*common.*not.*exclusive/is);
        expect(source).not.toMatch(/other integers.*unaffected/is);
    });

    it("gives every executable 4.x order-placement example a generated client order id", () => {
        const source = readFileSync(resolve(import.meta.dirname, "..", "MIGRATION.md"), "utf8");
        const orders = source.slice(
            source.indexOf("#### Create order"),
            source.indexOf("#### Read / list / modify / cancel"),
        );
        const errors = source.slice(
            source.indexOf("## Error handling"),
            source.indexOf("## Semantic changes"),
        );

        for (const method of ["market", "limit", "bracket", "postOrder"]) {
            const call = orders.match(
                new RegExp(
                    `await alpaca\\.trading\\.orders\\.${method}\\(\\{[\\s\\S]*?\\n\\}\\);`,
                ),
            )?.[0];
            expect(call, `missing current ${method} placement example`).toBeDefined();
            expect(call, `${method} example must pass clientOrderId`).toContain(
                "clientOrderId",
            );
        }
        expect(orders.match(/crypto\.randomUUID\(\)/g)?.length).toBeGreaterThanOrEqual(5);
        expect(errors).toContain("const clientOrderId = crypto.randomUUID();");
        expect(errors).toMatch(
            /orders\.market\(\{[^}]*clientOrderId[^}]*\}\)/s,
        );
    });
});

describe("docs examples generator", () => {
    it("renders deterministic generated frontmatter with edit links disabled", () => {
        const source = [
            "/**",
            " * Places a paper order.",
            " *",
            " * Run:",
            " * npx tsx examples/demo.ts",
            " */",
            'console.log("demo");',
            "",
        ].join("\n");

        const generated = renderDocsExamples([{ file: "demo.ts", source }]);

        expect(generated).toContain(
            [
                "---",
                "sidebar_position: 9",
                "title: Examples",
                "custom_edit_url: null",
                "---",
            ].join("\n"),
        );
        expect(generated).toContain("## [`demo.ts`]");
        expect(generated).toContain("Places a paper order.");
        expect(generated).toContain("npx tsx examples/demo.ts");
        expect(generated).toContain('console.log("demo");');
        expect(renderDocsExamples([{ file: "demo.ts", source }])).toBe(generated);
    });
});
