/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CorporateActionsResp,
  Region,
  Sort,
} from '../models/index';
import {
    CorporateActionsRespFromJSON,
    CorporateActionsRespToJSON,
    RegionFromJSON,
    RegionToJSON,
    SortFromJSON,
    SortToJSON,
} from '../models/index';

export interface CorporateActionsRequest {
    symbols?: string;
    cusips?: string;
    types?: string;
    region?: Region;
    start?: Date;
    end?: Date;
    ids?: string;
    limit?: number;
    pageToken?: string;
    sort?: Sort;
}

/**
 * 
 */
export class CorporateActionsApi extends runtime.BaseAPI {

    /**
     * This endpoint provides data about the corporate actions for each given symbol over a specified time period.  > ⚠️ Warning > > Currently Alpaca has no guarantees on the creation time of corporate actions. There may be delays in receiving corporate actions from our data providers, and there may be delays in processing and making them available via this API. As a result, corporate actions may not be available immediately after they are announced. 
     * Corporate actions
     */
    async corporateActionsRaw(requestParameters: CorporateActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporateActionsResp>> {
        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['cusips'] != null) {
            queryParameters['cusips'] = requestParameters['cusips'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v1/corporate-actions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporateActionsRespFromJSON(jsonValue));
    }

    /**
     * This endpoint provides data about the corporate actions for each given symbol over a specified time period.  > ⚠️ Warning > > Currently Alpaca has no guarantees on the creation time of corporate actions. There may be delays in receiving corporate actions from our data providers, and there may be delays in processing and making them available via this API. As a result, corporate actions may not be available immediately after they are announced. 
     * Corporate actions
     */
    async corporateActions(requestParameters: CorporateActionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporateActionsResp> {
        const response = await this.corporateActionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
