/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface LogosRequest {
    symbol: string;
    placeholder?: boolean;
}

/**
 * 
 */
export class LogosApi extends runtime.BaseAPI {

    /**
     * Get the image of the company logo for the given symbol.
     * Logos
     */
    async logosRaw(requestParameters: LogosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling logos().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['placeholder'] != null) {
            queryParameters['placeholder'] = requestParameters['placeholder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v1beta1/logos/{symbol}`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get the image of the company logo for the given symbol.
     * Logos
     */
    async logos(requestParameters: LogosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.logosRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
