/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Sort,
  StockAuctionsResp,
  StockAuctionsRespSingle,
  StockBarsResp,
  StockBarsRespSingle,
  StockHistoricalFeed,
  StockLatestBarsResp,
  StockLatestBarsRespSingle,
  StockLatestFeed,
  StockLatestQuotesResp,
  StockLatestQuotesRespSingle,
  StockLatestTradesResp,
  StockLatestTradesRespSingle,
  StockQuotesResp,
  StockQuotesRespSingle,
  StockSnapshot,
  StockSnapshotsRespSingle,
  StockTradesResp,
  StockTradesRespSingle,
} from '../models/index';
import {
    SortFromJSON,
    SortToJSON,
    StockAuctionsRespFromJSON,
    StockAuctionsRespToJSON,
    StockAuctionsRespSingleFromJSON,
    StockAuctionsRespSingleToJSON,
    StockBarsRespFromJSON,
    StockBarsRespToJSON,
    StockBarsRespSingleFromJSON,
    StockBarsRespSingleToJSON,
    StockHistoricalFeedFromJSON,
    StockHistoricalFeedToJSON,
    StockLatestBarsRespFromJSON,
    StockLatestBarsRespToJSON,
    StockLatestBarsRespSingleFromJSON,
    StockLatestBarsRespSingleToJSON,
    StockLatestFeedFromJSON,
    StockLatestFeedToJSON,
    StockLatestQuotesRespFromJSON,
    StockLatestQuotesRespToJSON,
    StockLatestQuotesRespSingleFromJSON,
    StockLatestQuotesRespSingleToJSON,
    StockLatestTradesRespFromJSON,
    StockLatestTradesRespToJSON,
    StockLatestTradesRespSingleFromJSON,
    StockLatestTradesRespSingleToJSON,
    StockQuotesRespFromJSON,
    StockQuotesRespToJSON,
    StockQuotesRespSingleFromJSON,
    StockQuotesRespSingleToJSON,
    StockSnapshotFromJSON,
    StockSnapshotToJSON,
    StockSnapshotsRespSingleFromJSON,
    StockSnapshotsRespSingleToJSON,
    StockTradesRespFromJSON,
    StockTradesRespToJSON,
    StockTradesRespSingleFromJSON,
    StockTradesRespSingleToJSON,
} from '../models/index';

export interface StockAuctionSingleRequest {
    symbol: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockAuctionsRequest {
    symbols: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockBarSingleRequest {
    symbol: string;
    timeframe: string;
    start?: Date;
    end?: Date;
    limit?: number;
    adjustment?: string;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockBarsRequest {
    symbols: string;
    timeframe: string;
    start?: Date;
    end?: Date;
    limit?: number;
    adjustment?: string;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockLatestBarSingleRequest {
    symbol: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockLatestBarsRequest {
    symbols: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockLatestQuoteSingleRequest {
    symbol: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockLatestQuotesRequest {
    symbols: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockLatestTradeSingleRequest {
    symbol: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockLatestTradesRequest {
    symbols: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockMetaConditionsRequest {
    ticktype: StockMetaConditionsTicktypeEnum;
    tape: StockMetaConditionsTapeEnum;
}

export interface StockQuoteSingleRequest {
    symbol: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockQuotesRequest {
    symbols: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockSnapshotSingleRequest {
    symbol: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockSnapshotsRequest {
    symbols: string;
    feed?: StockLatestFeed;
    currency?: string;
}

export interface StockTradeSingleRequest {
    symbol: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

export interface StockTradesRequest {
    symbols: string;
    start?: Date;
    end?: Date;
    limit?: number;
    asof?: string;
    feed?: StockHistoricalFeed;
    currency?: string;
    pageToken?: string;
    sort?: Sort;
}

/**
 * 
 */
export class StockApi extends runtime.BaseAPI {

    /**
     * The historical auctions endpoint provides auction prices for the given stock symbol between the specified dates. 
     * Historical auctions (single)
     */
    async stockAuctionSingleRaw(requestParameters: StockAuctionSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockAuctionsRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockAuctionSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/auctions`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockAuctionsRespSingleFromJSON(jsonValue));
    }

    /**
     * The historical auctions endpoint provides auction prices for the given stock symbol between the specified dates. 
     * Historical auctions (single)
     */
    async stockAuctionSingle(requestParameters: StockAuctionSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockAuctionsRespSingle> {
        const response = await this.stockAuctionSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical auctions endpoint provides auction prices for a list of stock symbols between the specified dates. 
     * Historical auctions
     */
    async stockAuctionsRaw(requestParameters: StockAuctionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockAuctionsResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockAuctions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/auctions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockAuctionsRespFromJSON(jsonValue));
    }

    /**
     * The historical auctions endpoint provides auction prices for a list of stock symbols between the specified dates. 
     * Historical auctions
     */
    async stockAuctions(requestParameters: StockAuctionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockAuctionsResp> {
        const response = await this.stockAuctionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical stock bars API provides aggregates for the stock symbol between the specified dates.
     * Historical bars (single symbol)
     */
    async stockBarSingleRaw(requestParameters: StockBarSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockBarsRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockBarSingle().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling stockBarSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['adjustment'] != null) {
            queryParameters['adjustment'] = requestParameters['adjustment'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/bars`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockBarsRespSingleFromJSON(jsonValue));
    }

    /**
     * The historical stock bars API provides aggregates for the stock symbol between the specified dates.
     * Historical bars (single symbol)
     */
    async stockBarSingle(requestParameters: StockBarSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockBarsRespSingle> {
        const response = await this.stockBarSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical stock bars API provides aggregates for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first, then by bar timestamp. This means that you are likely to see only one symbol in your first response if there are enough bars for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any bars were found for them.
     * Historical bars
     */
    async stockBarsRaw(requestParameters: StockBarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockBarsResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockBars().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling stockBars().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['adjustment'] != null) {
            queryParameters['adjustment'] = requestParameters['adjustment'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/bars`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockBarsRespFromJSON(jsonValue));
    }

    /**
     * The historical stock bars API provides aggregates for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first, then by bar timestamp. This means that you are likely to see only one symbol in your first response if there are enough bars for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any bars were found for them.
     * Historical bars
     */
    async stockBars(requestParameters: StockBarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockBarsResp> {
        const response = await this.stockBarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest bar endpoint returns the latest minute bar for the given ticker symbol. 
     * Latest bar (single symbol)
     */
    async stockLatestBarSingleRaw(requestParameters: StockLatestBarSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestBarsRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockLatestBarSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/bars/latest`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestBarsRespSingleFromJSON(jsonValue));
    }

    /**
     * The latest bar endpoint returns the latest minute bar for the given ticker symbol. 
     * Latest bar (single symbol)
     */
    async stockLatestBarSingle(requestParameters: StockLatestBarSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestBarsRespSingle> {
        const response = await this.stockLatestBarSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest bars endpoint provides the latest minute bar for the given ticker symbols. 
     * Latest bars
     */
    async stockLatestBarsRaw(requestParameters: StockLatestBarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestBarsResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockLatestBars().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/bars/latest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestBarsRespFromJSON(jsonValue));
    }

    /**
     * The latest bars endpoint provides the latest minute bar for the given ticker symbols. 
     * Latest bars
     */
    async stockLatestBars(requestParameters: StockLatestBarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestBarsResp> {
        const response = await this.stockLatestBarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest quote endpoint provides the latest best bid and ask prices for a given ticker symbol. 
     * Latest quote (single symbol)
     */
    async stockLatestQuoteSingleRaw(requestParameters: StockLatestQuoteSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestQuotesRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockLatestQuoteSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/quotes/latest`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestQuotesRespSingleFromJSON(jsonValue));
    }

    /**
     * The latest quote endpoint provides the latest best bid and ask prices for a given ticker symbol. 
     * Latest quote (single symbol)
     */
    async stockLatestQuoteSingle(requestParameters: StockLatestQuoteSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestQuotesRespSingle> {
        const response = await this.stockLatestQuoteSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest quotes endpoint provides the latest best bid and ask prices for the given ticker symbols. 
     * Latest quotes
     */
    async stockLatestQuotesRaw(requestParameters: StockLatestQuotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestQuotesResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockLatestQuotes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/quotes/latest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestQuotesRespFromJSON(jsonValue));
    }

    /**
     * The latest quotes endpoint provides the latest best bid and ask prices for the given ticker symbols. 
     * Latest quotes
     */
    async stockLatestQuotes(requestParameters: StockLatestQuotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestQuotesResp> {
        const response = await this.stockLatestQuotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest trade endpoint provides the latest trade for the given ticker symbol.  Trades with any conditions that causes them to not update the bar price are excluded. For example a trade with condition `I` (odd lot) will never appear on this endpoint. You can find the complete list of excluded conditions in [this FAQ](https://docs.alpaca.markets/docs/market-data-faq#how-are-bars-aggregated).
     * Latest trade (single symbol)
     */
    async stockLatestTradeSingleRaw(requestParameters: StockLatestTradeSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestTradesRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockLatestTradeSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/trades/latest`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestTradesRespSingleFromJSON(jsonValue));
    }

    /**
     * The latest trade endpoint provides the latest trade for the given ticker symbol.  Trades with any conditions that causes them to not update the bar price are excluded. For example a trade with condition `I` (odd lot) will never appear on this endpoint. You can find the complete list of excluded conditions in [this FAQ](https://docs.alpaca.markets/docs/market-data-faq#how-are-bars-aggregated).
     * Latest trade (single symbol)
     */
    async stockLatestTradeSingle(requestParameters: StockLatestTradeSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestTradesRespSingle> {
        const response = await this.stockLatestTradeSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The latest trades endpoint provides the latest trades for the given ticker symbols.  Trades with any conditions that causes them to not update the bar price are excluded. For example a trade with condition `I` (odd lot) will never appear on this endpoint. You can find the complete list of excluded conditions in [this FAQ](https://docs.alpaca.markets/docs/market-data-faq#how-are-bars-aggregated).
     * Latest trades
     */
    async stockLatestTradesRaw(requestParameters: StockLatestTradesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLatestTradesResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockLatestTrades().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/trades/latest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLatestTradesRespFromJSON(jsonValue));
    }

    /**
     * The latest trades endpoint provides the latest trades for the given ticker symbols.  Trades with any conditions that causes them to not update the bar price are excluded. For example a trade with condition `I` (odd lot) will never appear on this endpoint. You can find the complete list of excluded conditions in [this FAQ](https://docs.alpaca.markets/docs/market-data-faq#how-are-bars-aggregated).
     * Latest trades
     */
    async stockLatestTrades(requestParameters: StockLatestTradesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLatestTradesResp> {
        const response = await this.stockLatestTradesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the mapping between the condition codes and names.
     * Condition codes
     */
    async stockMetaConditionsRaw(requestParameters: StockMetaConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['ticktype'] == null) {
            throw new runtime.RequiredError(
                'ticktype',
                'Required parameter "ticktype" was null or undefined when calling stockMetaConditions().'
            );
        }

        if (requestParameters['tape'] == null) {
            throw new runtime.RequiredError(
                'tape',
                'Required parameter "tape" was null or undefined when calling stockMetaConditions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tape'] != null) {
            queryParameters['tape'] = requestParameters['tape'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/meta/conditions/{ticktype}`;
        urlPath = urlPath.replace(`{${"ticktype"}}`, encodeURIComponent(String(requestParameters['ticktype'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns the mapping between the condition codes and names.
     * Condition codes
     */
    async stockMetaConditions(requestParameters: StockMetaConditionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.stockMetaConditionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the mapping between the stock exchange codes and the corresponding exchange names. 
     * Exchange codes
     */
    async stockMetaExchangesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/meta/exchanges`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns the mapping between the stock exchange codes and the corresponding exchange names. 
     * Exchange codes
     */
    async stockMetaExchanges(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.stockMetaExchangesRaw(initOverrides);
        return await response.value();
    }

    /**
     * The historical stock quotes API provides quote data for a stock symbol between the specified dates.
     * Historical quotes (single symbol)
     */
    async stockQuoteSingleRaw(requestParameters: StockQuoteSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockQuotesRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockQuoteSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/quotes`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockQuotesRespSingleFromJSON(jsonValue));
    }

    /**
     * The historical stock quotes API provides quote data for a stock symbol between the specified dates.
     * Historical quotes (single symbol)
     */
    async stockQuoteSingle(requestParameters: StockQuoteSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockQuotesRespSingle> {
        const response = await this.stockQuoteSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical stock quotes API provides quote data for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first, then by the quote timestamp. This means that you are likely to see only one symbol in your first response if there are enough quotes for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any quotes were found for them.
     * Historical quotes
     */
    async stockQuotesRaw(requestParameters: StockQuotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockQuotesResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockQuotes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/quotes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockQuotesRespFromJSON(jsonValue));
    }

    /**
     * The historical stock quotes API provides quote data for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first, then by the quote timestamp. This means that you are likely to see only one symbol in your first response if there are enough quotes for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any quotes were found for them.
     * Historical quotes
     */
    async stockQuotes(requestParameters: StockQuotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockQuotesResp> {
        const response = await this.stockQuotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The snapshot endpoint provides the latest trade, latest quote, minute bar, daily bar, and previous daily bar data for a given ticker symbol. 
     * Snapshot (single symbol)
     */
    async stockSnapshotSingleRaw(requestParameters: StockSnapshotSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockSnapshotsRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockSnapshotSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/snapshot`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockSnapshotsRespSingleFromJSON(jsonValue));
    }

    /**
     * The snapshot endpoint provides the latest trade, latest quote, minute bar, daily bar, and previous daily bar data for a given ticker symbol. 
     * Snapshot (single symbol)
     */
    async stockSnapshotSingle(requestParameters: StockSnapshotSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockSnapshotsRespSingle> {
        const response = await this.stockSnapshotSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The snapshot endpoint for multiple tickers provides the latest trade, latest quote, minute bar, daily bar, and previous daily bar data for each given ticker symbol. 
     * Snapshots
     */
    async stockSnapshotsRaw(requestParameters: StockSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: StockSnapshot; }>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockSnapshots().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/snapshots`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, StockSnapshotFromJSON));
    }

    /**
     * The snapshot endpoint for multiple tickers provides the latest trade, latest quote, minute bar, daily bar, and previous daily bar data for each given ticker symbol. 
     * Snapshots
     */
    async stockSnapshots(requestParameters: StockSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: StockSnapshot; }> {
        const response = await this.stockSnapshotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical stock trades API provides trade data for a stock symbol between the specified dates.
     * Historical trades (single symbol)
     */
    async stockTradeSingleRaw(requestParameters: StockTradeSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockTradesRespSingle>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling stockTradeSingle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/{symbol}/trades`;
        urlPath = urlPath.replace(`{${"symbol"}}`, encodeURIComponent(String(requestParameters['symbol'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockTradesRespSingleFromJSON(jsonValue));
    }

    /**
     * The historical stock trades API provides trade data for a stock symbol between the specified dates.
     * Historical trades (single symbol)
     */
    async stockTradeSingle(requestParameters: StockTradeSingleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockTradesRespSingle> {
        const response = await this.stockTradeSingleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The historical stock trades API provides trade data for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first then by trade timestamp. This means that you are likely to see only one symbol in your first response if there are enough trades for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any trades were found for them.
     * Historical trades
     */
    async stockTradesRaw(requestParameters: StockTradesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockTradesResp>> {
        if (requestParameters['symbols'] == null) {
            throw new runtime.RequiredError(
                'symbols',
                'Required parameter "symbols" was null or undefined when calling stockTrades().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbols'] != null) {
            queryParameters['symbols'] = requestParameters['symbols'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['asof'] != null) {
            queryParameters['asof'] = requestParameters['asof'];
        }

        if (requestParameters['feed'] != null) {
            queryParameters['feed'] = requestParameters['feed'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // apiSecret authentication
        }


        let urlPath = `/v2/stocks/trades`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockTradesRespFromJSON(jsonValue));
    }

    /**
     * The historical stock trades API provides trade data for a list of stock symbols between the specified dates.  The returned results are sorted by symbol first then by trade timestamp. This means that you are likely to see only one symbol in your first response if there are enough trades for that symbol to hit the limit you requested.  In these situations, if you keep requesting again with the `next_page_token` from the previous response, you will eventually reach the other symbols if any trades were found for them.
     * Historical trades
     */
    async stockTrades(requestParameters: StockTradesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockTradesResp> {
        const response = await this.stockTradesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const StockMetaConditionsTicktypeEnum = {
    Trade: 'trade',
    Quote: 'quote'
} as const;
export type StockMetaConditionsTicktypeEnum = typeof StockMetaConditionsTicktypeEnum[keyof typeof StockMetaConditionsTicktypeEnum];
/**
 * @export
 */
export const StockMetaConditionsTapeEnum = {
    A: 'A',
    B: 'B',
    C: 'C'
} as const;
export type StockMetaConditionsTapeEnum = typeof StockMetaConditionsTapeEnum[keyof typeof StockMetaConditionsTapeEnum];
