/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Spin-off payload delivered when
 * `event_type == spin_off_corporateaction_event`. Corresponds to
 * `spin_offs` on the REST
 * [`GET /v1/corporate-actions`](#operation/CorporateActions) response, but
 * every decimal field is emitted as a JSON string to preserve precision on
 * the wire.
 * 
 * @export
 * @interface CaEventSpinOff
 */
export interface CaEventSpinOff {
    /**
     * The internal Alpaca identifier of the corporate action.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    id: string;
    /**
     * The date when the corporate action is processed by Alpaca.
     * @type {Date}
     * @memberof CaEventSpinOff
     */
    processDate: Date;
    /**
     * The ISO 4217 currency code associated with the corporate action.
     * Empty value can mean USD, non-applicable (e.g. for name changes) or unknown
     * (can change later to a valid currency).
     * 
     * @type {string}
     * @memberof CaEventSpinOff
     */
    currency?: string;
    /**
     * The date when due bill obligations are redeemed.
     * @type {Date}
     * @memberof CaEventSpinOff
     */
    dueBillRedemptionDate?: Date;
    /**
     * The ex-date marks the cutoff point for shareholders to be credited.
     * @type {Date}
     * @memberof CaEventSpinOff
     */
    exDate: Date;
    /**
     * CUSIP of the new spin-off company.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    newCusip: string;
    /**
     * International Securities Identification Number (ISIN) as defined by ISO 6166.
     * May be empty for US corporate actions.
     * 
     * @type {string}
     * @memberof CaEventSpinOff
     */
    newIsin?: string;
    /**
     * New-company shares distributed per `source_rate` parent shares, as a decimal string.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    newRate: string;
    /**
     * Ticker of the new spin-off company.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    newSymbol: string;
    /**
     * The date when the corporate action benefit is paid or distributed.
     * @type {Date}
     * @memberof CaEventSpinOff
     */
    payableDate?: Date;
    /**
     * The date shareholders must own shares to receive the benefit.
     * @type {Date}
     * @memberof CaEventSpinOff
     */
    recordDate?: Date;
    /**
     * Parent CUSIP.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    sourceCusip: string;
    /**
     * International Securities Identification Number (ISIN) as defined by ISO 6166.
     * May be empty for US corporate actions.
     * 
     * @type {string}
     * @memberof CaEventSpinOff
     */
    sourceIsin?: string;
    /**
     * Parent shares required per ratio unit, as a decimal string.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    sourceRate: string;
    /**
     * Parent company's ticker.
     * @type {string}
     * @memberof CaEventSpinOff
     */
    sourceSymbol: string;
}

/**
 * Check if a given object implements the CaEventSpinOff interface.
 */
export function instanceOfCaEventSpinOff(value: object): value is CaEventSpinOff {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('processDate' in value) || value['processDate'] === undefined) return false;
    if (!('exDate' in value) || value['exDate'] === undefined) return false;
    if (!('newCusip' in value) || value['newCusip'] === undefined) return false;
    if (!('newRate' in value) || value['newRate'] === undefined) return false;
    if (!('newSymbol' in value) || value['newSymbol'] === undefined) return false;
    if (!('sourceCusip' in value) || value['sourceCusip'] === undefined) return false;
    if (!('sourceRate' in value) || value['sourceRate'] === undefined) return false;
    if (!('sourceSymbol' in value) || value['sourceSymbol'] === undefined) return false;
    return true;
}

export function CaEventSpinOffFromJSON(json: any): CaEventSpinOff {
    return CaEventSpinOffFromJSONTyped(json, false);
}

export function CaEventSpinOffFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaEventSpinOff {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'processDate': (new Date(json['process_date'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'dueBillRedemptionDate': json['due_bill_redemption_date'] == null ? undefined : (new Date(json['due_bill_redemption_date'])),
        'exDate': (new Date(json['ex_date'])),
        'newCusip': json['new_cusip'],
        'newIsin': json['new_isin'] == null ? undefined : json['new_isin'],
        'newRate': json['new_rate'],
        'newSymbol': json['new_symbol'],
        'payableDate': json['payable_date'] == null ? undefined : (new Date(json['payable_date'])),
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'sourceCusip': json['source_cusip'],
        'sourceIsin': json['source_isin'] == null ? undefined : json['source_isin'],
        'sourceRate': json['source_rate'],
        'sourceSymbol': json['source_symbol'],
    };
}

export function CaEventSpinOffToJSON(json: any): CaEventSpinOff {
    return CaEventSpinOffToJSONTyped(json, false);
}

export function CaEventSpinOffToJSONTyped(value?: CaEventSpinOff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'process_date': ((value['processDate']).toISOString().substring(0,10)),
        'currency': value['currency'],
        'due_bill_redemption_date': value['dueBillRedemptionDate'] == null ? undefined : ((value['dueBillRedemptionDate']).toISOString().substring(0,10)),
        'ex_date': ((value['exDate']).toISOString().substring(0,10)),
        'new_cusip': value['newCusip'],
        'new_isin': value['newIsin'],
        'new_rate': value['newRate'],
        'new_symbol': value['newSymbol'],
        'payable_date': value['payableDate'] == null ? undefined : ((value['payableDate']).toISOString().substring(0,10)),
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'source_cusip': value['sourceCusip'],
        'source_isin': value['sourceIsin'],
        'source_rate': value['sourceRate'],
        'source_symbol': value['sourceSymbol'],
    };
}

