/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Discriminator that determines the shape of the `ca` field on a
 * [`corporate_action_event`](#/components/schemas/corporate_action_event).
 * 
 * Each value corresponds to a per-type payload schema:
 * 
 * | `event_type` | `ca` schema |
 * | --- | --- |
 * | `capital_gains_distribution_corporateaction_event` | [`ca_event_capital_gains_distribution`](#/components/schemas/ca_event_capital_gains_distribution) |
 * | `cash_dividend_corporateaction_event` | [`ca_event_cash_dividend`](#/components/schemas/ca_event_cash_dividend) |
 * | `cash_merger_corporateaction_event` | [`ca_event_cash_merger`](#/components/schemas/ca_event_cash_merger) |
 * | `equity_partial_call_corporateaction_event` | [`ca_event_equity_partial_call`](#/components/schemas/ca_event_equity_partial_call) |
 * | `forward_split_corporateaction_event` | [`ca_event_forward_split`](#/components/schemas/ca_event_forward_split) |
 * | `name_change_corporateaction_event` | [`ca_event_name_change`](#/components/schemas/ca_event_name_change) |
 * | `redemption_corporateaction_event` | [`ca_event_redemption`](#/components/schemas/ca_event_redemption) |
 * | `reorganization_corporateaction_event` | [`ca_event_reorganization`](#/components/schemas/ca_event_reorganization) |
 * | `reverse_split_corporateaction_event` | [`ca_event_reverse_split`](#/components/schemas/ca_event_reverse_split) |
 * | `rights_distribution_corporateaction_event` | [`ca_event_rights_distribution`](#/components/schemas/ca_event_rights_distribution) |
 * | `spin_off_corporateaction_event` | [`ca_event_spin_off`](#/components/schemas/ca_event_spin_off) |
 * | `stock_and_cash_merger_corporateaction_event` | [`ca_event_stock_and_cash_merger`](#/components/schemas/ca_event_stock_and_cash_merger) |
 * | `stock_dividend_corporateaction_event` | [`ca_event_stock_dividend`](#/components/schemas/ca_event_stock_dividend) |
 * | `stock_merger_corporateaction_event` | [`ca_event_stock_merger`](#/components/schemas/ca_event_stock_merger) |
 * | `unit_split_corporateaction_event` | [`ca_event_unit_split`](#/components/schemas/ca_event_unit_split) |
 * | `worthless_removal_corporateaction_event` | [`ca_event_worthless_removal`](#/components/schemas/ca_event_worthless_removal) |
 * 
 * @export
 */
export const CorporateActionEventType = {
    CapitalGainsDistributionCorporateactionEvent: 'capital_gains_distribution_corporateaction_event',
    CashDividendCorporateactionEvent: 'cash_dividend_corporateaction_event',
    CashMergerCorporateactionEvent: 'cash_merger_corporateaction_event',
    EquityPartialCallCorporateactionEvent: 'equity_partial_call_corporateaction_event',
    ForwardSplitCorporateactionEvent: 'forward_split_corporateaction_event',
    NameChangeCorporateactionEvent: 'name_change_corporateaction_event',
    RedemptionCorporateactionEvent: 'redemption_corporateaction_event',
    ReorganizationCorporateactionEvent: 'reorganization_corporateaction_event',
    ReverseSplitCorporateactionEvent: 'reverse_split_corporateaction_event',
    RightsDistributionCorporateactionEvent: 'rights_distribution_corporateaction_event',
    SpinOffCorporateactionEvent: 'spin_off_corporateaction_event',
    StockAndCashMergerCorporateactionEvent: 'stock_and_cash_merger_corporateaction_event',
    StockDividendCorporateactionEvent: 'stock_dividend_corporateaction_event',
    StockMergerCorporateactionEvent: 'stock_merger_corporateaction_event',
    UnitSplitCorporateactionEvent: 'unit_split_corporateaction_event',
    WorthlessRemovalCorporateactionEvent: 'worthless_removal_corporateaction_event'
} as const;
export type CorporateActionEventType = typeof CorporateActionEventType[keyof typeof CorporateActionEventType];


export function instanceOfCorporateActionEventType(value: any): boolean {
    for (const key in CorporateActionEventType) {
        if (Object.prototype.hasOwnProperty.call(CorporateActionEventType, key)) {
            if (CorporateActionEventType[key as keyof typeof CorporateActionEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CorporateActionEventTypeFromJSON(json: any): CorporateActionEventType {
    return CorporateActionEventTypeFromJSONTyped(json, false);
}

export function CorporateActionEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporateActionEventType {
    return json as CorporateActionEventType;
}

export function CorporateActionEventTypeToJSON(value?: CorporateActionEventType | null): any {
    return value as any;
}

export function CorporateActionEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CorporateActionEventType {
    return value as CorporateActionEventType;
}

