/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorporateActions } from './CorporateActions';
import {
    CorporateActionsFromJSON,
    CorporateActionsFromJSONTyped,
    CorporateActionsToJSON,
    CorporateActionsToJSONTyped,
} from './CorporateActions';

/**
 * 
 * @export
 * @interface CorporateActionsResp
 */
export interface CorporateActionsResp {
    /**
     * 
     * @type {CorporateActions}
     * @memberof CorporateActionsResp
     */
    corporateActions: CorporateActions;
    /**
     * Pagination token for the next page.
     * @type {string}
     * @memberof CorporateActionsResp
     */
    nextPageToken: string | null;
}

/**
 * Check if a given object implements the CorporateActionsResp interface.
 */
export function instanceOfCorporateActionsResp(value: object): value is CorporateActionsResp {
    if (!('corporateActions' in value) || value['corporateActions'] === undefined) return false;
    if (!('nextPageToken' in value) || value['nextPageToken'] === undefined) return false;
    return true;
}

export function CorporateActionsRespFromJSON(json: any): CorporateActionsResp {
    return CorporateActionsRespFromJSONTyped(json, false);
}

export function CorporateActionsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporateActionsResp {
    if (json == null) {
        return json;
    }
    return {
        
        'corporateActions': CorporateActionsFromJSON(json['corporate_actions']),
        'nextPageToken': json['next_page_token'],
    };
}

export function CorporateActionsRespToJSON(json: any): CorporateActionsResp {
    return CorporateActionsRespToJSONTyped(json, false);
}

export function CorporateActionsRespToJSONTyped(value?: CorporateActionsResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corporate_actions': CorporateActionsToJSON(value['corporateActions']),
        'next_page_token': value['nextPageToken'],
    };
}

