/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorporateActionEventRegion } from './CorporateActionEventRegion';
import {
    CorporateActionEventRegionFromJSON,
    CorporateActionEventRegionFromJSONTyped,
    CorporateActionEventRegionToJSON,
    CorporateActionEventRegionToJSONTyped,
} from './CorporateActionEventRegion';
import type { CaEventNameChange } from './CaEventNameChange';
import {
    CaEventNameChangeFromJSON,
    CaEventNameChangeFromJSONTyped,
    CaEventNameChangeToJSON,
    CaEventNameChangeToJSONTyped,
} from './CaEventNameChange';
import type { CorporateActionEventAction } from './CorporateActionEventAction';
import {
    CorporateActionEventActionFromJSON,
    CorporateActionEventActionFromJSONTyped,
    CorporateActionEventActionToJSON,
    CorporateActionEventActionToJSONTyped,
} from './CorporateActionEventAction';

/**
 * `corporate_action_event` envelope specialised to `event_type ==
 * name_change_corporateaction_event`. Emitted through
 * [Corporate Actions Events Stream](#operation/SubscribeToCorporateActionsEventsSSE).
 * 
 * @export
 * @interface CorporateActionEventNameChange
 */
export interface CorporateActionEventNameChange {
    /**
     * 
     * @type {CorporateActionEventAction}
     * @memberof CorporateActionEventNameChange
     */
    action: CorporateActionEventAction;
    /**
     * RFC-3339 timestamp when the streaming service emitted this event.
     * @type {Date}
     * @memberof CorporateActionEventNameChange
     */
    at: Date;
    /**
     * Lexically sortable, monotonically increasing 26-character
     * [ULID](https://github.com/ulid/spec) (Crockford Base32, uppercase) that
     * identifies a single SSE emission. Unique per message -- an `update` or
     * `delete` for the same underlying corporate action carries a fresh
     * `event_id`. Because ULIDs sort in emission order, they can be used as
     * resume cursors via `since_id`, `until_id`, or the standard `Last-Event-Id`
     * reconnect header.
     * 
     * @type {string}
     * @memberof CorporateActionEventNameChange
     */
    eventId: string;
    /**
     * 
     * @type {CorporateActionEventRegion}
     * @memberof CorporateActionEventNameChange
     */
    region: CorporateActionEventRegion;
    /**
     * 
     * @type {CaEventNameChange}
     * @memberof CorporateActionEventNameChange
     */
    ca: CaEventNameChange;
    /**
     * 
     * @type {string}
     * @memberof CorporateActionEventNameChange
     */
    eventType: CorporateActionEventNameChangeEventTypeEnum;
}


/**
 * @export
 */
export const CorporateActionEventNameChangeEventTypeEnum = {
    NameChangeCorporateactionEvent: 'name_change_corporateaction_event'
} as const;
export type CorporateActionEventNameChangeEventTypeEnum = typeof CorporateActionEventNameChangeEventTypeEnum[keyof typeof CorporateActionEventNameChangeEventTypeEnum];


/**
 * Check if a given object implements the CorporateActionEventNameChange interface.
 */
export function instanceOfCorporateActionEventNameChange(value: object): value is CorporateActionEventNameChange {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('at' in value) || value['at'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('ca' in value) || value['ca'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    return true;
}

export function CorporateActionEventNameChangeFromJSON(json: any): CorporateActionEventNameChange {
    return CorporateActionEventNameChangeFromJSONTyped(json, false);
}

export function CorporateActionEventNameChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporateActionEventNameChange {
    if (json == null) {
        return json;
    }
    return {
        
        'action': CorporateActionEventActionFromJSON(json['action']),
        'at': (new Date(json['at'])),
        'eventId': json['event_id'],
        'region': CorporateActionEventRegionFromJSON(json['region']),
        'ca': CaEventNameChangeFromJSON(json['ca']),
        'eventType': json['event_type'],
    };
}

export function CorporateActionEventNameChangeToJSON(json: any): CorporateActionEventNameChange {
    return CorporateActionEventNameChangeToJSONTyped(json, false);
}

export function CorporateActionEventNameChangeToJSONTyped(value?: CorporateActionEventNameChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': CorporateActionEventActionToJSON(value['action']),
        'at': ((value['at']).toISOString()),
        'event_id': value['eventId'],
        'region': CorporateActionEventRegionToJSON(value['region']),
        'ca': CaEventNameChangeToJSON(value['ca']),
        'event_type': value['eventType'],
    };
}

