/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CorporateActionEventCapitalGainsDistribution } from './CorporateActionEventCapitalGainsDistribution';
import {
    instanceOfCorporateActionEventCapitalGainsDistribution,
    CorporateActionEventCapitalGainsDistributionFromJSONTyped,
    CorporateActionEventCapitalGainsDistributionToJSON,
} from './CorporateActionEventCapitalGainsDistribution';
import type { CorporateActionEventCashDividend } from './CorporateActionEventCashDividend';
import {
    instanceOfCorporateActionEventCashDividend,
    CorporateActionEventCashDividendFromJSONTyped,
    CorporateActionEventCashDividendToJSON,
} from './CorporateActionEventCashDividend';
import type { CorporateActionEventCashMerger } from './CorporateActionEventCashMerger';
import {
    instanceOfCorporateActionEventCashMerger,
    CorporateActionEventCashMergerFromJSONTyped,
    CorporateActionEventCashMergerToJSON,
} from './CorporateActionEventCashMerger';
import type { CorporateActionEventEquityPartialCall } from './CorporateActionEventEquityPartialCall';
import {
    instanceOfCorporateActionEventEquityPartialCall,
    CorporateActionEventEquityPartialCallFromJSONTyped,
    CorporateActionEventEquityPartialCallToJSON,
} from './CorporateActionEventEquityPartialCall';
import type { CorporateActionEventForwardSplit } from './CorporateActionEventForwardSplit';
import {
    instanceOfCorporateActionEventForwardSplit,
    CorporateActionEventForwardSplitFromJSONTyped,
    CorporateActionEventForwardSplitToJSON,
} from './CorporateActionEventForwardSplit';
import type { CorporateActionEventNameChange } from './CorporateActionEventNameChange';
import {
    instanceOfCorporateActionEventNameChange,
    CorporateActionEventNameChangeFromJSONTyped,
    CorporateActionEventNameChangeToJSON,
} from './CorporateActionEventNameChange';
import type { CorporateActionEventRedemption } from './CorporateActionEventRedemption';
import {
    instanceOfCorporateActionEventRedemption,
    CorporateActionEventRedemptionFromJSONTyped,
    CorporateActionEventRedemptionToJSON,
} from './CorporateActionEventRedemption';
import type { CorporateActionEventReorganization } from './CorporateActionEventReorganization';
import {
    instanceOfCorporateActionEventReorganization,
    CorporateActionEventReorganizationFromJSONTyped,
    CorporateActionEventReorganizationToJSON,
} from './CorporateActionEventReorganization';
import type { CorporateActionEventReverseSplit } from './CorporateActionEventReverseSplit';
import {
    instanceOfCorporateActionEventReverseSplit,
    CorporateActionEventReverseSplitFromJSONTyped,
    CorporateActionEventReverseSplitToJSON,
} from './CorporateActionEventReverseSplit';
import type { CorporateActionEventRightsDistribution } from './CorporateActionEventRightsDistribution';
import {
    instanceOfCorporateActionEventRightsDistribution,
    CorporateActionEventRightsDistributionFromJSONTyped,
    CorporateActionEventRightsDistributionToJSON,
} from './CorporateActionEventRightsDistribution';
import type { CorporateActionEventSpinOff } from './CorporateActionEventSpinOff';
import {
    instanceOfCorporateActionEventSpinOff,
    CorporateActionEventSpinOffFromJSONTyped,
    CorporateActionEventSpinOffToJSON,
} from './CorporateActionEventSpinOff';
import type { CorporateActionEventStockAndCashMerger } from './CorporateActionEventStockAndCashMerger';
import {
    instanceOfCorporateActionEventStockAndCashMerger,
    CorporateActionEventStockAndCashMergerFromJSONTyped,
    CorporateActionEventStockAndCashMergerToJSON,
} from './CorporateActionEventStockAndCashMerger';
import type { CorporateActionEventStockDividend } from './CorporateActionEventStockDividend';
import {
    instanceOfCorporateActionEventStockDividend,
    CorporateActionEventStockDividendFromJSONTyped,
    CorporateActionEventStockDividendToJSON,
} from './CorporateActionEventStockDividend';
import type { CorporateActionEventStockMerger } from './CorporateActionEventStockMerger';
import {
    instanceOfCorporateActionEventStockMerger,
    CorporateActionEventStockMergerFromJSONTyped,
    CorporateActionEventStockMergerToJSON,
} from './CorporateActionEventStockMerger';
import type { CorporateActionEventUnitSplit } from './CorporateActionEventUnitSplit';
import {
    instanceOfCorporateActionEventUnitSplit,
    CorporateActionEventUnitSplitFromJSONTyped,
    CorporateActionEventUnitSplitToJSON,
} from './CorporateActionEventUnitSplit';
import type { CorporateActionEventWorthlessRemoval } from './CorporateActionEventWorthlessRemoval';
import {
    instanceOfCorporateActionEventWorthlessRemoval,
    CorporateActionEventWorthlessRemovalFromJSONTyped,
    CorporateActionEventWorthlessRemovalToJSON,
} from './CorporateActionEventWorthlessRemoval';

/**
 * @type CorporateActionEvent
 * A single corporate-action mutation delivered over the
 * [Corporate Actions Events Stream](#operation/SubscribeToCorporateActionsEventsSSE).
 * 
 * Every event uses the same envelope. The `event_type` field selects which of
 * the 16 per-type schemas populates `ca`; see
 * [`corporate_action_event_type`](#/components/schemas/corporate_action_event_type)
 * for the full mapping and follow the link on each row to the per-type `ca`
 * payload schema.
 * 
 * Optional fields (including `currency` and, on most CA types, `isin`) are
 * omitted from the JSON when empty; `null` is never emitted.
 * 
 * @export
 */
export type CorporateActionEvent = { eventType: 'capital_gains_distribution_corporateaction_event' } & CorporateActionEventCapitalGainsDistribution | { eventType: 'cash_dividend_corporateaction_event' } & CorporateActionEventCashDividend | { eventType: 'cash_merger_corporateaction_event' } & CorporateActionEventCashMerger | { eventType: 'equity_partial_call_corporateaction_event' } & CorporateActionEventEquityPartialCall | { eventType: 'forward_split_corporateaction_event' } & CorporateActionEventForwardSplit | { eventType: 'name_change_corporateaction_event' } & CorporateActionEventNameChange | { eventType: 'redemption_corporateaction_event' } & CorporateActionEventRedemption | { eventType: 'reorganization_corporateaction_event' } & CorporateActionEventReorganization | { eventType: 'reverse_split_corporateaction_event' } & CorporateActionEventReverseSplit | { eventType: 'rights_distribution_corporateaction_event' } & CorporateActionEventRightsDistribution | { eventType: 'spin_off_corporateaction_event' } & CorporateActionEventSpinOff | { eventType: 'stock_and_cash_merger_corporateaction_event' } & CorporateActionEventStockAndCashMerger | { eventType: 'stock_dividend_corporateaction_event' } & CorporateActionEventStockDividend | { eventType: 'stock_merger_corporateaction_event' } & CorporateActionEventStockMerger | { eventType: 'unit_split_corporateaction_event' } & CorporateActionEventUnitSplit | { eventType: 'worthless_removal_corporateaction_event' } & CorporateActionEventWorthlessRemoval;

/**
 * Check if a given object implements one of the CorporateActionEvent variants.
 */
export function instanceOfCorporateActionEvent(value: object): value is CorporateActionEvent {
    switch ((value as Record<string, unknown>)['eventType']) {
        case 'capital_gains_distribution_corporateaction_event':
            return instanceOfCorporateActionEventCapitalGainsDistribution(value);
        case 'cash_dividend_corporateaction_event':
            return instanceOfCorporateActionEventCashDividend(value);
        case 'cash_merger_corporateaction_event':
            return instanceOfCorporateActionEventCashMerger(value);
        case 'equity_partial_call_corporateaction_event':
            return instanceOfCorporateActionEventEquityPartialCall(value);
        case 'forward_split_corporateaction_event':
            return instanceOfCorporateActionEventForwardSplit(value);
        case 'name_change_corporateaction_event':
            return instanceOfCorporateActionEventNameChange(value);
        case 'redemption_corporateaction_event':
            return instanceOfCorporateActionEventRedemption(value);
        case 'reorganization_corporateaction_event':
            return instanceOfCorporateActionEventReorganization(value);
        case 'reverse_split_corporateaction_event':
            return instanceOfCorporateActionEventReverseSplit(value);
        case 'rights_distribution_corporateaction_event':
            return instanceOfCorporateActionEventRightsDistribution(value);
        case 'spin_off_corporateaction_event':
            return instanceOfCorporateActionEventSpinOff(value);
        case 'stock_and_cash_merger_corporateaction_event':
            return instanceOfCorporateActionEventStockAndCashMerger(value);
        case 'stock_dividend_corporateaction_event':
            return instanceOfCorporateActionEventStockDividend(value);
        case 'stock_merger_corporateaction_event':
            return instanceOfCorporateActionEventStockMerger(value);
        case 'unit_split_corporateaction_event':
            return instanceOfCorporateActionEventUnitSplit(value);
        case 'worthless_removal_corporateaction_event':
            return instanceOfCorporateActionEventWorthlessRemoval(value);
        default:
            return false;
    }
}

export function CorporateActionEventFromJSON(json: any): CorporateActionEvent {
    return CorporateActionEventFromJSONTyped(json, false);
}

export function CorporateActionEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporateActionEvent {
    if (json == null) {
        return json;
    }
    switch (json['event_type']) {
        case 'capital_gains_distribution_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventCapitalGainsDistributionFromJSONTyped(json, true), { eventType: 'capital_gains_distribution_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventCapitalGainsDistribution(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "capital_gains_distribution_corporateaction_event"');
            }
            return value;
        }
        case 'cash_dividend_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventCashDividendFromJSONTyped(json, true), { eventType: 'cash_dividend_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventCashDividend(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "cash_dividend_corporateaction_event"');
            }
            return value;
        }
        case 'cash_merger_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventCashMergerFromJSONTyped(json, true), { eventType: 'cash_merger_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventCashMerger(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "cash_merger_corporateaction_event"');
            }
            return value;
        }
        case 'equity_partial_call_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventEquityPartialCallFromJSONTyped(json, true), { eventType: 'equity_partial_call_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventEquityPartialCall(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "equity_partial_call_corporateaction_event"');
            }
            return value;
        }
        case 'forward_split_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventForwardSplitFromJSONTyped(json, true), { eventType: 'forward_split_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventForwardSplit(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "forward_split_corporateaction_event"');
            }
            return value;
        }
        case 'name_change_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventNameChangeFromJSONTyped(json, true), { eventType: 'name_change_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventNameChange(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "name_change_corporateaction_event"');
            }
            return value;
        }
        case 'redemption_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventRedemptionFromJSONTyped(json, true), { eventType: 'redemption_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventRedemption(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "redemption_corporateaction_event"');
            }
            return value;
        }
        case 'reorganization_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventReorganizationFromJSONTyped(json, true), { eventType: 'reorganization_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventReorganization(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "reorganization_corporateaction_event"');
            }
            return value;
        }
        case 'reverse_split_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventReverseSplitFromJSONTyped(json, true), { eventType: 'reverse_split_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventReverseSplit(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "reverse_split_corporateaction_event"');
            }
            return value;
        }
        case 'rights_distribution_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventRightsDistributionFromJSONTyped(json, true), { eventType: 'rights_distribution_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventRightsDistribution(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "rights_distribution_corporateaction_event"');
            }
            return value;
        }
        case 'spin_off_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventSpinOffFromJSONTyped(json, true), { eventType: 'spin_off_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventSpinOff(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "spin_off_corporateaction_event"');
            }
            return value;
        }
        case 'stock_and_cash_merger_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventStockAndCashMergerFromJSONTyped(json, true), { eventType: 'stock_and_cash_merger_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventStockAndCashMerger(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "stock_and_cash_merger_corporateaction_event"');
            }
            return value;
        }
        case 'stock_dividend_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventStockDividendFromJSONTyped(json, true), { eventType: 'stock_dividend_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventStockDividend(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "stock_dividend_corporateaction_event"');
            }
            return value;
        }
        case 'stock_merger_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventStockMergerFromJSONTyped(json, true), { eventType: 'stock_merger_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventStockMerger(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "stock_merger_corporateaction_event"');
            }
            return value;
        }
        case 'unit_split_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventUnitSplitFromJSONTyped(json, true), { eventType: 'unit_split_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventUnitSplit(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "unit_split_corporateaction_event"');
            }
            return value;
        }
        case 'worthless_removal_corporateaction_event': {
            const value = Object.assign({}, CorporateActionEventWorthlessRemovalFromJSONTyped(json, true), { eventType: 'worthless_removal_corporateaction_event' } as const);
            if (!instanceOfCorporateActionEventWorthlessRemoval(value)) {
                throw new TypeError('Invalid CorporateActionEvent payload for discriminator "worthless_removal_corporateaction_event"');
            }
            return value;
        }
        default:
            throw new TypeError(`Unknown CorporateActionEvent discriminator value: ${String(json['event_type'])}`);
    }
}

export function CorporateActionEventToJSON(json: any): any {
    return CorporateActionEventToJSONTyped(json, false);
}

export function CorporateActionEventToJSONTyped(value?: CorporateActionEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['eventType']) {
        case 'capital_gains_distribution_corporateaction_event':
            return Object.assign({}, CorporateActionEventCapitalGainsDistributionToJSON(value), { 'event_type': 'capital_gains_distribution_corporateaction_event' } as const);
        case 'cash_dividend_corporateaction_event':
            return Object.assign({}, CorporateActionEventCashDividendToJSON(value), { 'event_type': 'cash_dividend_corporateaction_event' } as const);
        case 'cash_merger_corporateaction_event':
            return Object.assign({}, CorporateActionEventCashMergerToJSON(value), { 'event_type': 'cash_merger_corporateaction_event' } as const);
        case 'equity_partial_call_corporateaction_event':
            return Object.assign({}, CorporateActionEventEquityPartialCallToJSON(value), { 'event_type': 'equity_partial_call_corporateaction_event' } as const);
        case 'forward_split_corporateaction_event':
            return Object.assign({}, CorporateActionEventForwardSplitToJSON(value), { 'event_type': 'forward_split_corporateaction_event' } as const);
        case 'name_change_corporateaction_event':
            return Object.assign({}, CorporateActionEventNameChangeToJSON(value), { 'event_type': 'name_change_corporateaction_event' } as const);
        case 'redemption_corporateaction_event':
            return Object.assign({}, CorporateActionEventRedemptionToJSON(value), { 'event_type': 'redemption_corporateaction_event' } as const);
        case 'reorganization_corporateaction_event':
            return Object.assign({}, CorporateActionEventReorganizationToJSON(value), { 'event_type': 'reorganization_corporateaction_event' } as const);
        case 'reverse_split_corporateaction_event':
            return Object.assign({}, CorporateActionEventReverseSplitToJSON(value), { 'event_type': 'reverse_split_corporateaction_event' } as const);
        case 'rights_distribution_corporateaction_event':
            return Object.assign({}, CorporateActionEventRightsDistributionToJSON(value), { 'event_type': 'rights_distribution_corporateaction_event' } as const);
        case 'spin_off_corporateaction_event':
            return Object.assign({}, CorporateActionEventSpinOffToJSON(value), { 'event_type': 'spin_off_corporateaction_event' } as const);
        case 'stock_and_cash_merger_corporateaction_event':
            return Object.assign({}, CorporateActionEventStockAndCashMergerToJSON(value), { 'event_type': 'stock_and_cash_merger_corporateaction_event' } as const);
        case 'stock_dividend_corporateaction_event':
            return Object.assign({}, CorporateActionEventStockDividendToJSON(value), { 'event_type': 'stock_dividend_corporateaction_event' } as const);
        case 'stock_merger_corporateaction_event':
            return Object.assign({}, CorporateActionEventStockMergerToJSON(value), { 'event_type': 'stock_merger_corporateaction_event' } as const);
        case 'unit_split_corporateaction_event':
            return Object.assign({}, CorporateActionEventUnitSplitToJSON(value), { 'event_type': 'unit_split_corporateaction_event' } as const);
        case 'worthless_removal_corporateaction_event':
            return Object.assign({}, CorporateActionEventWorthlessRemovalToJSON(value), { 'event_type': 'worthless_removal_corporateaction_event' } as const);
        default:
            throw new TypeError(`Unknown CorporateActionEvent discriminator value: ${String((value as Record<string, unknown>)['eventType'])}`);
    }
}

