/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CryptoQuote } from './CryptoQuote';
import {
    CryptoQuoteFromJSON,
    CryptoQuoteFromJSONTyped,
    CryptoQuoteToJSON,
    CryptoQuoteToJSONTyped,
} from './CryptoQuote';

/**
 * 
 * @export
 * @interface CryptoQuotesResp
 */
export interface CryptoQuotesResp {
    /**
     * Pagination token for the next page.
     * @type {string}
     * @memberof CryptoQuotesResp
     */
    nextPageToken: string | null;
    /**
     * 
     * @type {{ [key: string]: Array<CryptoQuote>; }}
     * @memberof CryptoQuotesResp
     */
    quotes: { [key: string]: Array<CryptoQuote>; };
}

/**
 * Check if a given object implements the CryptoQuotesResp interface.
 */
export function instanceOfCryptoQuotesResp(value: object): value is CryptoQuotesResp {
    if (!('nextPageToken' in value) || value['nextPageToken'] === undefined) return false;
    if (!('quotes' in value) || value['quotes'] === undefined) return false;
    return true;
}

export function CryptoQuotesRespFromJSON(json: any): CryptoQuotesResp {
    return CryptoQuotesRespFromJSONTyped(json, false);
}

export function CryptoQuotesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoQuotesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['next_page_token'],
        'quotes': json['quotes'],
    };
}

export function CryptoQuotesRespToJSON(json: any): CryptoQuotesResp {
    return CryptoQuotesRespToJSONTyped(json, false);
}

export function CryptoQuotesRespToJSONTyped(value?: CryptoQuotesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_page_token': value['nextPageToken'],
        'quotes': value['quotes'],
    };
}

