/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Crypto perpetual location.
 * @export
 */
export const CryptoPerpLoc = {
    Global: 'global'
} as const;
export type CryptoPerpLoc = typeof CryptoPerpLoc[keyof typeof CryptoPerpLoc];


export function instanceOfCryptoPerpLoc(value: any): boolean {
    for (const key in CryptoPerpLoc) {
        if (Object.prototype.hasOwnProperty.call(CryptoPerpLoc, key)) {
            if (CryptoPerpLoc[key as keyof typeof CryptoPerpLoc] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CryptoPerpLocFromJSON(json: any): CryptoPerpLoc {
    return CryptoPerpLocFromJSONTyped(json, false);
}

export function CryptoPerpLocFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoPerpLoc {
    return json as CryptoPerpLoc;
}

export function CryptoPerpLocToJSON(value?: CryptoPerpLoc | null): any {
    return value as any;
}

export function CryptoPerpLocToJSONTyped(value: any, ignoreDiscriminator: boolean): CryptoPerpLoc {
    return value as CryptoPerpLoc;
}

