/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OHLC aggregate of all the trades in a given interval.
 * @export
 * @interface CryptoBar
 */
export interface CryptoBar {
    /**
     * Closing price.
     * @type {number}
     * @memberof CryptoBar
     */
    c: number;
    /**
     * High price.
     * @type {number}
     * @memberof CryptoBar
     */
    h: number;
    /**
     * Low price.
     * @type {number}
     * @memberof CryptoBar
     */
    l: number;
    /**
     * Trade count in the bar.
     * @type {number}
     * @memberof CryptoBar
     */
    n: number;
    /**
     * Opening price.
     * @type {number}
     * @memberof CryptoBar
     */
    o: number;
    /**
     * Timestamp in RFC-3339 format with nanosecond precision.
     * @type {Date}
     * @memberof CryptoBar
     */
    t: Date;
    /**
     * Bar volume.
     * @type {number}
     * @memberof CryptoBar
     */
    v: number;
    /**
     * Volume weighted average price.
     * @type {number}
     * @memberof CryptoBar
     */
    vw: number;
}

/**
 * Check if a given object implements the CryptoBar interface.
 */
export function instanceOfCryptoBar(value: object): value is CryptoBar {
    if (!('c' in value) || value['c'] === undefined) return false;
    if (!('h' in value) || value['h'] === undefined) return false;
    if (!('l' in value) || value['l'] === undefined) return false;
    if (!('n' in value) || value['n'] === undefined) return false;
    if (!('o' in value) || value['o'] === undefined) return false;
    if (!('t' in value) || value['t'] === undefined) return false;
    if (!('v' in value) || value['v'] === undefined) return false;
    if (!('vw' in value) || value['vw'] === undefined) return false;
    return true;
}

export function CryptoBarFromJSON(json: any): CryptoBar {
    return CryptoBarFromJSONTyped(json, false);
}

export function CryptoBarFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoBar {
    if (json == null) {
        return json;
    }
    return {
        
        'c': json['c'],
        'h': json['h'],
        'l': json['l'],
        'n': json['n'],
        'o': json['o'],
        't': (new Date(json['t'])),
        'v': json['v'],
        'vw': json['vw'],
    };
}

export function CryptoBarToJSON(json: any): CryptoBar {
    return CryptoBarToJSONTyped(json, false);
}

export function CryptoBarToJSONTyped(value?: CryptoBar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'c': value['c'],
        'h': value['h'],
        'l': value['l'],
        'n': value['n'],
        'o': value['o'],
        't': ((value['t']).toISOString()),
        'v': value['v'],
        'vw': value['vw'],
    };
}

