/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CryptoOrderbook } from './CryptoOrderbook';
import {
    CryptoOrderbookFromJSON,
    CryptoOrderbookFromJSONTyped,
    CryptoOrderbookToJSON,
    CryptoOrderbookToJSONTyped,
} from './CryptoOrderbook';

/**
 * 
 * @export
 * @interface CryptoLatestOrderbooksResp
 */
export interface CryptoLatestOrderbooksResp {
    /**
     * 
     * @type {{ [key: string]: CryptoOrderbook; }}
     * @memberof CryptoLatestOrderbooksResp
     */
    orderbooks: { [key: string]: CryptoOrderbook; };
}

/**
 * Check if a given object implements the CryptoLatestOrderbooksResp interface.
 */
export function instanceOfCryptoLatestOrderbooksResp(value: object): value is CryptoLatestOrderbooksResp {
    if (!('orderbooks' in value) || value['orderbooks'] === undefined) return false;
    return true;
}

export function CryptoLatestOrderbooksRespFromJSON(json: any): CryptoLatestOrderbooksResp {
    return CryptoLatestOrderbooksRespFromJSONTyped(json, false);
}

export function CryptoLatestOrderbooksRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoLatestOrderbooksResp {
    if (json == null) {
        return json;
    }
    return {
        
        'orderbooks': (mapValues(json['orderbooks'], CryptoOrderbookFromJSON)),
    };
}

export function CryptoLatestOrderbooksRespToJSON(json: any): CryptoLatestOrderbooksResp {
    return CryptoLatestOrderbooksRespToJSONTyped(json, false);
}

export function CryptoLatestOrderbooksRespToJSONTyped(value?: CryptoLatestOrderbooksResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderbooks': (mapValues(value['orderbooks'], CryptoOrderbookToJSON)),
    };
}

