/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Crypto location from where the latest market data is retrieved.
 * @export
 */
export const CryptoLatestLoc = {
    Us: 'us',
    Us1: 'us-1',
    Us2: 'us-2',
    Eu1: 'eu-1',
    Bs1: 'bs-1'
} as const;
export type CryptoLatestLoc = typeof CryptoLatestLoc[keyof typeof CryptoLatestLoc];


export function instanceOfCryptoLatestLoc(value: any): boolean {
    for (const key in CryptoLatestLoc) {
        if (Object.prototype.hasOwnProperty.call(CryptoLatestLoc, key)) {
            if (CryptoLatestLoc[key as keyof typeof CryptoLatestLoc] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CryptoLatestLocFromJSON(json: any): CryptoLatestLoc {
    return CryptoLatestLocFromJSONTyped(json, false);
}

export function CryptoLatestLocFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoLatestLoc {
    return json as CryptoLatestLoc;
}

export function CryptoLatestLocToJSON(value?: CryptoLatestLoc | null): any {
    return value as any;
}

export function CryptoLatestLocToJSONTyped(value: any, ignoreDiscriminator: boolean): CryptoLatestLoc {
    return value as CryptoLatestLoc;
}

