/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The best bid and ask information for a given fixed income security. A value of 0 means there is no active bid or ask for that field.
 * 
 * @export
 * @interface FixedIncomeQuote
 */
export interface FixedIncomeQuote {
    /**
     * Best ask minimum trade size in par value.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    ams: number;
    /**
     * Best ask price. 0 means there is no active ask.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    ap: number;
    /**
     * Best ask size in par value. 0 means there is no active ask.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    as: number;
    /**
     * Best ask yield to maturity.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    aytm: number;
    /**
     * Best ask yield to worst.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    aytw: number;
    /**
     * Best bid minimum trade size in par value.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    bms: number;
    /**
     * Best bid price. 0 means there is no active bid.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    bp: number;
    /**
     * Best bid size in par value. 0 means there is no active bid.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    bs: number;
    /**
     * Best bid yield to maturity.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    bytm: number;
    /**
     * Best bid yield to worst.
     * @type {number}
     * @memberof FixedIncomeQuote
     */
    bytw: number;
    /**
     * Timestamp in RFC-3339 format with nanosecond precision.
     * @type {Date}
     * @memberof FixedIncomeQuote
     */
    t: Date;
}

/**
 * Check if a given object implements the FixedIncomeQuote interface.
 */
export function instanceOfFixedIncomeQuote(value: object): value is FixedIncomeQuote {
    if (!('ams' in value) || value['ams'] === undefined) return false;
    if (!('ap' in value) || value['ap'] === undefined) return false;
    if (!('as' in value) || value['as'] === undefined) return false;
    if (!('aytm' in value) || value['aytm'] === undefined) return false;
    if (!('aytw' in value) || value['aytw'] === undefined) return false;
    if (!('bms' in value) || value['bms'] === undefined) return false;
    if (!('bp' in value) || value['bp'] === undefined) return false;
    if (!('bs' in value) || value['bs'] === undefined) return false;
    if (!('bytm' in value) || value['bytm'] === undefined) return false;
    if (!('bytw' in value) || value['bytw'] === undefined) return false;
    if (!('t' in value) || value['t'] === undefined) return false;
    return true;
}

export function FixedIncomeQuoteFromJSON(json: any): FixedIncomeQuote {
    return FixedIncomeQuoteFromJSONTyped(json, false);
}

export function FixedIncomeQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixedIncomeQuote {
    if (json == null) {
        return json;
    }
    return {
        
        'ams': json['ams'],
        'ap': json['ap'],
        'as': json['as'],
        'aytm': json['aytm'],
        'aytw': json['aytw'],
        'bms': json['bms'],
        'bp': json['bp'],
        'bs': json['bs'],
        'bytm': json['bytm'],
        'bytw': json['bytw'],
        't': (new Date(json['t'])),
    };
}

export function FixedIncomeQuoteToJSON(json: any): FixedIncomeQuote {
    return FixedIncomeQuoteToJSONTyped(json, false);
}

export function FixedIncomeQuoteToJSONTyped(value?: FixedIncomeQuote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ams': value['ams'],
        'ap': value['ap'],
        'as': value['as'],
        'aytm': value['aytm'],
        'aytw': value['aytw'],
        'bms': value['bms'],
        'bp': value['bp'],
        'bs': value['bs'],
        'bytm': value['bytm'],
        'bytw': value['bytw'],
        't': ((value['t']).toISOString()),
    };
}

