/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForexRate } from './ForexRate';
import {
    ForexRateFromJSON,
    ForexRateFromJSONTyped,
    ForexRateToJSON,
    ForexRateToJSONTyped,
} from './ForexRate';

/**
 * The response object of the latest forex rates.
 * @export
 * @interface ForexLatestRatesResp
 */
export interface ForexLatestRatesResp {
    /**
     * 
     * @type {{ [key: string]: ForexRate; }}
     * @memberof ForexLatestRatesResp
     */
    rates: { [key: string]: ForexRate; };
}

/**
 * Check if a given object implements the ForexLatestRatesResp interface.
 */
export function instanceOfForexLatestRatesResp(value: object): value is ForexLatestRatesResp {
    if (!('rates' in value) || value['rates'] === undefined) return false;
    return true;
}

export function ForexLatestRatesRespFromJSON(json: any): ForexLatestRatesResp {
    return ForexLatestRatesRespFromJSONTyped(json, false);
}

export function ForexLatestRatesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForexLatestRatesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'rates': (mapValues(json['rates'], ForexRateFromJSON)),
    };
}

export function ForexLatestRatesRespToJSON(json: any): ForexLatestRatesResp {
    return ForexLatestRatesRespToJSONTyped(json, false);
}

export function ForexLatestRatesRespToJSONTyped(value?: ForexLatestRatesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rates': (mapValues(value['rates'], ForexRateToJSON)),
    };
}

