/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MostActive } from './MostActive';
import {
    MostActiveFromJSON,
    MostActiveFromJSONTyped,
    MostActiveToJSON,
    MostActiveToJSONTyped,
} from './MostActive';

/**
 * 
 * @export
 * @interface MostActivesResp
 */
export interface MostActivesResp {
    /**
     * Time when the most actives were last computed. Formatted as a RFC-3339 date-time with nanosecond precision.
     * 
     * @type {string}
     * @memberof MostActivesResp
     */
    lastUpdated: string;
    /**
     * List of top N most active symbols.
     * @type {Array<MostActive>}
     * @memberof MostActivesResp
     */
    mostActives: Array<MostActive>;
}

/**
 * Check if a given object implements the MostActivesResp interface.
 */
export function instanceOfMostActivesResp(value: object): value is MostActivesResp {
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('mostActives' in value) || value['mostActives'] === undefined) return false;
    return true;
}

export function MostActivesRespFromJSON(json: any): MostActivesResp {
    return MostActivesRespFromJSONTyped(json, false);
}

export function MostActivesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): MostActivesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'lastUpdated': json['last_updated'],
        'mostActives': (json['most_actives'] == null ? [] : (json['most_actives'] as Array<any>).map(MostActiveFromJSON)),
    };
}

export function MostActivesRespToJSON(json: any): MostActivesResp {
    return MostActivesRespToJSONTyped(json, false);
}

export function MostActivesRespToJSONTyped(value?: MostActivesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_updated': value['lastUpdated'],
        'most_actives': ((value['mostActives'] as Array<any>).map(MostActiveToJSON)),
    };
}

