/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A model representing images for a news article. Simply a URL to the image along with a size parameter suggesting the display size of the image.
 * @export
 * @interface NewsImage
 */
export interface NewsImage {
    /**
     * Possible values for size are thumb, small and large.
     * @type {string}
     * @memberof NewsImage
     */
    size: NewsImageSizeEnum;
    /**
     * URL to image from news article.
     * @type {string}
     * @memberof NewsImage
     */
    url: string;
}


/**
 * @export
 */
export const NewsImageSizeEnum = {
    Thumb: 'thumb',
    Small: 'small',
    Large: 'large'
} as const;
export type NewsImageSizeEnum = typeof NewsImageSizeEnum[keyof typeof NewsImageSizeEnum];


/**
 * Check if a given object implements the NewsImage interface.
 */
export function instanceOfNewsImage(value: object): value is NewsImage {
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NewsImageFromJSON(json: any): NewsImage {
    return NewsImageFromJSONTyped(json, false);
}

export function NewsImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsImage {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'],
        'url': json['url'],
    };
}

export function NewsImageToJSON(json: any): NewsImage {
    return NewsImageToJSONTyped(json, false);
}

export function NewsImageToJSONTyped(value?: NewsImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'url': value['url'],
    };
}

