/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OptionFeed = {
    Opra: 'opra',
    Indicative: 'indicative'
} as const;
export type OptionFeed = typeof OptionFeed[keyof typeof OptionFeed];


export function instanceOfOptionFeed(value: any): boolean {
    for (const key in OptionFeed) {
        if (Object.prototype.hasOwnProperty.call(OptionFeed, key)) {
            if (OptionFeed[key as keyof typeof OptionFeed] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OptionFeedFromJSON(json: any): OptionFeed {
    return OptionFeedFromJSONTyped(json, false);
}

export function OptionFeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionFeed {
    return json as OptionFeed;
}

export function OptionFeedToJSON(value?: OptionFeed | null): any {
    return value as any;
}

export function OptionFeedToJSONTyped(value: any, ignoreDiscriminator: boolean): OptionFeed {
    return value as OptionFeed;
}

