/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptionQuote } from './OptionQuote';
import {
    OptionQuoteFromJSON,
    OptionQuoteFromJSONTyped,
    OptionQuoteToJSON,
    OptionQuoteToJSONTyped,
} from './OptionQuote';

/**
 * 
 * @export
 * @interface OptionLatestQuotesResp
 */
export interface OptionLatestQuotesResp {
    /**
     * 
     * @type {{ [key: string]: OptionQuote; }}
     * @memberof OptionLatestQuotesResp
     */
    quotes: { [key: string]: OptionQuote; };
}

/**
 * Check if a given object implements the OptionLatestQuotesResp interface.
 */
export function instanceOfOptionLatestQuotesResp(value: object): value is OptionLatestQuotesResp {
    if (!('quotes' in value) || value['quotes'] === undefined) return false;
    return true;
}

export function OptionLatestQuotesRespFromJSON(json: any): OptionLatestQuotesResp {
    return OptionLatestQuotesRespFromJSONTyped(json, false);
}

export function OptionLatestQuotesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionLatestQuotesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'quotes': (mapValues(json['quotes'], OptionQuoteFromJSON)),
    };
}

export function OptionLatestQuotesRespToJSON(json: any): OptionLatestQuotesResp {
    return OptionLatestQuotesRespToJSONTyped(json, false);
}

export function OptionLatestQuotesRespToJSONTyped(value?: OptionLatestQuotesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quotes': (mapValues(value['quotes'], OptionQuoteToJSON)),
    };
}

