/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OHLC aggregate of all the trades in a given interval.
 * @export
 * @interface OptionBar
 */
export interface OptionBar {
    /**
     * Closing price.
     * @type {number}
     * @memberof OptionBar
     */
    c: number;
    /**
     * High price.
     * @type {number}
     * @memberof OptionBar
     */
    h: number;
    /**
     * Low price.
     * @type {number}
     * @memberof OptionBar
     */
    l: number;
    /**
     * Trade count in the bar.
     * @type {number}
     * @memberof OptionBar
     */
    n: number;
    /**
     * Opening price.
     * @type {number}
     * @memberof OptionBar
     */
    o: number;
    /**
     * Timestamp in RFC-3339 format with nanosecond precision.
     * @type {Date}
     * @memberof OptionBar
     */
    t: Date;
    /**
     * Bar volume.
     * @type {number}
     * @memberof OptionBar
     */
    v: number;
    /**
     * Volume weighted average price.
     * @type {number}
     * @memberof OptionBar
     */
    vw: number;
}

/**
 * Check if a given object implements the OptionBar interface.
 */
export function instanceOfOptionBar(value: object): value is OptionBar {
    if (!('c' in value) || value['c'] === undefined) return false;
    if (!('h' in value) || value['h'] === undefined) return false;
    if (!('l' in value) || value['l'] === undefined) return false;
    if (!('n' in value) || value['n'] === undefined) return false;
    if (!('o' in value) || value['o'] === undefined) return false;
    if (!('t' in value) || value['t'] === undefined) return false;
    if (!('v' in value) || value['v'] === undefined) return false;
    if (!('vw' in value) || value['vw'] === undefined) return false;
    return true;
}

export function OptionBarFromJSON(json: any): OptionBar {
    return OptionBarFromJSONTyped(json, false);
}

export function OptionBarFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionBar {
    if (json == null) {
        return json;
    }
    return {
        
        'c': json['c'],
        'h': json['h'],
        'l': json['l'],
        'n': json['n'],
        'o': json['o'],
        't': (new Date(json['t'])),
        'v': json['v'],
        'vw': json['vw'],
    };
}

export function OptionBarToJSON(json: any): OptionBar {
    return OptionBarToJSONTyped(json, false);
}

export function OptionBarToJSONTyped(value?: OptionBar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'c': value['c'],
        'h': value['h'],
        'l': value['l'],
        'n': value['n'],
        'o': value['o'],
        't': ((value['t']).toISOString()),
        'v': value['v'],
        'vw': value['vw'],
    };
}

