/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptionSnapshot } from './OptionSnapshot';
import {
    OptionSnapshotFromJSON,
    OptionSnapshotFromJSONTyped,
    OptionSnapshotToJSON,
    OptionSnapshotToJSONTyped,
} from './OptionSnapshot';

/**
 * 
 * @export
 * @interface OptionSnapshotsResp
 */
export interface OptionSnapshotsResp {
    /**
     * Pagination token for the next page.
     * @type {string}
     * @memberof OptionSnapshotsResp
     */
    nextPageToken: string | null;
    /**
     * 
     * @type {{ [key: string]: OptionSnapshot; }}
     * @memberof OptionSnapshotsResp
     */
    snapshots: { [key: string]: OptionSnapshot; };
}

/**
 * Check if a given object implements the OptionSnapshotsResp interface.
 */
export function instanceOfOptionSnapshotsResp(value: object): value is OptionSnapshotsResp {
    if (!('nextPageToken' in value) || value['nextPageToken'] === undefined) return false;
    if (!('snapshots' in value) || value['snapshots'] === undefined) return false;
    return true;
}

export function OptionSnapshotsRespFromJSON(json: any): OptionSnapshotsResp {
    return OptionSnapshotsRespFromJSONTyped(json, false);
}

export function OptionSnapshotsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionSnapshotsResp {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['next_page_token'],
        'snapshots': (mapValues(json['snapshots'], OptionSnapshotFromJSON)),
    };
}

export function OptionSnapshotsRespToJSON(json: any): OptionSnapshotsResp {
    return OptionSnapshotsRespToJSONTyped(json, false);
}

export function OptionSnapshotsRespToJSONTyped(value?: OptionSnapshotsResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_page_token': value['nextPageToken'],
        'snapshots': (mapValues(value['snapshots'], OptionSnapshotToJSON)),
    };
}

