/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptionTrade } from './OptionTrade';
import {
    OptionTradeFromJSON,
    OptionTradeFromJSONTyped,
    OptionTradeToJSON,
    OptionTradeToJSONTyped,
} from './OptionTrade';

/**
 * 
 * @export
 * @interface OptionTradesResp
 */
export interface OptionTradesResp {
    /**
     * 
     * @type {string}
     * @memberof OptionTradesResp
     */
    currency?: string;
    /**
     * Pagination token for the next page.
     * @type {string}
     * @memberof OptionTradesResp
     */
    nextPageToken: string | null;
    /**
     * 
     * @type {{ [key: string]: Array<OptionTrade>; }}
     * @memberof OptionTradesResp
     */
    trades: { [key: string]: Array<OptionTrade>; };
}

/**
 * Check if a given object implements the OptionTradesResp interface.
 */
export function instanceOfOptionTradesResp(value: object): value is OptionTradesResp {
    if (!('nextPageToken' in value) || value['nextPageToken'] === undefined) return false;
    if (!('trades' in value) || value['trades'] === undefined) return false;
    return true;
}

export function OptionTradesRespFromJSON(json: any): OptionTradesResp {
    return OptionTradesRespFromJSONTyped(json, false);
}

export function OptionTradesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionTradesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'nextPageToken': json['next_page_token'],
        'trades': json['trades'],
    };
}

export function OptionTradesRespToJSON(json: any): OptionTradesResp {
    return OptionTradesRespToJSONTyped(json, false);
}

export function OptionTradesRespToJSONTyped(value?: OptionTradesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'next_page_token': value['nextPageToken'],
        'trades': value['trades'],
    };
}

