/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Partial call.
 * @export
 * @interface PartialCall
 */
export interface PartialCall {
    /**
     * The ISO 4217 currency code associated with the corporate action.
     * Empty value can mean USD, non-applicable (e.g. for name changes) or unknown
     * (can change later to a valid currency).
     * 
     * @type {string}
     * @memberof PartialCall
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialCall
     */
    cusip?: string;
    /**
     * 
     * @type {number}
     * @memberof PartialCall
     */
    dividendRate?: number;
    /**
     * The internal Alpaca identifier of the corporate action.
     * @type {string}
     * @memberof PartialCall
     */
    id: string;
    /**
     * International Securities Identification Number (ISIN) as defined by ISO 6166.
     * May be empty for US corporate actions.
     * 
     * @type {string}
     * @memberof PartialCall
     */
    isin?: string;
    /**
     * 
     * @type {Date}
     * @memberof PartialCall
     */
    lotteryDate?: Date;
    /**
     * The type of lottery for the partial call.
     * @type {string}
     * @memberof PartialCall
     */
    lotteryType?: PartialCallLotteryTypeEnum;
    /**
     * The date when the corporate action benefit is paid or distributed.
     * @type {Date}
     * @memberof PartialCall
     */
    payableDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof PartialCall
     */
    price?: number;
    /**
     * The date when the corporate action is processed by Alpaca.
     * @type {Date}
     * @memberof PartialCall
     */
    processDate: Date;
    /**
     * The date shareholders must own shares to receive the benefit.
     * @type {Date}
     * @memberof PartialCall
     */
    recordDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PartialCall
     */
    resultsPublicationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PartialCall
     */
    symbol: string;
}


/**
 * @export
 */
export const PartialCallLotteryTypeEnum = {
    Original: 'original',
    Supplemental: 'supplemental'
} as const;
export type PartialCallLotteryTypeEnum = typeof PartialCallLotteryTypeEnum[keyof typeof PartialCallLotteryTypeEnum];


/**
 * Check if a given object implements the PartialCall interface.
 */
export function instanceOfPartialCall(value: object): value is PartialCall {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('processDate' in value) || value['processDate'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function PartialCallFromJSON(json: any): PartialCall {
    return PartialCallFromJSONTyped(json, false);
}

export function PartialCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialCall {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'cusip': json['cusip'] == null ? undefined : json['cusip'],
        'dividendRate': json['dividend_rate'] == null ? undefined : json['dividend_rate'],
        'id': json['id'],
        'isin': json['isin'] == null ? undefined : json['isin'],
        'lotteryDate': json['lottery_date'] == null ? undefined : (new Date(json['lottery_date'])),
        'lotteryType': json['lottery_type'] == null ? undefined : json['lottery_type'],
        'payableDate': json['payable_date'] == null ? undefined : (new Date(json['payable_date'])),
        'price': json['price'] == null ? undefined : json['price'],
        'processDate': (new Date(json['process_date'])),
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'resultsPublicationDate': json['results_publication_date'] == null ? undefined : (new Date(json['results_publication_date'])),
        'symbol': json['symbol'],
    };
}

export function PartialCallToJSON(json: any): PartialCall {
    return PartialCallToJSONTyped(json, false);
}

export function PartialCallToJSONTyped(value?: PartialCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'cusip': value['cusip'],
        'dividend_rate': value['dividendRate'],
        'id': value['id'],
        'isin': value['isin'],
        'lottery_date': value['lotteryDate'] == null ? undefined : ((value['lotteryDate']).toISOString().substring(0,10)),
        'lottery_type': value['lotteryType'],
        'payable_date': value['payableDate'] == null ? undefined : ((value['payableDate']).toISOString().substring(0,10)),
        'price': value['price'],
        'process_date': ((value['processDate']).toISOString().substring(0,10)),
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'results_publication_date': value['resultsPublicationDate'] == null ? undefined : ((value['resultsPublicationDate']).toISOString().substring(0,10)),
        'symbol': value['symbol'],
    };
}

