/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The region to filter corporate actions by.
 * 
 * - `us`: only US corporate actions
 * - `non_us`: only non-US corporate actions
 * - `all`: both US and non-US corporate actions
 * 
 * @export
 */
export const Region = {
    Us: 'us',
    NonUs: 'non_us',
    All: 'all'
} as const;
export type Region = typeof Region[keyof typeof Region];


export function instanceOfRegion(value: any): boolean {
    for (const key in Region) {
        if (Object.prototype.hasOwnProperty.call(Region, key)) {
            if (Region[key as keyof typeof Region] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RegionFromJSON(json: any): Region {
    return RegionFromJSONTyped(json, false);
}

export function RegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Region {
    return json as Region;
}

export function RegionToJSON(value?: Region | null): any {
    return value as any;
}

export function RegionToJSONTyped(value: any, ignoreDiscriminator: boolean): Region {
    return value as Region;
}

