/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rights distribution.
 * @export
 * @interface RightsDistribution
 */
export interface RightsDistribution {
    /**
     * The ISO 4217 currency code associated with the corporate action.
     * Empty value can mean USD, non-applicable (e.g. for name changes) or unknown
     * (can change later to a valid currency).
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    currency?: string;
    /**
     * The ex-date marks the cutoff point for shareholders to be credited.
     * @type {Date}
     * @memberof RightsDistribution
     */
    exDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof RightsDistribution
     */
    expirationDate?: Date;
    /**
     * The internal Alpaca identifier of the corporate action.
     * @type {string}
     * @memberof RightsDistribution
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    newCusip: string;
    /**
     * International Securities Identification Number (ISIN) as defined by ISO 6166.
     * May be empty for US corporate actions.
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    newIsin?: string;
    /**
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    newSymbol: string;
    /**
     * The date when the corporate action benefit is paid or distributed.
     * @type {Date}
     * @memberof RightsDistribution
     */
    payableDate: Date;
    /**
     * The date when the corporate action is processed by Alpaca.
     * @type {Date}
     * @memberof RightsDistribution
     */
    processDate: Date;
    /**
     * 
     * @type {number}
     * @memberof RightsDistribution
     */
    rate: number;
    /**
     * The date shareholders must own shares to receive the benefit.
     * @type {Date}
     * @memberof RightsDistribution
     */
    recordDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    sourceCusip: string;
    /**
     * International Securities Identification Number (ISIN) as defined by ISO 6166.
     * May be empty for US corporate actions.
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    sourceIsin?: string;
    /**
     * 
     * @type {string}
     * @memberof RightsDistribution
     */
    sourceSymbol: string;
}

/**
 * Check if a given object implements the RightsDistribution interface.
 */
export function instanceOfRightsDistribution(value: object): value is RightsDistribution {
    if (!('exDate' in value) || value['exDate'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('newCusip' in value) || value['newCusip'] === undefined) return false;
    if (!('newSymbol' in value) || value['newSymbol'] === undefined) return false;
    if (!('payableDate' in value) || value['payableDate'] === undefined) return false;
    if (!('processDate' in value) || value['processDate'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('sourceCusip' in value) || value['sourceCusip'] === undefined) return false;
    if (!('sourceSymbol' in value) || value['sourceSymbol'] === undefined) return false;
    return true;
}

export function RightsDistributionFromJSON(json: any): RightsDistribution {
    return RightsDistributionFromJSONTyped(json, false);
}

export function RightsDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightsDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'exDate': (new Date(json['ex_date'])),
        'expirationDate': json['expiration_date'] == null ? undefined : (new Date(json['expiration_date'])),
        'id': json['id'],
        'newCusip': json['new_cusip'],
        'newIsin': json['new_isin'] == null ? undefined : json['new_isin'],
        'newSymbol': json['new_symbol'],
        'payableDate': (new Date(json['payable_date'])),
        'processDate': (new Date(json['process_date'])),
        'rate': json['rate'],
        'recordDate': json['record_date'] == null ? undefined : (new Date(json['record_date'])),
        'sourceCusip': json['source_cusip'],
        'sourceIsin': json['source_isin'] == null ? undefined : json['source_isin'],
        'sourceSymbol': json['source_symbol'],
    };
}

export function RightsDistributionToJSON(json: any): RightsDistribution {
    return RightsDistributionToJSONTyped(json, false);
}

export function RightsDistributionToJSONTyped(value?: RightsDistribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'ex_date': ((value['exDate']).toISOString().substring(0,10)),
        'expiration_date': value['expirationDate'] == null ? undefined : ((value['expirationDate']).toISOString().substring(0,10)),
        'id': value['id'],
        'new_cusip': value['newCusip'],
        'new_isin': value['newIsin'],
        'new_symbol': value['newSymbol'],
        'payable_date': ((value['payableDate']).toISOString().substring(0,10)),
        'process_date': ((value['processDate']).toISOString().substring(0,10)),
        'rate': value['rate'],
        'record_date': value['recordDate'] == null ? undefined : ((value['recordDate']).toISOString().substring(0,10)),
        'source_cusip': value['sourceCusip'],
        'source_isin': value['sourceIsin'],
        'source_symbol': value['sourceSymbol'],
    };
}

