/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sort data in ascending or descending order.
 * @export
 */
export const Sort = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type Sort = typeof Sort[keyof typeof Sort];


export function instanceOfSort(value: any): boolean {
    for (const key in Sort) {
        if (Object.prototype.hasOwnProperty.call(Sort, key)) {
            if (Sort[key as keyof typeof Sort] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortFromJSON(json: any): Sort {
    return SortFromJSONTyped(json, false);
}

export function SortFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sort {
    return json as Sort;
}

export function SortToJSON(value?: Sort | null): any {
    return value as any;
}

export function SortToJSONTyped(value: any, ignoreDiscriminator: boolean): Sort {
    return value as Sort;
}

