/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockTrade } from './StockTrade';
import {
    StockTradeFromJSON,
    StockTradeFromJSONTyped,
    StockTradeToJSON,
    StockTradeToJSONTyped,
} from './StockTrade';

/**
 * 
 * @export
 * @interface StockTradesResp
 */
export interface StockTradesResp {
    /**
     * 
     * @type {string}
     * @memberof StockTradesResp
     */
    currency?: string;
    /**
     * Pagination token for the next page.
     * @type {string}
     * @memberof StockTradesResp
     */
    nextPageToken: string | null;
    /**
     * 
     * @type {{ [key: string]: Array<StockTrade>; }}
     * @memberof StockTradesResp
     */
    trades: { [key: string]: Array<StockTrade>; };
}

/**
 * Check if a given object implements the StockTradesResp interface.
 */
export function instanceOfStockTradesResp(value: object): value is StockTradesResp {
    if (!('nextPageToken' in value) || value['nextPageToken'] === undefined) return false;
    if (!('trades' in value) || value['trades'] === undefined) return false;
    return true;
}

export function StockTradesRespFromJSON(json: any): StockTradesResp {
    return StockTradesRespFromJSONTyped(json, false);
}

export function StockTradesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockTradesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'nextPageToken': json['next_page_token'],
        'trades': json['trades'],
    };
}

export function StockTradesRespToJSON(json: any): StockTradesResp {
    return StockTradesRespToJSONTyped(json, false);
}

export function StockTradesRespToJSONTyped(value?: StockTradesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'next_page_token': value['nextPageToken'],
        'trades': value['trades'],
    };
}

