/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockQuote } from './StockQuote';
import {
    StockQuoteFromJSON,
    StockQuoteFromJSONTyped,
    StockQuoteToJSON,
    StockQuoteToJSONTyped,
} from './StockQuote';

/**
 * 
 * @export
 * @interface StockLatestQuotesRespSingle
 */
export interface StockLatestQuotesRespSingle {
    /**
     * 
     * @type {string}
     * @memberof StockLatestQuotesRespSingle
     */
    currency?: string;
    /**
     * 
     * @type {StockQuote}
     * @memberof StockLatestQuotesRespSingle
     */
    quote: StockQuote;
    /**
     * 
     * @type {string}
     * @memberof StockLatestQuotesRespSingle
     */
    symbol: string;
}

/**
 * Check if a given object implements the StockLatestQuotesRespSingle interface.
 */
export function instanceOfStockLatestQuotesRespSingle(value: object): value is StockLatestQuotesRespSingle {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function StockLatestQuotesRespSingleFromJSON(json: any): StockLatestQuotesRespSingle {
    return StockLatestQuotesRespSingleFromJSONTyped(json, false);
}

export function StockLatestQuotesRespSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockLatestQuotesRespSingle {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'quote': StockQuoteFromJSON(json['quote']),
        'symbol': json['symbol'],
    };
}

export function StockLatestQuotesRespSingleToJSON(json: any): StockLatestQuotesRespSingle {
    return StockLatestQuotesRespSingleToJSONTyped(json, false);
}

export function StockLatestQuotesRespSingleToJSONTyped(value?: StockLatestQuotesRespSingle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'quote': StockQuoteToJSON(value['quote']),
        'symbol': value['symbol'],
    };
}

