/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - A: New York Stock Exchange
 * - B: NYSE Arca, Bats, IEX and other regional exchanges
 * - C: NASDAQ
 * - N: Overnight
 * - O: OTC
 * 
 * @export
 */
export const StockTape = {
    A: 'A',
    B: 'B',
    C: 'C',
    N: 'N',
    O: 'O'
} as const;
export type StockTape = typeof StockTape[keyof typeof StockTape];


export function instanceOfStockTape(value: any): boolean {
    for (const key in StockTape) {
        if (Object.prototype.hasOwnProperty.call(StockTape, key)) {
            if (StockTape[key as keyof typeof StockTape] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StockTapeFromJSON(json: any): StockTape {
    return StockTapeFromJSONTyped(json, false);
}

export function StockTapeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockTape {
    return json as StockTape;
}

export function StockTapeToJSON(value?: StockTape | null): any {
    return value as any;
}

export function StockTapeToJSONTyped(value: any, ignoreDiscriminator: boolean): StockTape {
    return value as StockTape;
}

