/* tslint:disable */
/* eslint-disable */
/**
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockTape } from './StockTape';
import {
    StockTapeFromJSON,
    StockTapeFromJSONTyped,
    StockTapeToJSON,
    StockTapeToJSONTyped,
} from './StockTape';

/**
 * A stock trade.
 * @export
 * @interface StockTrade
 */
export interface StockTrade {
    /**
     * Condition flags. See `v2/stocks/meta/conditions/trade` for more details.
     * @type {Array<string>}
     * @memberof StockTrade
     */
    c: Array<string>;
    /**
     * Trade ID sent by the exchange.
     * @type {number}
     * @memberof StockTrade
     */
    i: number;
    /**
     * Trade price.
     * @type {number}
     * @memberof StockTrade
     */
    p: number;
    /**
     * Trade size.
     * @type {number}
     * @memberof StockTrade
     */
    s: number;
    /**
     * Timestamp in RFC-3339 format with nanosecond precision.
     * @type {Date}
     * @memberof StockTrade
     */
    t: Date;
    /**
     * Update to the trade. This field is optional, if it's missing, the trade is valid. Otherwise, it can have these values:
     *  - canceled: indicates that the trade has been canceled
     *  - incorrect: indicates that the trade has been corrected and the given trade is no longer valid
     *  - corrected: indicates that this trade is the correction of a previous (incorrect) trade
     * 
     * @type {string}
     * @memberof StockTrade
     */
    u?: string;
    /**
     * Exchange code. See `v2/stocks/meta/exchanges` for more details.
     * @type {string}
     * @memberof StockTrade
     */
    x: string;
    /**
     * 
     * @type {StockTape}
     * @memberof StockTrade
     */
    z: StockTape;
}



/**
 * Check if a given object implements the StockTrade interface.
 */
export function instanceOfStockTrade(value: object): value is StockTrade {
    if (!('c' in value) || value['c'] === undefined) return false;
    if (!('i' in value) || value['i'] === undefined) return false;
    if (!('p' in value) || value['p'] === undefined) return false;
    if (!('s' in value) || value['s'] === undefined) return false;
    if (!('t' in value) || value['t'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('z' in value) || value['z'] === undefined) return false;
    return true;
}

export function StockTradeFromJSON(json: any): StockTrade {
    return StockTradeFromJSONTyped(json, false);
}

export function StockTradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockTrade {
    if (json == null) {
        return json;
    }
    return {
        
        'c': json['c'],
        'i': json['i'],
        'p': json['p'],
        's': json['s'],
        't': (new Date(json['t'])),
        'u': json['u'] == null ? undefined : json['u'],
        'x': json['x'],
        'z': StockTapeFromJSON(json['z']),
    };
}

export function StockTradeToJSON(json: any): StockTrade {
    return StockTradeToJSONTyped(json, false);
}

export function StockTradeToJSONTyped(value?: StockTrade | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'c': value['c'],
        'i': value['i'],
        'p': value['p'],
        's': value['s'],
        't': ((value['t']).toISOString()),
        'u': value['u'],
        'x': value['x'],
        'z': StockTapeToJSON(value['z']),
    };
}

