/**
 * Deterministically derives docs-site migration pages from their canonical
 * root Markdown sources. Repository-relative links are rewritten because the
 * generated pages live under docs/docs; anchors and external links stay intact.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPOSITORY_BLOB = "https://github.com/alpacahq/alpaca-trade-api-js/blob/master";
const LINK_REWRITES: Record<string, string> = {
    "codemods/alpaca-v3-to-v4.js": `${REPOSITORY_BLOB}/codemods/alpaca-v3-to-v4.js`,
    "codemods/alpaca-v4-to-v5.js": `${REPOSITORY_BLOB}/codemods/alpaca-v4-to-v5.js`,
    "codemods/README.md": `${REPOSITORY_BLOB}/codemods/README.md`,
    "MIGRATION.md": "./migration.md",
    "MIGRATION_V5.md": "./migration-v5.md",
    "MIGRATIONS.md": "./migrations.md",
};

export type MigrationPage = {
    sourceFile: string;
    outputFile: string;
    title: string;
    sidebarPosition: number;
    primary: boolean;
};

export const migrationPages: readonly MigrationPage[] = [
    {
        sourceFile: "MIGRATIONS.md",
        outputFile: "migrations.md",
        title: "Migration overview",
        sidebarPosition: 1,
        primary: false,
    },
    {
        sourceFile: "MIGRATION.md",
        outputFile: "migration.md",
        title: "Migrate from 3.x",
        sidebarPosition: 2,
        primary: true,
    },
    {
        sourceFile: "MIGRATION_V5.md",
        outputFile: "migration-v5.md",
        title: "Migrate from 4.x to 5.0",
        sidebarPosition: 3,
        primary: false,
    },
] as const;

export function renderDocsMigration(source: string): string {
    return renderDocsMigrationPage(source, migrationPages[1]);
}

export function renderDocsV5Migration(source: string): string {
    return renderDocsMigrationPage(source, migrationPages[2]);
}

export function renderDocsMigrationIndex(source: string): string {
    return renderDocsMigrationPage(source, migrationPages[0]);
}

export function renderDocsMigrationPage(
    source: string,
    page: MigrationPage,
): string {
    const targets = Object.keys(LINK_REWRITES)
        .map((target) => target.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
        .join("|");
    const body = source.replace(
        new RegExp(`\\]\\((${targets})\\)`, "g"),
        (_match, target: string) => `](${LINK_REWRITES[target]})`,
    );

    return [
        "---",
        `sidebar_position: ${page.sidebarPosition}`,
        `title: ${page.title}`,
        "custom_edit_url: null",
        "---",
        "",
        `<!-- Generated by scripts/gen-docs-migration.ts from ${page.sourceFile} — do not edit by hand. -->`,
        "",
        body.trimEnd(),
        "",
    ].join("\n");
}

function main(): void {
    const here = dirname(fileURLToPath(import.meta.url));
    const root = resolve(here, "..");
    for (const page of migrationPages) {
        const input = resolve(root, page.sourceFile);
        const output = resolve(root, "docs", "docs", page.outputFile);
        writeFileSync(
            output,
            renderDocsMigrationPage(readFileSync(input, "utf8"), page),
        );
        console.log(`Wrote ${page.title.toLowerCase()} to ${output}`);
    }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main();
}
