/**
 * Writer for the docs-site Examples page.
 *
 * Reads the runnable examples in `examples/*.ts` *live* and emits a single
 * Docusaurus page (`docs/docs/examples.md`) that embeds their current source,
 * so the documented code can never drift from what's in the repo. The example
 * files are themselves type-checked against the SDK source (`npm run typecheck`
 * via `tsconfig.examples.json`), so this page always shows compiling code.
 *
 * Each example's leading block comment becomes the page prose (its `Run:`
 * section is rendered as a runnable command block), followed by the file's
 * source. The output is gitignored and treated as a build artifact: the docs
 * `prestart`/`prebuild` runs this before every `docusaurus start`/`build`, and
 * the root `npm run docs:examples-site` regenerates it on demand.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const examplesDir = resolve(here, "..", "examples");
const outFile = resolve(here, "..", "docs", "docs", "examples.md");

const GITHUB_BLOB = "https://github.com/alpacahq/alpaca-trade-api-js/blob/ts-alpha/examples";

/** Ordered list of example files to surface (matches `examples/README.md`). */
const EXAMPLES = ["trading-bot.ts", "marketdata-backend.ts"];

interface ParsedExample {
    /** Prose description (the leading block comment, minus its `Run:` section). */
    description: string;
    /** Shell commands from the comment's `Run:` section. */
    run: string[];
    /** File source with the leading block comment stripped (it became prose). */
    code: string;
}

/** Strip a JSDoc/block-comment line's ` * ` decoration. */
function undecorate(line: string): string {
    return line.replace(/^\s*\*?\s?/, "").replace(/\s+$/, "");
}

function parseExample(source: string): ParsedExample {
    const commentMatch = source.match(/^\s*\/\*\*([\s\S]*?)\*\//);
    const code = source.replace(/^\s*\/\*\*[\s\S]*?\*\/\n?/, "").trimStart();
    if (!commentMatch) {
        return { description: "", run: [], code };
    }

    const lines = commentMatch[1].split("\n").map(undecorate);
    const runIdx = lines.findIndex((l) => l.trim() === "Run:");
    const descLines = runIdx === -1 ? lines : lines.slice(0, runIdx);
    const runLines =
        runIdx === -1 ? [] : lines.slice(runIdx + 1).map((l) => l.trim()).filter(Boolean);

    return {
        description: descLines.join("\n").trim(),
        run: runLines,
        code: code.trimEnd(),
    };
}

const blocks: string[] = [];
for (const file of EXAMPLES) {
    const { description, run, code } = parseExample(readFileSync(resolve(examplesDir, file), "utf8"));
    const parts = [`## [\`${file}\`](${GITHUB_BLOB}/${file})`, ""];
    if (description) parts.push(description, "");
    if (run.length) parts.push("```bash", ...run, "```", "");
    parts.push("```ts", code, "```", "");
    blocks.push(parts.join("\n"));
}

const contents = `---
sidebar_position: 9
title: Examples
---

<!-- Generated by scripts/gen-docs-examples.ts from examples/*.ts — do not edit by hand. -->

# Examples

Runnable, end-to-end examples for \`@alpacahq/alpaca-trade-api\`, generated from the
[\`examples/\`](${GITHUB_BLOB}) directory so the code below always matches the repo.

The examples import from the local source (\`../src\`) so they run straight from a
clone; in your own app the import is simply \`from "@alpacahq/alpaca-trade-api"\`
(shown in a comment at the top of each file). They are type-checked against the
current SDK source as part of \`npm run typecheck\`, so they can't silently drift
out of sync with the API.

## Prerequisites

- Node.js ≥ 20
- Paper-trading API credentials from <https://app.alpaca.markets/paper/dashboard/overview>
- [\`tsx\`](https://github.com/privatenumber/tsx) to run TypeScript directly
  (\`npx tsx ...\` will fetch it on first use)

Export your credentials once:

\`\`\`bash
export APCA_API_KEY_ID="your-key-id"
export APCA_API_SECRET_KEY="your-secret"
\`\`\`

${blocks.join("\n")}`;

writeFileSync(outFile, `${contents.trimEnd()}\n`);
console.log(`Wrote ${EXAMPLES.length} examples to ${outFile}`);
